### ISSUE TITLE
Source ver

### ISSUE THREAD

**Issue by royalspin** [monyxcoin/monyx-coin#1]
You just changed readme to ver 2
Wallets still have "version" : "MYX-v1.0.0.build-g-bdb-gcc"

**Comment by monyxcoin** [comment]
Thanks, will change their version too. 
Though this is just the wallet version itself, it shouldn't affect anything really.

**Comment by new2018man** [comment]
@monyxcoin what time opwn lending and exchange?

**Comment by monyxcoin** [comment]
@new2018man this information will be available on Twitter and Telegram

**Comment by monyxcoin** [comment]
Fixed
