### ISSUE TITLE
Exchange is not working, please check!

### ISSUE THREAD

**Issue by Bonboni** [monyxcoin/monyx-coin#10]
Guy´s,
The exchange is filld up with Buy orders- but no sales are going through and the prize for MYX is not moving, should be past $5 by now with this pressure.
Please check it

**Comment by NeekCrypto** [comment]
MonyX Team, please advise if you're aware of this issue; Buy/ Sell orders are not being filled. No one is able to buy and sell.

**Comment by srinuperumalla** [comment]
I'm not aware...is the bye and sell is not working??

**Comment by monyxcoin** [comment]
@Bonboni @srinuperumalla @NeekCrypto sorry for the inconvenience, the dev working on the exchange is aware and as far as I know the bug is fixed and shouldn't happen in future.

**Comment by NeekCrypto** [comment]
Great to hear the bug has been fixed. But why hasn't the price moved from $1.80 in hours? It also doesn't show any of the 'sell orders' in order history.
