### ISSUE TITLE
Mac OSX wallet

### ISSUE THREAD

**Issue by BryerTuck** [monyxcoin/monyx-coin#100]
Downloaded the Max OSX wallet but I can't get it open and it crashes as soon as I open it. I'm running Mac OSX 10.10.5. I tried looking for the folder in /Library/Application Support/Monyx but the folder isn't there or anywhere else on my computer. Any ideas on how I can fix it?

**Comment by aid0123** [comment]
try to redodwnload

**Comment by BryerTuck** [comment]
Tried several times. Before the staking announcement and every day since. Deleting all the files and re-downloading and trying to open. Same problems.

**Comment by monyxcoin** [comment]
@BryerTuck there is a know issue about incompatibility of the currently published wallet and macOS versions < Sierra.

We're working on resolving this issue and releasing the wallet compatible with older macOS versions.

Would be useful though if you attach the content of the crash report here.
