### ISSUE TITLE
Btc not deoosited

### ISSUE THREAD

**Issue by jv65644** [monyxcoin/monyx-coin#101]
Sent btc 2 days ago. Has not showed up?

**Comment by jv65644** [comment]
Summary
Address
33rPe89rWLy4nS4mc47e83NRyDJB88GS5Q

Hash 16017b61fa3096e03ad72cb8905637f85872cdbf135

**Comment by chass3768** [comment]
better check to make sure you sent it to the right wallet!

**Comment by jv65644** [comment]
That is weird. I copy and pasted direct from myx wallet tab and some how it ended in Q instead of QZ??

**Comment by monyxcoin** [comment]
@jv65644 i see that the transaction is in our system, so address was correct. It should be deposited soon.

**Comment by jv65644** [comment]
Ok ty got it just now
