### ISSUE TITLE
Wallet question+issue with missing BTC deposit on Monyx platform

### ISSUE THREAD

**Issue by Xatra47** [monyxcoin/monyx-coin#103]
Hello Team,

My Monyx user's profile name is Xatra47.
0.0571 BTC sent one day ago. Transaction ID:
03fb7bf8558940b4f906e8a48d389ea55c1e16c490ec9b0c817418b1334f2257
156 Confirmations and still pending on the platform. I sent some emails without any acknowledgment or answer...

Moreover, Do I need to let my computer turned on when staking or could I send MYX (once I'll buy some with my missing BTC), unlock the wallet then turn it off or sleep mode?

Thank you for your help,
Rgds,

Xatra47

**Comment by Xatra47** [comment]
BTC received for info.

**Comment by monyxcoin** [comment]
@Xatra47 good piece of information about PoS can be found here: https://github.com/novacoin-project/novacoin/wiki/Proof-of-stake.

In short - yes, you need to keep the wallet connected to the network to receive a reward.
