### ISSUE TITLE
kindly fix monyx exchange ????

### ISSUE THREAD

**Issue by saurabh1dec** [monyxcoin/monyx-coin#104]
issue solved

**Comment by chass3768** [comment]
they have a 1000 coin sell limit a day set right now. it is not a bug or glitch. you have reached your limit for the day.

**Comment by saurabh1dec** [comment]
monyx i need official reply on this issue.........

**Comment by saurabh1dec** [comment]
thanks Chass but they should reply us officially as well if its not bug ????

**Comment by chass3768** [comment]
Read the sxchange it self explanatory! 1000 coin limit a day to sell!

**Comment by saurabh1dec** [comment]
issue solved thanks
