### ISSUE TITLE
Incentivize Marketers for Referrals

### ISSUE THREAD

**Issue by doncrypto** [monyxcoin/monyx-coin#106]
Hi Monyx Dev.
I actively promoted Monyx after the ICO and have a significant amount of referrals. I just want to bring this up so you don't forget about us that promoted monyx after the ICO to bring people to the lending platform. I know you are actively working on the new platform because of recent events. I wanted to being this up so you don't forget us and still incentivize us to continue promoting monyx.

Thanks.
DC

**Comment by monyxcoin** [comment]
@doncrypto right, considering the recent events (court orders against Davorcoin, their shut down, bitconnect and many other things that happened in last few weeks) we decided to move the platform in another direction. Once we work through details, we will release a new whitepaper, official statements, etc.

In any case referrals collected by users will be used in some form in the new product.
