### ISSUE TITLE
IMPORTANT: Daily Update

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#107]
Gud evening,  coming directly from the community, we would like further news from the Monyx Team. 
Though we understand the hard work you guys are putting in the background we would appreciate that you refrain from your old ways and give us daily updates however small as this will keep us all updated and remove any doubts and yes prevent many of this kind of questions coming up.

Daily updates in the News page however small is good news.
Let us know when we can expect this update. 

The Ultimate mountain of desire, The mountain of molten lust
Carlos Matos
aka: The Ultimate Male

**Comment by doncrypto** [comment]
I prefer they say less and do more.
That's their style.

Why do you still have doubts?
Be confident in your investments.

**Comment by monyxcoin** [comment]
@alexpride007 @doncrypto I asked the team to release news more often, unfortunately I didn't get any response from them regarding this, I guess they are still very busy with other legal/new whitepaper/etc stuff.
