### ISSUE TITLE
Staking Tokens Unavailable 

### ISSUE THREAD

**Issue by Sirbearingson** [monyxcoin/monyx-coin#108]
So its been 36 hours of having my tokens in my Wallet and i have not received any monyx...
SOMEONE HELP 
I was told by Admin it takes 24 hours to activate

**Comment by doncrypto** [comment]
It takes 24 hours for your coins to mature and BEGIN staking. Depending on the network and how many coins you have it could take even longer to get a stake.

**Comment by Sirbearingson** [comment]
okay so my next question is how often are we rewarded as stakers?

**Comment by monyxcoin** [comment]
@Sirbearingson the more addresses in the network having tokens, the lower the chance. Every time the address is determined randomly.

You can read more on how PoS works here: https://github.com/novacoin-project/novacoin/wiki/Proof-of-stake
