### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Homeuser17** [monyxcoin/monyx-coin#109]
Hi,

How do I start mining the Monyx coin?

Many thanks,

HU

**Comment by Sirbearingson** [comment]
YES PLEASE SOMEONE HELP HOW DO WE MINE!?!?

**Comment by chass3768** [comment]
If you look in the wallet you will see a section called minting. Your coins should be already in that section being used for confirmation and mining purposes. The output is also tied to how many active connections you have I believe.

**Comment by jwsbj** [comment]
its called minting in your wallet
i guess its a form of mining 
it will need to mature i have already started 'minting'
just transfer funds then go to settings, then wallet security & unlock for mining
the next day around 24 hrs+ it will start minting and you just allow it to progress

**Comment by doncrypto** [comment]
you need to be more specific, there are 2 ways to mine: pos or pow. Which one are you talking about?

**Comment by monyxcoin** [comment]
@Homeuser17  I'll compose a FAQ section here about mining on this weekend.

**Comment by monyxcoin** [comment]
@chass3768 @Homeuser17 @doncrypto thanks for the helping answers!
