### ISSUE TITLE
Disable 2fa button

### ISSUE THREAD

**Issue by brunoski1** [monyxcoin/monyx-coin#11]
2fa buttons for disabling if not able to login

**Comment by brunoski1** [comment]
Option to disable 2fa if one has lost their personal 2fa codes via the Google authenticator app disable button allowing a user access to the platform for a confirmation to email and telephone for security it's not possible

**Comment by monyxcoin** [comment]
@brunoski1 let me know if you need the 2fa disabled, I'll also ask the dev working on the website about possible solutions to this problem.

**Comment by bakuleshkanakia** [comment]
Dear MonyX team,
I have also lost my mobile and do not have a backup of the 2fa code. My MonyX account in bakulesh@gmail.com

Can you please help me as well with disabeling 2fa for my account.

**Comment by monyxcoin** [comment]
@brunoski1 done

**Comment by bakuleshkanakia** [comment]
Thanks!
