### ISSUE TITLE
Mining Q and A  For noobies

### ISSUE THREAD

**Issue by Sirbearingson** [monyxcoin/monyx-coin#112]
How can i get started mining monyx knowing zero information on the basis of mining besides my computing power and This Github 
any downloads?
plzz help!

**Comment by monyxcoin** [comment]
@Sirbearingson I'll compose a FAQ section here about mining on this weekend.

**Comment by Sirbearingson** [comment]
Thanks @monyxcoin 
I appreciate your response
The FAQS will be WELL Appreciated <3
