### ISSUE TITLE
Stolen MNX ?

### ISSUE THREAD

**Issue by Yaqoubalali** [monyxcoin/monyx-coin#113]
Dear Dev,

My user name htcrypto and my account get hacked on Feb 7 and 1027 sold in exchange and resulted in BTC withdrawn by the hacker. ? My password my strong since it contains a special letter and small and capital letters in addition to numbers.
Can you help and refund my MNX?

**Comment by chass3768** [comment]
Better check whatever device you are using for malware! Always use a VPN  and change IP addresses frequently!

**Comment by monyxcoin** [comment]
@Yaqoubalali what is your username?

**Comment by chass3768** [comment]
@monyxcoin They said their user name is htcrypto.

**Comment by Yaqoubalali** [comment]
The user name which hacked is htcrypto. 
Can you help with recovering my stolen MNX?

**Comment by monyxcoin** [comment]
@Yaqoubalali should be fixed now
