### ISSUE TITLE
Withdrawal

### ISSUE THREAD

**Issue by Blitzkitten** [monyxcoin/monyx-coin#114]
Hi guys,

I did the noob thing and didn't read the full disclosure about withdrawing funds and sent all mine out (only recently).

Currently my dashboard says 0 MYX available. The wallet page shows that all my MYX are there. My personal wallet has no transactions.

Is this just a case of waiting for the withdrawal to be processed? I just wanted to get staking! 

Just a bit freaked out as I read afterwards (like a chump) that it's not a good idea to do big transactions at the moment. 

Thanks

Username is Blitzkitten just in case you look in to it.

**Comment by monyxcoin** [comment]
@Blitzkitten you should be able to withdraw the amount if previous try is failed.
