### ISSUE TITLE
Back up staking

### ISSUE THREAD

**Issue by KMD89** [monyxcoin/monyx-coin#115]
Hi guys,

How can I make a proper back-up?

Every time I make a back up it’s just an white paper and it doesn’t work. I lot of other people have the same issue could you please tell us how it’s done?

Thanks in advance!

**Comment by monyxcoin** [comment]
@KMD89 what do you mean by "back up"? What exactly do you want to do/achieve?

**Comment by KMD89** [comment]
@monyxcoin I want to make an backup of my desktop (windows) wallet. In case somethings happens i want to have a backup and restore it.

But every time I do this, I get an empty file and I can only safe this file as ''Wallet Data (*.dat) '' After i save the file it doesn't open. 

I am concerned because I don't know if the backup of my wallet worked, and if it worked how will i be able to restore it if needed?

**Comment by Blitzkitten** [comment]
Dude

Just go in to your users\YOURUSERNAME\AppData\Roaming\Monyx folder

select the wallet.dat file
copy it, paste it somewhere else.

JOB DONE

Restore it by pasting it back in there.

NEVER DELETE THAT FILE!

**Comment by monyxcoin** [comment]
@KMD89 interesting, so the "Backup wallet" function doesn't produce a valid wallet file? Do you use Windows?

**Comment by KMD89** [comment]
it creates an File but i cant open it or anything, so therefor i don't know it i useful or not. Yes i use a windows wallet.

**Comment by Blitzkitten** [comment]
Backup works fine for me.

If you want to double check... cut & paste the wallet from users\YOURUSERNAME\AppData\Roaming\Monyx folder

put back up wallet file in there and make sure it's call wallet.dat

open your wallet, if your address and coins are there then it worked fine.

**Comment by monyxcoin** [comment]
@KMD89 so I think you need to try to run the wallet with the new `wallet.dat` you backed up before to test if it works as intended. I tested it on my windows machine, it seems to work fine.

**Comment by KMD89** [comment]
It works now thank u!
