### ISSUE TITLE
Query on Project's new direction

### ISSUE THREAD

**Issue by JagCrypto** [monyxcoin/monyx-coin#116]
Hi Team,
I understand the project has took change towards new more profitable direction. Could you please explain on high level on the future plan?  Are you planning to provide Interest on staking? Do you still have Algorithmic Trading powered by AI ? With out lending how will the token holders going to earn profit? Do the ICO investors need to wait for ages for token appreciation? Please elaborate the future prospects atleast on high level. Suspense kills..

regards,
Jag

**Comment by jwsbj** [comment]
staking works, its generating revenue it builds up as it matures so it starts off slow and takes over 24hrs t start up

**Comment by monyxcoin** [comment]
@JagCrypto the team discussing the plan, I think the official statement will be ready on the next week.
