### ISSUE TITLE
QT WALLET WONT SYNC UP

### ISSUE THREAD

**Issue by DAATHVEGA** [monyxcoin/monyx-coin#118]
DOWNLOADED MONYX WALLET AND LEFT OPEN FOR MORE THAN 24 HOURS...WHY HASNT THE WALLET SYNC YET?

**Comment by monyxcoin** [comment]
@DAATHVEGA provide please your `degub.log` file.

**Comment by DAATHVEGA** [comment]
Ok...where do I find that?

**Comment by DAATHVEGA** [comment]
[debug.log](https://github.com/monyxcoin/monyx-coin/files/1712064/debug.log)

**Comment by monyxcoin** [comment]
@DAATHVEGA most likely you have the old wallet. Try to download the new one and delete everything **EXCEPT** `wallet.dat` file from the folder where you found `debug.log` file.

**Comment by DAATHVEGA** [comment]
The only file present is the exe file...I don't know of a way to delete the
wallet data before the app can launch

**Comment by monyxcoin** [comment]
@DAATHVEGA do you use macOS or Windows?

**Comment by DAATHVEGA** [comment]
windows, but problem solved after i deleted everything but wallet.dat


Powered by Cricket Wireless
-------- Original message --------From: "monyx.io" <notifications@github.com> Date: 2/11/18  11:25  (GMT-05:00) To: monyxcoin/monyx-coin <monyx-coin@noreply.github.com> Cc: DAATHVEGA <DIGIDUNN@GMAIL.COM>, Mention <mention@noreply.github.com> Subject: Re: [monyxcoin/monyx-coin] QT WALLET WONT SYNC UP (#118) 
@DAATHVEGA do you use macOS or Windows?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/monyxcoin/monyx-coin","title":"monyxcoin/monyx-coin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/monyxcoin/monyx-coin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@monyxcoin in #118: @DAATHVEGA do you use macOS or Windows?"}],"action":{"name":"View Issue","url":"https://github.com/monyxcoin/monyx-coin/issues/118#issuecomment-364764335"}}}
