### ISSUE TITLE
Missing Bitcoin Balance.

### ISSUE THREAD

**Issue by combofiend** [monyxcoin/monyx-coin#119]
username : freemonyx

https://blockchain.info/tx/74c4e325e294e9050c53952b39463646bc9c5f682b3c8e4803c3449e11d452bb

**Comment by combofiend** [comment]
check my btc. wallet. https://chain.so/address/BTC/3MaHorDRTfUuviYq63Gn3LuqJagPmwmeAV

**Comment by combofiend** [comment]
No pending. EMPTY BALANCE what happen. to my -0.02577171 btc 😭

**Comment by combofiend** [comment]
pending nothing. EMPTY BALANCE what happen. to my -0.02577171 btc 😭

**Comment by monyxcoin** [comment]
@combofiend i see that the transaction was deposited and then used to buy 388 and 11 MYX. Now you have 684 MYX on your balance.
