### ISSUE TITLE
Option to disable 2fa for lost authentication 

### ISSUE THREAD

**Issue by bakuleshkanakia** [monyxcoin/monyx-coin#12]
Dear MonyX team,

Can you please help me as well with disabling 2fa for my account. I have lost my mobile and can not access the 2fa code from the google authenticator.
my MonyX account is registered with bakulesh@gmail.com

Thanks

**Comment by monyxcoin** [comment]
@bakuleshkanakia done

**Comment by bakuleshkanakia** [comment]
Thanks!
