### ISSUE TITLE
Stolen my monyx coin

### ISSUE THREAD

**Issue by rathorepritish** [monyxcoin/monyx-coin#120]
My name is Pritish Rathore

I have been so excited to be part of Monyx ico family and I have bought 1908 during ico. Now I have problem about my account. I have lost my monyx coin , So can you please help me to resolve this .

My user name is pritishrathore  and email address is pritish.rathore@gmail.com !

**Comment by monyxcoin** [comment]
@rathorepritish I don't see any transactions in the database related to your account. Can you please provide transactions ids or addresses you used to deposit the account with BTC?

**Comment by rathorepritish** [comment]
Its was not generated i dnt know what happened here with me in my
transition history

**Comment by monyxcoin** [comment]
@rathorepritish I need from you anything that can prove you had the coins, it can be a transaction id of one of your deposits, or a screenshot, maybe a BTC address you used to deposit your wallet to buy MYX during the ICO.

**Comment by rathorepritish** [comment]
You can see in pictures 25 dec 2017 i have deposit for purchase monyx Coin

**Comment by monyxcoin** [comment]
@rathorepritish I checked the older dumps of our database - there are no transactions for your account and you had zero balance.
Maybe you had another account?

**Comment by rathorepritish** [comment]
This is unfair with me I don't know what happeneding with me
