### ISSUE TITLE
Suggestion if you don't mind looking at this.

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#123]
I was wondering if the Monyx team might consider raising the Stake Interest Percent as a bonus since lending is no longer active. I do understand you guys are working on a replacement but I was wondering if you might consider it since many members enjoy Staking as myself. It would also help keep coins on the platform. 

Thanks for considering.

**Comment by manojaum** [comment]
If no lending then please consider staking with staking profit in btc or eth.

**Comment by monyxcoin** [comment]
@2themoonandback unfortunately we can't rise the staking rate, because it would need the network reset, so let's wait for the new whitepaper and official statement the team is planning to release on the next week.
