### ISSUE TITLE
Monyx Good Project 

### ISSUE THREAD

**Issue by combofiend** [monyxcoin/monyx-coin#124]
hello. monyx if you want to skyrocket your coin. why you dont create trading site. like binance and huobi. or follow the step of davor. this is a good project i want see monyx coin $1000 per coin.  and e-commerce and put banking to instant withdraw.

**Comment by combofiend** [comment]
release new white paper or roadmap, ASAP.

**Comment by monyxcoin** [comment]
@combofiend I'm not responsible for the team's plans, I think they were planning to release a new whitepaper/statement describing the new direction on the next week, not sure when exactly.
