### ISSUE TITLE
0 active connections

### ISSUE THREAD

**Issue by jv65644** [monyxcoin/monyx-coin#126]
Can not sync windows wallet because it says 0 active connections?

**Comment by chass3768** [comment]
Make sure you have allowed it to pass traffic through your firewall and virus protection, If your security is blocking the incoming and outgoing traffic from the wallet it wont get connections.

**Comment by monyxcoin** [comment]
@jv65644 right, It could be a firewall that disables all connections (you need to have the port 41906 opened), in rare cases it can take few hours to find connections and sync the wallet.

**Comment by jv65644** [comment]
ive tried all above info and still no luck. :/
