### ISSUE TITLE
Release new plan before exchange 

### ISSUE THREAD

**Issue by animalmode** [monyxcoin/monyx-coin#127]
I advise you to release your plan of monyx moving forward, And what monyx can offer for their investors before you take the sell limit off on the exchange. Right now people aren't seeing much value in the coin because there's no offer to make money from the coins, So people will dump the coins on the exchange when they get that opportunity.

Maybe you should do something very similar to thorn coins setup, Their idea is what looks promising for lending platforms to do well and survive.

**Comment by chass3768** [comment]
I absolutely hope people dump their coins on the exchange so I can buy them up for cheap!

**Comment by monyxcoin** [comment]
@animalmode I'm not responsible for the team's plans, I think they were planning to release a new whitepaper/statement describing the new direction on the next week, not sure when exactly.
