### ISSUE TITLE
Windows wallet keep disappearing 

### ISSUE THREAD

**Issue by IamTheM8** [monyxcoin/monyx-coin#128]
After I install, run the wallet everything is fine. But when I want to look for the .exe of the wallet it's gone. Every time after I run the wallet, the .exe disappears.

I don't have activated the antivirus nor the firewall.

Hope you can tell me how to fix.

Best to the project

**Comment by chass3768** [comment]
Are you running the 64bit wallet or the 32bit? I have zero issues with the 32bit one. The .exe file should always be in your download folder, unless you moved it to a different location after download. I moved mine to my desktop for easy access, but I keep the wallet open and running 24/7.

**Comment by IamTheM8** [comment]
I have the 64bit, and always after running the wallet, the .exe disappear , just the .exe nothing more

**Comment by IamTheM8** [comment]
I tried that but still same problem, keeps disappearing from anywhere I put the .exe

**Comment by monyxcoin** [comment]
@IamTheM8 interesting, I don't think the wallet is capable of deleting it's own executable, it's just not programmed in the code, so I guess that's the problem with your windows setup, unfortunately I can't help with that.

**Comment by monyxcoin** [comment]
@IamTheM8 you can try to use this method to disable deletion, maybe it will help: https://answers.microsoft.com/en-us/windows/forum/windows_7-files/protect-files-from-being-deleted/814dbe4c-8957-4e39-9fd7-b613e2812851?auth=1
