### ISSUE TITLE
Monxy Wallet Download issue

### ISSUE THREAD

**Issue by SimonSimon999** [monyxcoin/monyx-coin#129]
I´ve downloaded my wallet but it won´t sync. The Debug isn´t working ... I´ve been waiting hours and nothing is happening. What do I need to do? 
[debug.log](https://github.com/monyxcoin/monyx-coin/files/1714368/debug.log)

**Comment by monyxcoin** [comment]
@SimonSimon999 seems like the old wallet. Try to download a new version and delete the monyx folder before starting the new wallet.
