### ISSUE TITLE
Exchange Issues

### ISSUE THREAD

**Issue by drcrypto123** [monyxcoin/monyx-coin#13]
None of the sell orders going through. Something is wrong with the exchange. I do not see any buy orders to chose from as well. 

Windows wallet is missing, Lending platform is broken! Support not replying back, no info on twitter or any communication through telegram.

Kindly resolve

**Comment by loydz21** [comment]
Please no pressure to devs..i know they do there best to make the platform run smoothly all we have to do is wait and believe to the devs..

**Comment by drcrypto123** [comment]
Its not pressure, we want clarification and some actual development. Nothing is working as of now i need to know what can we expect in future.

**Comment by monyxcoin** [comment]
@drcrypto123 windows wallet is coming today, working on it just right now!

Sell orders don't go through because there is a huge sell wall, that can't be compensated by the amount of buy orders we get currently.

Lending is not enabled yet and is coming soon.

Regarding other issues with communication - I'll ask the team.

**Comment by drcrypto123** [comment]
Thanks!

**Comment by loydz21** [comment]
What happen to the price??

**Comment by drcrypto123** [comment]
Monyx have started dumping there own coins

**Comment by loydz21** [comment]
I hope it will back to normal

**Comment by monyxcoin** [comment]
@drcrypto123 no, nobody is dumping the coins.

The price was pegged to 1.80 USD on launch, to have a stable and safe launch. Now the price is set free.

**Comment by loydz21** [comment]
Ohhh..i see what do you want us to do to set price up again sir monyx?

**Comment by drcrypto123** [comment]
Thanks! That is the best thing and very good news! Brings some confidence in platform
