### ISSUE TITLE
staking

### ISSUE THREAD

**Issue by bang121** [monyxcoin/monyx-coin#130]
i have sataked my coin in desktop wallet i also got my first mint reward. but after i got my reward it turned into too young (blue colour).so is there any problem ??? or we have to wait for 24 after every minting reward ?????
![send](https://user-images.githubusercontent.com/36374713/36075297-e6416c78-0f72-11e8-9b43-cf45999e4823.png)

**Comment by bang121** [comment]
see i have just recived new minting reward my my mature coin change to too young coin.
![send2](https://user-images.githubusercontent.com/36374713/36075342-71aaf432-0f73-11e8-8990-c76b0a11b8b6.png)

**Comment by monyxcoin** [comment]
@bang121 every time you get a reward, the transaction resets, so yes, it's the intended behavior.

**Comment by bang121** [comment]
then how it is possible 10 % per month in last 58 hr i have just received 1.59 coin. how u calculate 10% staking reward ? as per calculation it should be .75%return and till now i have received 1.59 coin.  please explain in details. thank you in advance
