### ISSUE TITLE
genesis block help

### ISSUE THREAD

**Issue by FrankFromFrance** [monyxcoin/monyx-coin#134]
Bonjour monyx from France ! ;-)

I'm trying to learn the amazing process of genesisblock creation, it seems like you guys got it down.

First, I set merkleRoot to "0x"
https://github.com/monyxcoin/monyx-coin/blob/master/src/main.cpp#L2591

Next, I execute on my linux terminal to get epoch time `date +%s`, I set :
txNew.nTime = (current epoch time);
block.nTime = (current epoch time);

I also changed pszTimeStamp & removed checkpoints references.

Lastly , I set genesisHash to "0x"
https://github.com/monyxcoin/monyx-coin/blob/master/src/main.h#L66

Ok, now I compiled  on linux
`make -f makefile.unix`

I ran the headless monyx, and it crashed (as expected).

I got the new merkle root in debug.log, and pasted it to
https://github.com/monyxcoin/monyx-coin/blob/master/src/main.cpp#L2591

I recompiled, and ran headless monyx again, but it's not creating genesis block !

to be more clear, I have not seen such message in debug.log
https://github.com/monyxcoin/monyx-coin/blob/master/src/main.cpp#L2582

Is it possible I missed any step ? There is a long pause when I run headless monyx "Loading block index...".

Please, let me know if I did a wrong. I want to create a test blockchain very badly . Merci monyx ! 🇫🇷

**Comment by monyxcoin** [comment]
@FrankFromFrance hi, glad to see somebody interested in technical details!
Did you also change the genesis block hash here https://github.com/monyxcoin/monyx-coin/blob/master/src/main.h#L66 to the one you got in the `debug.log` after crash?

**Comment by FrankFromFrance** [comment]
@monyxcoin 
Hi,

After the initial start up `./Monyxd` - it crashed due to the assert of:
`assert(block.hashMerkleRoot == uint256("0x"));`

I checked my debug.log and this line printed out a hash:
https://github.com/monyxcoin/monyx-coin/blob/master/src/main.cpp#L2588

I set this hash to the assert line. `assert(block.hashMerkleRoot == uint256("0x(my hash)"));`

is this the same hash I should set for genesisblock you pointed out? I'm not too sure where to get the genesis block hash. Thank you.

**Comment by monyxcoin** [comment]
@FrankFromFrance the line above also prints the block hash: https://github.com/monyxcoin/monyx-coin/blob/master/src/main.cpp#L2587

Can you show me your `debug.log` file please, I'll point you to the block hash that you should set as the genesis block hash in `main.h`?

**Comment by FrankFromFrance** [comment]
@monyxcoin 

Ok, I think I see what you mean now, I'll try it out in a few hours because I forgot to get my USB with the ssh keys to my linux server.

Anyways, I think much confusion came from while I was forking litecoin. I had to set the merkle root, recompile, and then it would mine the genesis block trying out hashes, and after it successfully mined it it would spit out the genesis hash. (2 step process).

If I'm understanding everything correctly now, when monyx starts up (and fails) it should spit out the merkle and genesis hash after the same running session. And after I set both of those, the new chain should be created. ;)

I'll nano the debug log and set that genesis hash, I recall seeing it before but I wasn't too sure what to make of it before.

**Comment by monyxcoin** [comment]
@FrankFromFrance exactly, it's all done in one session. Let me know later if it worked for you :)

**Comment by FrankFromFrance** [comment]
@monyxcoin 

It worked. Thank you so much! I cannot believe how simple it was to do, but I was over complicating it.
Tomorrow, I'm going to try to compile GUI wallets. Learning these things is very fun!

Merci ;-)

**Comment by FrankFromFrance** [comment]
@monyxcoin 

One last thing. I have added gen=1 in my config to start mining. However, no blocks are being created. I believe at least 2 nodes need to run for blocks to be created and gen=1 needs to be in config, correct?

**Comment by FrankFromFrance** [comment]
@monyxcoin Is it possible to mine on a node running monyxd? Seems like set generate command was removed.
