### ISSUE TITLE
Problem with the window wallet

### ISSUE THREAD

**Issue by paschkka** [monyxcoin/monyx-coin#135]
Hey, 
I already installed the wallet and transfer some funds over it. I worked fine so far, but since today I cant open it.  Everytime I try to open, I got a failure:

Assertion failed!
Program:C:\.........\MonyxQT.exe
File:..\\..\\src\kernel.ccp
Line: 494

Expression: pindex->pprev || pindex->GetBlockHash()==(!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)

Heelp please. 
@monyxcoin

**Comment by monyxcoin** [comment]
@paschkka try to delete everything **EXCEPT** `wallet.dat` file in the Monyx folder.

**Comment by paschkka** [comment]
I made a backup of my wallet, before.. Is it enough?? Don´t know how to extract, the wallet.dat, if i can´t find the folder!
Should i reinstall it or is there no solution so far??
@monyxcoin

**Comment by monyxcoin** [comment]
@paschkka go to `C:\Users\YourUserName\Appdata\Roaming\Monyx`and delete everything except wallet.dat.

**Comment by chakramchirkut** [comment]
@paschkka  - could you please confirm if your problem is solved ? if so could you please close the ticket ?

tip: another easy way to find the folder is 
Open My computer -> type %appdata% in the address bar and hit Enter -> here you should see Monyx folder.

**Comment by Adebola100** [comment]
@paschkka @monyxcoin this process does not work, I backed up my wallet before following the steps, deleted everything accept wallet.dat and ended up losing all my coins and still not sync to network
