### ISSUE TITLE
IMPORTANT PLS READ: RECOMMENDATION FOR MONYX

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#136]
Hi, gud day

Since the ICO, the industry has changed dramatically and everyone must adapt. There is real fear in the industry (much of which is unjustified). Lending platforms have been given a terrible name because of these exit scams, and monyx really do not want to be associated with any such platforms.

Thus YOU -  Monyx need to change how you work.The entire platform/exchange needs rethinking to make sure Monyx is profitable for everyone involved. 

You will create/ announce a new trading artificial intelligence called Monyx AI that will trade on behalf of the investors and earn interest when in profit. So....

1) Monyx should drop the word ‘Lending’. Investors are no longer lenders but are traders. If you want Monyx AI to trade on your behalf then you will create a ‘Trade‘ with Monyx to send to the Trading Pool (TP).

2) Monyx should float against Bitcoin (MONYX/BTC pair) to attract  more investors

3)Marketmore competitive interests rates for 'Staking' so help ensure value of the coin increases

The 3 above examples are just ways to rebrand your platform so that it moves away from the image of a 'lending' platform to an AI trading / Staking platform.

Do read and carefully consider the above ideas as I believe this will be the way forward for Monyx. I hope to see the above's implemented or at least allow the public to vote.

Yours sincerely 
Carlos Matos

**Comment by animalmode** [comment]
lol that's identical to Bitai.

**Comment by myfunnelpays** [comment]
good suggestions Carlos Matos...

100% AGREE!

Also to add to it, let there be transparency by showing the trades going to the pools and profits generated as well...

#Monyx To The MOON!!!

**Comment by Ghabh** [comment]
This is the best solution monyx should do.

**Comment by monjil43** [comment]
lol man you guys sill dreaming....so funny
