### ISSUE TITLE
monyx,please don't be one of those lending platforms

### ISSUE THREAD

**Issue by aid0123** [monyxcoin/monyx-coin#137]
Hello, Myx.Please open withdrawals today, I need my money back, do not scam ,I believe that U will find a better way to earn more,oh pls.Hype surrounding your platform is tremendous, so try to benefit from this by creating something revolutional,that's trully possible with funds u have from ICO.

**Comment by monyxcoin** [comment]
@aid0123 we're going to put the platform in maintenance mode in few hours and withdrawals will be enabled.

**Comment by aid0123** [comment]
Thnaks so much
