### ISSUE TITLE
missing monyx. ...!

### ISSUE THREAD

**Issue by parasghelani43** [monyxcoin/monyx-coin#138]
i did't recieve any BTC amount. you will check my transaction history.

**Comment by monyxcoin** [comment]
@parasghelani43 checking.

**Comment by monyxcoin** [comment]
@parasghelani43 I see that you bought 11 MYX, there were no other transactions. You still have them on your balance.

**Comment by parasghelani43** [comment]
sry i send the different username kindlly check this "parasghelani29 "
thank u
