### ISSUE TITLE
Missing my monyx coin

### ISSUE THREAD

**Issue by rathorepritish** [monyxcoin/monyx-coin#139]
Dear sir 
I have 1,779.37325220 MYX coin but its not showing in my wallet what happened with me ??
User name - rathorepritish
Email id - rathorepritish@gmail.com

**Comment by monyxcoin** [comment]
@rathorepritish you was one of the users whose balance was affected by the bug, so you got 0.08168995 BTC than needed.
Since you didn't have any BTC on your account, we deducted the equivalent amount of MYX.

**Comment by rathorepritish** [comment]
No sir i have not got any btc ,, some hacked my account 7feb after i was complained reports here after i have returned btc again and purchase monyx  again

**Comment by rathorepritish** [comment]
7 feb i have also deposit 0.00719870 BTC in my wallet and purchase some monyx coin its is also dedication from my account

**Comment by rathorepritish** [comment]
This is unfair with me i have not received any btc 0.08168995  and l also complained regarding to this on 7 feb you can checked it here

**Comment by monyxcoin** [comment]
@rathorepritish ok, give me some time to investigate it closely.

**Comment by rathorepritish** [comment]
This unfair with me

**Comment by monyxcoin** [comment]
@rathorepritish should be restored to the point where bug affected the balance.

**Comment by rathorepritish** [comment]
Thank you sir

Give me life again i was died for some time
