### ISSUE TITLE
Price on roadmap

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#14]
@monyxcoin is there any chance myx hit the roadmap price for the month of february?

**Comment by drcrypto123** [comment]
No one knows! Its open market. depends on buying and selling volume. One mistake they have done is not starting the lending and staking before un-pegging the fixed value of $1.80

**Comment by loydz21** [comment]
I Think they can manipulate the price of if they want to..

**Comment by jaytan17** [comment]
Anybody here has btc issue?  Coz I've lost all of my btc in the site and it show now negative. It's so strange ..

**Comment by loydz21** [comment]
No, I didn't have any  problem..

**Comment by drcrypto123** [comment]
@loydz21 why would they? They have to give interest in lending. Manipulation wont be sustainable even in near short term.
@jaytan17 No problem here as well.

**Comment by jaytan17** [comment]
Ah ok. Coz I tried to trade few hours ago.. At first it was smooth.  But now all of my btc are gone. Hopefully they fix my account

**Comment by loydz21** [comment]
@drcrypto123 at this moment, i think the dev accidentally click the anti pegging button that shouldn't happened..bcoz of this negative comments and post..the dev allow it so that there are no more complains.

**Comment by loydz21** [comment]
But I the dev can restore it if the devs wants to.

**Comment by drcrypto123** [comment]
There are no accidents my dear friend

**Comment by loydz21** [comment]
Well, i guess but its not too late.

**Comment by monyxcoin** [comment]
I'm not responsible for the decision the team working on exchange makes, sorry.

The only thing I know I answered in another issue.

**Comment by loydz21** [comment]
@monyxcoin no problem sir i think the best option to pump the price is to successfully release the lending the soonest.

**Comment by NeekCrypto** [comment]
It's going to be tough coming back from this .20 cent price mark. A safety net should've been in place to keep the price point above $1.80. If it was me, I would reset the entire buy/ sell orders from this morning, and come back strong with a fresh-slate and functional exchange. Like Jamie Foxx sang "Blame it on the alcohol"... Monyx can "Blame it on the bugs" lol... we won't be mad at cha!

**Comment by monyxcoin** [comment]
I'm not sure we're able to reset all orders. Anyway the exchange and price will stabilize during next few days.

The lending will be released as soon as we can.
