### ISSUE TITLE
BTC & Coins missing

### ISSUE THREAD

**Issue by malyk** [monyxcoin/monyx-coin#146]
hi
today when i loged in my accout i findout everything is missing from my account and i have msg from monyx that they took btc and coin to adjust ??? i did not get this where is my inveament gone ???????
kindly have  a look .

**Comment by loydz21** [comment]
@monyxcoin mine too

**Comment by loydz21** [comment]
@monyxcoin can u restore our balance please..

**Comment by loydz21** [comment]
My username: loydz21

**Comment by monyxcoin** [comment]
@malyk I'll check it, most likely you was affected by the bug in the system and bought more tokens than you could.

**Comment by monyxcoin** [comment]
@loydz21 yes, you was able to buy more tokens than you had BTC. I restored you your initial MYX balance you got from the first buy order.
