### ISSUE TITLE
missing monyx. ...!!

### ISSUE THREAD

**Issue by parasghelani43** [monyxcoin/monyx-coin#147]
hello sir 
may i request you that i did't receive any BTC amount so kidnly ckeck the transction history .i already talk to u but that's wrong username so 
this my username -parasghelani29
thank you.

**Comment by parasghelani43** [comment]
there is 261.061500 monyx coin missing. .!!!
i repeat this is my username "parasghelani29"
thank you

**Comment by monyxcoin** [comment]
@parasghelani43 I'll check it, most likely you was affected by the bug in the system and bought more tokens than you could.

**Comment by monyxcoin** [comment]
@parasghelani43 should be restored
