### ISSUE TITLE
BTC withdraw doesn't work 

### ISSUE THREAD

**Issue by Alessandro1982** [monyxcoin/monyx-coin#148]
requested withdraw. I confirmed withdraw by email, site gave a success prompt, but withdraw did not execute. In withdraw history is says "Error or the hot wallet is empty and soon will be funded". Please look into it / fix it

**Comment by Alessandro1982** [comment]
Nevermind. I'm an idiot. :)

**Comment by Alessandro1982** [comment]
second time around it seems to have gone through ... will let you know if it's not successfull

**Comment by Alessandro1982** [comment]
nope. Still same error as before. Withdraw does not get processed.

**Comment by Alessandro1982** [comment]
@monyxcoin , can you look into this?

**Comment by iDarkXY** [comment]
I have the same issue

**Comment by chass3768** [comment]
sounds like they disabled it again.

**Comment by animalmode** [comment]
Man this sucks. Just let us withdraw our money! @monyxcoin

**Comment by cryptosomnia** [comment]
Looks like it's happening to all us right now I tried to withdrawal several times and keep getting same error
"Error or the hot wallet is empty and soon will be funded" after few minutes the pending amount disappears.

**Comment by monyxcoin** [comment]
Calm down! Our hot wallet is now funded.

**Comment by monyxcoin** [comment]
Read the error description! "Hot wallet is empty and soon will be funded"

**Comment by cryptosomnia** [comment]
Monyx I was little confused by that that's all. I never used word scam at all.

**Comment by iDarkXY** [comment]
thank u monyx! Yes please read the errors guys

**Comment by debow22** [comment]
Monyx do you plan to find hot wallet? The constant disabling of deposits causes fear that you may exit. This causes price to go down. Just let people get out who want to get ou.

**Comment by debow22** [comment]
Do you plan to fund the hot wallet?
