### ISSUE TITLE
Incorrect deduction

### ISSUE THREAD

**Issue by Homeuser17** [monyxcoin/monyx-coin#149]
I logged back in after your maintence this afternoon. On my dashboard, you claim that i somehow ' got some BTC'??? I do not know how that is even possible, you have incorrectly deducted MYX from my account! I have checked all my transactions, from initial deposits to my buy/sell orders, if anything I have some BTC missing! You should reimburst me NOT deduct more from my account. :/

**Comment by monyxcoin** [comment]
@Homeuser17 sure, i'll check it

**Comment by monyxcoin** [comment]
@Homeuser17 what is you username?

**Comment by mmgva** [comment]
monedas monyx que compre a un precio de 0.38$! con esas mismas monedas hice trading y logre hacer 360 monedas monyx y luego me salio una oferta para llegar a las 1200 monedas y procedí a la compra!!! no entiendo por que me quitaron tantas monedas si yo debería seguir teniendo un aproximado de 1000 monedas exijo verifiquen por que no es justo yo no tengo la culpa del error que hubo en el sistema

**Comment by mmgva** [comment]
Mi nombre de usuario es Mjrg02

**Comment by monyxcoin** [comment]
@mmgva I restored you the initial balance you would have after buying tokens. Other tokens must be deducted since they were purchased with BTC you didn't own.

**Comment by mmgva** [comment]
Entiendo pero yo antes de haber la compra por las 1200 monedas monyx tenia 360 gracias a los trading que hice y considero que me los gane de manera legal y sin perjudicar a la plataforma y en el día de hoy luego que me dijeran con 22 monedas he logrado obtener 10 monedas haciendo trading que suman 32 entonces debería tener al menos 372 monedas en cartera por favor revisen eso por favor gracias!!!!! Usuario Mjrg02

**Comment by mmgva** [comment]
Disculpen por la traducción

**Comment by Homeuser17** [comment]
@monyxcoin

My user name is mkycryptic2

**Comment by Homeuser17** [comment]
@monyxcoin 

Have you fixed it yet?

**Comment by monyxcoin** [comment]
@Homeuser17 you had initial deposit that you spent to buy 859.09724107 tokens, then sell it and then buy 1000.06344433 for all your BTC.
Then you withdrew  550 tokens, so now you should have 450 tokens remaining. If so, your balance should be fixed now.

**Comment by mmgva** [comment]
good afternoon monyx team! Here there must be an error I have never
withdrawn coins nor will I like your platform and I trust that it will be
great! before its keeping I had in my wallet 1256 coins now I only have 400
monedes please I ask for my coins back thanks !!

**Comment by mmgva** [comment]
Good morning I am waiting for you to explain why they ask me to move the
coins from the old wallet to a new one I do not understand that message and
I am still waiting for the replacement of my coins

**Comment by monyxcoin** [comment]
@mmgva because of the bug you got 0.04769731 BTC that you shouldn't get and bought 917 MYX. I already restored you the initial balance, but I won't restore you more MYX since they were gotten because of the bug.
