### ISSUE TITLE
Btc gone

### ISSUE THREAD

**Issue by jaytan17** [monyxcoin/monyx-coin#15]
Hi dev. 

I trade on the site few minutes ago. And now all of my btc are gone. Please fix this 

User name:Tristan17
Email: Bejarin4@gmail.com

**Comment by jaytan17** [comment]
And my btc got negative :-(

**Comment by monyxcoin** [comment]
@jaytan17 don't worry, i'll check what happened and fix it

**Comment by jaytan17** [comment]
Oh thank you so much dev. Please let me know
