### ISSUE TITLE
Error in BTC funds and withdraw does not work

### ISSUE THREAD

**Issue by CoinSamba** [monyxcoin/monyx-coin#150]
Hey guys,
I have been writing to your support and nobody answers me. The problems is that recently I opened my account user CoinSamba with you. I sent approx. 0.35 BTC to it in order to buy Monyx as you can see in the attached picture.
I bought Monyx token in the exchange and then in the same day I sold some. Then I bought a few more Monyx again.
I was expecting to have a final qty of approximately 0.108 BTC in my account and over 6,000 Monyx. Monyx fund is correct. However it shows 0.70 BTC in my account.
I am writing to you because approximately 0.59 BTC does not belong to me and probably belongs to another user that is reporting missing funds. I do believe the system must have a bug or glitch.
1h ago I tried to withdraw my BTC and the system does not allow it saying that I have no funds.
I would like you guys to fix my BTC wallet and allow me to withdraw my BTC.
Cheers!
Coin Samba
<img width="1143" alt="monyx - withdraw btc not working" src="https://user-images.githubusercontent.com/36425910/36125010-e8500f84-1084-11e8-8c6a-406fb20c5830.png">
<img width="408" alt="monyx - my closed orders at the exchange" src="https://user-images.githubusercontent.com/36425910/36125011-e887fc8c-1084-11e8-838b-da39abe628fb.png">
<img width="975" alt="monyx - deposit" src="https://user-images.githubusercontent.com/36425910/36125012-e8bf3a80-1084-11e8-840b-daeae01bee01.png">
<img width="1035" alt="monyx - amount btc 0 6 are not mine" src="https://user-images.githubusercontent.com/36425910/36125013-e90c0a9a-1084-11e8-9b1d-6548334a8068.png">

**Comment by animalmode** [comment]
Yes I get the same problem. What is going on????????? Let us withdraw our money!

**Comment by monyxcoin** [comment]
@CoinSamba i'll check it.

@animalmode read the error description! Our hot wallet was empty, that's what was going on!

**Comment by monyxcoin** [comment]
@CoinSamba thanks for reporting! BTC balance is fixed now.

**Comment by CoinSamba** [comment]
Hey Guys, thank you so much for fixing the issue with my account yesterday. Everything normal and BTC withdraw worked perfectly.
Question: when will you guys launch the Staking platform? At what price?
Cheers!
