### ISSUE TITLE
Btc Withdrawl ERROR

### ISSUE THREAD

**Issue by cryptosomnia** [monyxcoin/monyx-coin#155]
Hey Admin I got this message after I made a withdrawal and verify it by email under Withdrawals History it says "Error or the hot wallet is empty and soon will be funded" What does this mean?
After few minutes the pending withdrawal disappears, but no money received.
Should I make another request?
Please fix it.

Thank you

**Comment by monyxcoin** [comment]
@cryptosomnia our hot wallet is now funded.
