### ISSUE TITLE
Monyx Missing!!!

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#156]
@monyxcoin my myx is missing restore it..please!

username: loydz21

**Comment by monyxcoin** [comment]
@loydz21 i'll check it. Most likely you was affected by the bug in the system and bought more tokens than you had BTC.

**Comment by loydz21** [comment]
@monyxcoin ah ok, can please restore it so that i can begin trading..

**Comment by monyxcoin** [comment]
@loydz21 yes, due the bag in the system you, while trading, got 0.3 BTC more than needed (and withdrew 0.15 BTC that didn't belong to you). Initially you had only 140 MYX and I can't restore MYX to you, because you took the money that didn't belong to you.

**Comment by loydz21** [comment]
@monyxcoin I didn't took the btc..becoz someone took it from my account.

**Comment by loydz21** [comment]
@monyxcoin when the time someone took the btc..my account was hack.

**Comment by loydz21** [comment]
![image](https://user-images.githubusercontent.com/36193728/36131653-c41252ca-10ad-11e8-9559-ecb6bf9e66ea.png)

@monyxcoin look at the date..the withdrawal is in test mode that time..and everyone of us can't withdraw.

**Comment by monyxcoin** [comment]
@loydz21 ok, i remember now!

**Comment by loydz21** [comment]
@monyxcoin Thank you sir.

**Comment by loydz21** [comment]
@monyxcoin Can you please sir?

**Comment by monyxcoin** [comment]
@loydz21 should be restored

**Comment by loydz21** [comment]
Thank you
