### ISSUE TITLE
BTC Stolen..

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#158]
@monyxcoin can u restore the btc I deposited in the image below, that 140 monyx is when it is in ICO stage at $0.60.

![image](https://user-images.githubusercontent.com/36193728/36133182-f7653896-10b6-11e8-9d50-61b7d4e15ef5.png)

**Comment by monyxcoin** [comment]
@loydz21 check

**Comment by loydz21** [comment]
@monyxcoin Sir?
