### ISSUE TITLE
E-mail issue

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#160]
Apologies for leaving this on the github, not sure how else to contact you.

My account username: JCDenton, I used a throw-away email address and am unable to actually verify the withdrawl of BTC i am trying to make, will you assist me here?

The registered email begins with t971005

thank you team monyx

**Comment by monyxcoin** [comment]
@t971005 sure, to what email do you want to change it?

**Comment by monyxcoin** [comment]
@t971005 or should i just confirm your withdrawal?

**Comment by t971005** [comment]
Just confirm withdrawal would be sufficient. I appreciate the assistance.

**Comment by t971005** [comment]
Please confirm the recent withdrawls. Thank you
