### ISSUE TITLE
Missing Deposit tx-id inside

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#161]
Hi I sent over some BTC and it still hasn't shown. I know you are busy do you mind looking into it for me
e56884ff9a0aada1efd711abcb83d754fe293c269830f7f32a1872c71216b1ac

Username is 2themoonandback

Thanks :)

**Comment by monyxcoin** [comment]
@2themoonandback it's already in the system, soon will be confirmed.

**Comment by 2themoonandback** [comment]
Thank you
