### ISSUE TITLE
Put back sell limits

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#163]
Is it possible to request you put back sell limits. People are forming big walls just to drop the price intentionally. I understand that strategy but how is this good for the platform overall or if you can explain to me how this won't be a issue later on would be great.

Just alot of manipulation but I don't know if you find that to be a issue or not.

I myself am buying the dips but overall again isn't having a minimum sell limit better than a consistent pump and dump?

**Comment by chass3768** [comment]
NO...Once all these weak hands get out of the way the price will go up. Get yourself all the coins you can while this is happening. Sell limits will kill a platform!

**Comment by monyxcoin** [comment]
@2themoonandback yeah, we can't really force sell limits right now. The team still creates a new whitepaper and plan, and for now there are not much going on, so the price is and will be low for some time, but they decided to stop controlling the market.
