### ISSUE TITLE
my monyx gone

### ISSUE THREAD

**Issue by kimboya** [monyxcoin/monyx-coin#165]
Dear Monyx support

i login into my monyx account and got shocked while all my balance is gone

in exchange history listed any of closed order that sold all my 365 monyx while i never put sell order in exchange

and in btc withdrawal history listed that btc result from selling 365 monyx has been withdraw at  2018-02-06 19:22:44  amount -0.02606436 BTC  while i never do that.. it shown https://chain.so/tx/BTC/514f30419ac8d0985b1c069f49e1b192b34b330dfaee6a4e5cc50bb60646f872 and withrawed to address  1BVpM2Vt7MkQzDsQB1TNJZX6wVChjtTEMz while i dont know whose address is

please help me get my back 365 monyx back.. i never sell my monyx and never withdraw btc from that selling

my account : 
Username: kimboya
Email: 4jj1.hakim@gmail.com
Country: Indonesia
Registration date: 2017-12-23 23:51:06
![monyx 1](https://user-images.githubusercontent.com/36436322/36137049-f618cce6-10c5-11e8-9689-4990bcc9c1c5.jpg)
![monyx 2](https://user-images.githubusercontent.com/36436322/36137052-f8e4493c-10c5-11e8-9ffb-48081bd1b2c3.jpg)
![monyx 3](https://user-images.githubusercontent.com/36436322/36137053-fb4411c6-10c5-11e8-9ca9-332281427c96.jpg)

**Comment by monyxcoin** [comment]
@kimboya should be restored

**Comment by kimboya** [comment]
THX A LOT!! U GIFTHUB GUYS ROCK!!!
