### ISSUE TITLE
BTC not received 

### ISSUE THREAD

**Issue by nitishcse412** [monyxcoin/monyx-coin#166]
Hi Team,
I transferred 0.00578160 BTC but i never received in Monyx. 

Wallet BTC address - 39HZMuP7tzkjo69qUZzHb2SWKv8eyMbkH3
user name : nitishcse412

**Comment by Adebola100** [comment]
I also am missing a btc transfer 0.01618656 
trans ID b3c6029b92c1780fb7910409e9819aa5174da7b5c741ee011616d0bee759d808
wallet 17gSmwmk5aqe7DqUxRgNEkQqMaBvmpTzkV
user name adebola

**Comment by monyxcoin** [comment]
@nitishcse412 @Adebola100 old user addresses don't have webooks enabled already, so all transactions for those addresses are collected twice a day.
Yours will be deposited soon.

**Comment by nitishcse412** [comment]
Very thankful to you.

Thanks
Nitish
