### ISSUE TITLE
Offering volunteer free part time help to Monyx team

### ISSUE THREAD

**Issue by chakramchirkut** [monyxcoin/monyx-coin#169]
Hi Team,

I understand you guys are under the pump and helping out the members which is very good in this climate.

I am willing to help you guys part time for free in coding , documentation or support...let me know..

cheers.
@monyxcoin

**Comment by monyxcoin** [comment]
@chakramchirkut thanks, we'll consider your offer!

How can I contact you?

**Comment by chakramchirkut** [comment]
@monyxcoin please pm me on yahoo, same id name as github.
