### ISSUE TITLE
Minting balance

### ISSUE THREAD

**Issue by Adebola100** [monyxcoin/monyx-coin#171]
Good morning, 

I noticed that after my coin got mint that i am missing a 100 MXY on my minting transaction log. the balance in the minting transaction log doesn't reflect my available balance 

Thank You

**Comment by Xatra47** [comment]
Hello,
I got the same issue. Restart your wallet, it should then be fine. I sent a ticket few minutes ago to get an answer from support as I assume we should not have to restart the wallet every day after having received our rewards.
Bye.

**Comment by Adebola100** [comment]
thank you worked like you said..
