### ISSUE TITLE
MISSING DEPOSIT URGENT ATTENTION PLEASE!!!

### ISSUE THREAD

**Issue by myfunnelpays** [monyxcoin/monyx-coin#173]
hello admin,
I just deposited funds to my btc wallet upon 8 confirmations yet its not showing up in my monyx btc wallet why????
here is the transaction id: https://blockchain.info/tx/9bd1c8d81d9357bb899605ad9d4c194ca6486d7d82a4a071ac731c068b6a96a0
my monyx username is myfunnelpays.
Pls hasten to complete my deposit.
Thank you.

**Comment by myfunnelpays** [comment]
made another btc p
deposit yet not showing upon 16 confirmations...
pls rectify this issues asap

**Comment by myfunnelpays** [comment]
made another btc
deposit yet not showing upon 16 confirmations...
pls rectify this issues asap
the transaction details:
https://blockchain.info/tx/550adc26adc568f114b81e7e703006a7bb14f921cec2e129ba9bccdd8c71acd3

**Comment by monyxcoin** [comment]
@myfunnelpays old user addresses don't have webooks enabled already, so all transactions for those addresses are collected twice a day.
Yours will be deposited soon.
