### ISSUE TITLE
missing btc and coin ,urgent issue

### ISSUE THREAD

**Issue by adityapatell** [monyxcoin/monyx-coin#174]
my btc was deducted saying i got affected by bug, but i did not do anything, as well as coin got deducted

i was doing trading, buying and selling coin,
you can see my exchannge history as a proof.

at least you can do is give my coins and btc backk...
i am 100% sure i didn't do anything wrong..
waiting for our early reply...

**Comment by monyxcoin** [comment]
@adityapatell i'll check. What is your username?

**Comment by adityapatell** [comment]
Username: Adityamonyx

**Comment by adityapatell** [comment]
Username: Adityamonyx

**Comment by adityapatell** [comment]
any updates ?@monyxcoin

**Comment by 2themoonandback** [comment]
NO

------ Original Message ------

**Comment by monyxcoin** [comment]
@adityapatell i'll check that today.

**Comment by monyxcoin** [comment]
@adityapatell should be fixed.
