### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by Xatra47** [monyxcoin/monyx-coin#175]
Hello,

After letting my wallet unlocked and my computer always turned on, I got 1 something MYX with 1032 MYX staking.
Also when I got my rewards (2 received only on 4 days), the transaction which minted disappears from my minting transactions and nothing is updated automatically (all confirmed on the blockchain); I must exit and restart my wallet to make things refreshed. I run the wallet as an admin for info. However it was refreshed automatically for my first reward. Is there a bug somewhere? Am I doing things properly? I should receive a reward every 24 hours, once the transaction which is minting becomes mature, right?

![image](https://user-images.githubusercontent.com/36276350/36153214-cfa4dbe2-10cd-11e8-8f20-152ae1ef6985.png)

![image](https://user-images.githubusercontent.com/36276350/36153097-75daa2d6-10cd-11e8-9a8e-ab71f68529d5.png)

![image](https://user-images.githubusercontent.com/36276350/36153131-91b750d0-10cd-11e8-90c5-1d527e396316.png)

Thanks for your help.

**Comment by FrankFromFrance** [comment]
No, reward every 24 hours is not certain. You will get reward faster if you stake more coins.

However, in the end, you will receive approximately 10% per month. Keep wallet open 24/7 for that.

**Comment by Xatra47** [comment]
Thank you. Is that normal I had to close and start again the wallet to get everything refreshed?

**Comment by FrankFromFrance** [comment]
@Xatra47 I'm pretty sure it is a bug, monyx team will confirm soon.

**Comment by monyxcoin** [comment]
@Xatra47 I'll try to reproduce the bug, thanks for reporting.

Regarding staking - yes, your reward scales with the coin age and you are randomly selected from all other possible candidates for a reward. However your tx if not selected will continue getting older and therefore more profitable.

**Comment by chakramchirkut** [comment]
May be also try repairwallet from debug console, see if it helps. Are you sure you downloaded the latest version of the wallet?

**Comment by Xatra47** [comment]
File version: 3.0.0.1
I am neither a debugger nor a developer so I forget the debug console solution.
Thank you anyway!

**Comment by chakramchirkut** [comment]
Ok so you will receive the reward after the green phase ran for 24 hours, so total 48 hours after the start of minting.
I have noticed as well that orphan transactions are lingering on the minting screen and it requires restarting the QT software to clean up.

**Comment by chakramchirkut** [comment]
And yes, repairwallet from console did not fix that, i also had to restart the wallet to refresh the queue.

**Comment by monyxcoin** [comment]
I'll work on the wallet to fix this bug as soon as possible.
