### ISSUE TITLE
Ditto: Incorrect deduction

### ISSUE THREAD

**Issue by dustynw43** [monyxcoin/monyx-coin#177]
Please review my account.

The BTC amount you calculated as being 'erroneously deposited' was too much. If you look at my deposit BTC logs you will see how much BTC I have deposited of my own money. 

Please fill my BTC wallet with this amount and remove all MYX coins from my wallet.

If done promptly, I can then decide whether to reinvest in MYX with my BTC or no. 

Thankyou for your timely response to recover my wrongly deducted BTC amount, 

Dusty NW

acct = dusty.n.wauer@outlook.com

*****

Monyx Dashboard

 Important Notice:
You are one of the users whose balance was affected by the bug in the system **_---- TRUE_**

and therefore got 0.08438859 BTC. ---- _**FALSE**_

To correct your balance we deducted: 0.00000002 BTC and 2,109.71425000 MYX (equivalently to missing BTC amount based on MYX price = 0.00004 BTC). **_---- EXCESSIVE and UNJUSTIFIED_**

Our hot wallet is funded, BTC withdrawals now will go through.

All missing BTC deposits are collected every hour.

All affected by the bug in the system balances were ## **corrected to their initial values.** 

!! If nothing else, **PLEASE DO THIS** with my account; i.e. correct it to it's initial BTC value. Easily determined by viewing my deposit log linked to this account. 

![monyx dashboard](https://user-images.githubusercontent.com/36449566/36160027-323f18aa-10ae-11e8-8d63-02cdd989dac5.jpeg)

**Comment by monyxcoin** [comment]
@dustynw43 ok, I'll check.

**Comment by monyxcoin** [comment]
@dustynw43 the correct amount of MYX that you bought with your original deposits is restored.

**Comment by dustynw43** [comment]
Thanks!

Kuddos for promptness.

Dusty
________________________________
