### ISSUE TITLE
BTC Deposit

### ISSUE THREAD

**Issue by Adebola100** [monyxcoin/monyx-coin#178]
I also am missing a btc transfer 0.01618656
trans ID b3c6029b92c1780fb7910409e9819aa5174da7b5c741ee011616d0bee759d808
wallet 17gSmwmk5aqe7DqUxRgNEkQqMaBvmpTzkV
user name adebola

**Comment by monyxcoin** [comment]
@Adebola100 processing, will be deposited soon.
