### ISSUE TITLE
Rayyan99

### ISSUE THREAD

**Issue by rayyan99** [monyxcoin/monyx-coin#179]
Sir I am loss Google authenticator basalamahrayyan13@gmail.com

**Comment by rayyan99** [comment]
Sir I am loss Google authenticator basalamahrayyan13@gmail.com username rayyan99

**Comment by chakramchirkut** [comment]
Unfortunately, if you have lost google authenticator code then it will be difficult.
@monyxcoin  Could you please may be reset the access to this user account
?

**Comment by rayyan99** [comment]
Please disable sir

**Comment by rayyan99** [comment]
@monyxcoin please disable

**Comment by 2themoonandback** [comment]
NO

------ Original Message ------

**Comment by rayyan99** [comment]
Why

**Comment by 2themoonandback** [comment]
because if you lost  your OWN authenticator it would be a security risk 
for me to disable. Next time keep better care of it.

------ Original Message ------

**Comment by rayyan99** [comment]
I did not ask you

**Comment by 2themoonandback** [comment]
Well I'm telling you .

------ Original Message ------

**Comment by rayyan99** [comment]
I asked the monyx not you
