### ISSUE TITLE
Bitcoin pending

### ISSUE THREAD

**Issue by bitcoinprofitcycle** [monyxcoin/monyx-coin#185]
Hi 
I have deposited bitcoin and no show on my dashboard balance yet 20 confirmations showing in the blockchain. 

I also don't have any pending transaction showing in my dashboard yet the blockchain confirms the correct deposit address

![28034638_1733872006676359_1805933231_o](https://user-images.githubusercontent.com/36465281/36189522-e3cc4354-11b7-11e8-9b5a-d90d1ed90a89.png)

![2018-02-14_1849](https://user-images.githubusercontent.com/36465281/36189529-e8703032-11b7-11e8-9714-75da450a4c4a.png)

It also says in the Blockchain the btc has been spent.

![28125874_1733877623342464_1386337755_o](https://user-images.githubusercontent.com/36465281/36187658-aefc222c-11ab-11e8-9951-0f306458fa36.png)

Thanks

**Comment by bitcoinprofitcycle** [comment]
It also says in the Blockchain the btc has been spent.

**Comment by monyxcoin** [comment]
@bitcoinprofitcycle the BTC we get on user addresses immediately sent to the main wallet, so it's ok when it shows the amount is spent.

It should be confirmed now.
