### ISSUE TITLE
Bitcoin Deposit Missing

### ISSUE THREAD

**Issue by atcslot** [monyxcoin/monyx-coin#186]
My deposit has been pending for 24 hours despite being confirmed with 100+ confirmation
Username: LoveTWin
Transaction ID: 9c06a9d2c73a866a950e7e6dea3cac3016d92d04d5258494defa6ff893d0e7a0
![5aa67c05-d088-449c-8a38-a535798bcb1b](https://user-images.githubusercontent.com/36466722/36188669-20173b12-1180-11e8-91da-60ceb8768ca5.png)
![a758d9c2-ec66-4984-9459-ac69b194fa0b](https://user-images.githubusercontent.com/36466722/36188670-204e8496-1180-11e8-82c3-7e195a12aed7.png)

**Comment by monyxcoin** [comment]
@atcslot will be processed in few minutes.
