### ISSUE TITLE
Bitcoin withdrawals stuck in processing

### ISSUE THREAD

**Issue by EmotionlessTrading** [monyxcoin/monyx-coin#187]
Username is emotionlesstrading all of my withdrawals are still in processing . It's been hours can you process them and put them through.

Thank you

**Comment by monyxcoin** [comment]
@EmotionlessTrading what's your username? Are they still processing?

**Comment by EmotionlessTrading** [comment]
EmotionlessTrading is my username .

All withdrawals are still processing.

**Comment by monyxcoin** [comment]
@EmotionlessTrading ok, they will be cleared in few minutes and you will be able to initiate a withdrawal again.

**Comment by EmotionlessTrading** [comment]
Sorry to reopen I still have all my withdrawals in processing. All of them I did in pieces for my large but don't see it reflected back in my account . Is there something else you need?
