### ISSUE TITLE
Bitcoin Deposit issue

### ISSUE THREAD

**Issue by pk5720** [monyxcoin/monyx-coin#188]
Dear sir,
I deposited btc and had 31 confirmations but
![screenshot_20180214-165544](https://user-images.githubusercontent.com/20137679/36201983-f8575be8-11a7-11e8-93f6-c06edab88fad.png)
 still not credited in my monyx account. Here is the transaction id for reference ”bdb4e91d92e57212123e5760a5e71e4fd2c4fef7c195ca2895f76f859c2e137e”
My user id is pk5720

Regards,
Prashant

**Comment by monyxcoin** [comment]
@pk5720 old user addresses don't have webooks enabled already, so all transactions for those addresses are collected twice a day.
Yours will be deposited soon.
