### ISSUE TITLE
2FA authentication issue

### ISSUE THREAD

**Issue by rayyan99** [monyxcoin/monyx-coin#189]
Hello,

My email is basalamahrayyan13@gmail.com and username is rayyan99. I have an issue with 2FA and unfortunately, I also seem to have missed the secret key. Please help me reset 2FA. appreciate your help.

Thank you,
rayyan99

**Comment by 2themoonandback** [comment]
MONYX JUST CLOSED THIS TICKET SO THE ANSWER IS NO.... GET THE POINT AND STOP OPENING NEW TICKETS AND WASTING THEIR TIME.

**Comment by monyxcoin** [comment]
@rayyan99 can you confirm you own the email by sending something to egor.prokop.kop@gmail.com ?

But of course we should stop disabling 2FA as it's the only secure way to prevent someone to access an account.

**Comment by rayyan99** [comment]
Ok

**Comment by rayyan99** [comment]
basalamahrayyan13@gmail.com sir

**Comment by rayyan99** [comment]
Confirm to basalamah rayyan 13@gmail.com

**Comment by rayyan99** [comment]
basalamahrayyan13@gmail.com

**Comment by monyxcoin** [comment]
@rayyan99 i mean, send something from this email to the email I wrote above, then I'll be more or less sure that's you.

**Comment by rayyan99** [comment]
My account is basalamahrayyan13@gmail.com sir

**Comment by rayyan99** [comment]
Please disable

**Comment by rayyan99** [comment]
Sir how

**Comment by xStarBlade** [comment]
Email him. This is his email: egor.prokop.kop@gmail.com

**Comment by rayyan99** [comment]
Hello,

My email is basalamahrayyan13@gmail.com and username is rayyan99. I have an issue with 2FA and unfortunately, I also seem to have missed the secret key. Please help me reset 2FA. appreciate your help.

Thank you,
rayyan99

**Comment by loydz21** [comment]
Hahaha

**Comment by monyxcoin** [comment]
@rayyan99 disabled.
