### ISSUE TITLE
IMPORTANT: deposit issue

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#19]
kindly pls look into this transaction. still not getting my deposit:

Tx ID: 9731c804ab4981bcb9338ea5a116e663dbb10aff65c560870f6e8e91cd5677fc

**Comment by alexpride007** [comment]
https://blockchain.info/tx/9731c804ab4981bcb9338ea5a116e663dbb10aff65c560870f6e8e91cd5677fc

**Comment by monyxcoin** [comment]
@alexpride007 we're already investigating this issue, missing deposits will be added soon.

**Comment by monyxcoin** [comment]
@alexpride007 resolved
