### ISSUE TITLE
Exchange is dying a slow painful death!

### ISSUE THREAD

**Issue by chass3768** [monyxcoin/monyx-coin#194]
Monyx,

If you dont do something to advertise and get people trading, with a good investment opportunity soon, the coin will be worth pennys. The price is continually moving lower each day and trading volume is slowing drastically!

Please give us some news on the plan or a time frame for a decent investment opportunity with this platform!

**Comment by monyxcoin** [comment]
@chass3768 yes, I understand the frustration. I myself wait for some new information from the team! So let's just wait more, I'm pretty sure it's in their own interest to at least increase the price of the coin.

**Comment by chass3768** [comment]
@Monyx We need an update and a solid time frame from you on the new Road Map and White paper TODAY!

**Comment by monyxcoin** [comment]
@chass3768 I totally agree, though it depends not on me, but on the team. I can't promise it today, but it's in our interest to do some actions ASAP.
