### ISSUE TITLE
E- mail Issue

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#195]
**Reopened

Apologies for leaving this on the github, not sure how else to contact you.

My account username: JCDenton, I used a throw-away email address and am unable to actually verify the withdrawl of BTC i am trying to make, will you assist me here?

The registered email begins with t971005

thank you team monyx

action: Confirm Withdrawl

**Comment by t971005** [comment]
Alternatively change the email to t971005mvrhtnet@outlook.com 

thank you

**Comment by monyxcoin** [comment]
@t971005 changed!
