### ISSUE TITLE
2fa code per mail

### ISSUE THREAD

**Issue by KMD89** [monyxcoin/monyx-coin#196]
He guys,

just a tip here:

When u activate 2fa on Tokenpay, they send the "reset code'' to your email. People sending a lot of message here on Github because they cant acces their account duo to the 2fa code and they didn't write down the reset code on a paper.

It would be easier if Monyx send the ''reset code'' to your email when activating 2fa.

**Comment by monyxcoin** [comment]
@KMD89 great idea, thanks!
