### ISSUE TITLE
Improvement for sell order cancel button 

### ISSUE THREAD

**Issue by marcelvan** [monyxcoin/monyx-coin#197]
Hey there 
 just suggestion when trying to cancel a sell order on mobile.  We are unable to click the cancel button as the bid an ask list is over lapping the button 

Keep up the good work looking forward to the update news 
Cheers

**Comment by monyxcoin** [comment]
@marcelvan check it now please, is it better?

**Comment by marcelvan** [comment]
Thanks alot team nicely done

**Comment by marcelvan** [comment]
Huge thanks to the team this means alot looking forward to the next update
Kind regards
Marcel

On 15 Feb 2018 18:48, "monyx.io" <notifications@github.com> wrote:

@marcelvan <https://github.com/marcelvan> check it now please, is it better?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/monyxcoin/monyx-coin/issues/197#issuecomment-365831872>,
or mute the thread

**Comment by marcelvan** [comment]
Hey team

Could I also suggest upgrading the trading chart I'm guessing it's already
in development but would be nice to see

Kind regards
