### ISSUE TITLE
error after chosing the data directory

### ISSUE THREAD

**Issue by pviljaka** [monyxcoin/monyx-coin#2]
![screen shot 2018-01-28 at 0 39 58](https://user-images.githubusercontent.com/35880016/35477102-fc7885da-03c4-11e8-80e1-019379f48d9b.png)
Using OS X, El Capitan

**Comment by pviljaka** [comment]
Using OS X, El Capitan

**Comment by AlexCosta405** [comment]
The same issue here. Downloaded wallet v2.0.0.2, using El Capitan, 10.11.6

![mx-walet](https://user-images.githubusercontent.com/35890978/35481669-1ac379ec-0428-11e8-99a8-d03c1f5a8561.png)

**Comment by monyxcoin** [comment]
Thanks, we'll check it.

**Comment by monyxcoin** [comment]
@pviljaka @AlexCosta405 would be great if you post your `~/Library/Application Support/Monyx/debug.log` file content.

**Comment by AlexCosta405** [comment]
No problem, here is my .log  https://pastebin.com/UfSakThk

**Comment by pviljaka** [comment]
Here's my debug.log
[debug.log](https://github.com/monyxcoin/monyx-coin/files/1671470/debug.log)

**Comment by monyxcoin** [comment]
@AlexCosta405 that's the first time you run the wallet, right? You didn't have the wallet file before, right?

**Comment by Bonboni** [comment]
I have the same issu, and never run it before

**Comment by AlexCosta405** [comment]
@monyxcoin downloaded just today. After first run got an error, so uninstalled it and reinstalled again. Thought that it is problem in my system. So reinstalled and got the same error. Run wallet multiple times got the same error again, than I reported here. That's why you can see multiple entries in the log compared to @pviljaka

**Comment by pviljaka** [comment]
Are you all who has this error running older version of Mac OS? Not SIerra or High Sierra? I bet the error is because the "QT" libraries are not new enough. 

There would be a need for a different version compiled to work for El Capitan. Me myself, cannot currently upgrade to Sierra/High SIerra because gfx driver issues (i'm running hackingtosh). 
Hoping to see a working Monyx-QT version for El Capitan.

**Comment by monyxcoin** [comment]
Thanks @pviljaka, I guess that's the issue! I'll recompile the wallet for older versions as soon as I can.

**Comment by Bonboni** [comment]
Great :)
We are on standby

**Comment by new2018man** [comment]
@monyxcoin please fast completed work after 15 days you are say soon soon

**Comment by monyxcoin** [comment]
@pviljaka please check the wallet in the latest release, it should work properly on systems 10.7+ now.

**Comment by AlexCosta405** [comment]
@monyxcoin Hi team, this is fresh wallet install on the system. Old wallet has been uninstalled with AppCleaner. 

This is an error what I'm getting on my system. Ignore/Reopen doesn't open an app. 
![screen shot 2018-02-01 at 21 56 20](https://user-images.githubusercontent.com/35890978/35700643-d1faca2a-0793-11e8-8d8e-046e8d6c11fd.png)

Here is log file https://pastebin.com/kWu9aQHA

As far as I can tell, I will use wallet on Windows machine. Mac is my machine what I'm using at work and wanted to help the team to keep blockchain running smoothly from the beginning.  If wallet works on Sierra and High Sierra, than don't waste your resources on ElCapitan support. I know that you have more important things to take care of! 

Just wanted to share how I stand but I'm more than happy to help and do more testing if needed!

**Comment by Bonboni** [comment]
I´m with AlexCosta405 on this, but thanks for putting time and try to help us

**Comment by monyxcoin** [comment]
Thanks for the useful information and not putting pressure on me!
Anyway I'll be able to get my hands on El Capitan on this week/next week, so I'll thoroughly test the wallet on this system.

**Comment by monyxcoin** [comment]
Windows wallet is released, I'll try to compile the wallet for earlier macOS soon.
