### ISSUE TITLE
28 hours Transaction BLOCK! 

### ISSUE THREAD

**Issue by KemalCYP** [monyxcoin/monyx-coin#20]
Hi Guys
It's been 28hours and my transactions are not reflected.. now buying is in freeze. We simply lose together
https://live.blockcypher.com/btc/tx/b25721b35277aa4951b861ed82dea518fd2e7001f766dde34d80dddea9312633/

https://live.blockcypher.com/btc/tx/61abd3f3a54bf80783d10d24533d770c954152408d38ced925723264081921b1/

**Comment by monyxcoin** [comment]
@KemalCYP resolved, there was a problem with the 3rd party service we use to process btc txs
