### ISSUE TITLE
Fill the Hot wallet before it’s empty 

### ISSUE THREAD

**Issue by TonyMcclure** [monyxcoin/monyx-coin#200]
If u guys want people to trust this platform & bring in more BTC. People have to know that they can take out their BTC at any time. I’ve tried to take out 0.02029825 BTC at 3 diffent times of the day today. & get the same message after a minute of processing. “Error or the hot wallet is empty & will be founded shortly”. Being able to withdraw at any time, is one of the most important things to build trust & a happy community. & we can let others know that it is safe. Cause  people are very weary about lending & stacking platforms right now.

**Comment by monyxcoin** [comment]
@TonyMcclure that's right, we have some deficit because of the bug happened on 7th Febuary and it takes some time for the team to get BTC from the cold wallet to cover the stolen funds.

**Comment by chakramchirkut** [comment]
@monyxcoin  any estimate on how much was taken due to the bug ?

**Comment by monyxcoin** [comment]
@chakramchirkut yes, around 20BTC. We were able to restore some part of that in MYX coins, but we still need to sell them to cover the missing amount, that's why it's also in our interest to make the price higher, still trying to get any information from the team.

**Comment by chakramchirkut** [comment]
@monyxcoin Thank you for the information. appreciate it.

**Comment by debow22** [comment]
This coin is shit scam. You will NEVER see a dollar from these guys. Just one excuse after another. I can’t even Withdraw a measly 200.00. Nickel and dime scammers

**Comment by chakramchirkut** [comment]
@debow22  so just bcz you cant withdraw its scam ? did you even see any real back office and github community for other lending platforms ?
Plus they have already said that they had issues and bugs for which they needed to to do audit and halt the withdrawals etc.. its work in progress but its still better than running away, if they want they could just not care about all of these and run away..but they are still here so have faith.. no one knows future..

**Comment by TonyMcclure** [comment]
It's cool, people r just made that they can't pull their BTC out. So he kinda has the right to be mad. People only trust a platform if they can pull their crypto out. But we do need to be calm & give them a few more days. But I wouldn't refer anyone till they get the wallet filled & r able to keep it filled. Need to be able to withdraw at anytime

**Comment by monyxcoin** [comment]
@debow22 @TonyMcclure  We don't do that people can't pull their BTC, it's in our interest to keep the platform running.

I just filled the wallet, so you can withdraw your BTC and stop using out platform at all.
