### ISSUE TITLE
Wallet Staking

### ISSUE THREAD

**Issue by NeekCrypto** [monyxcoin/monyx-coin#202]
Hi Dev,

Can you please advise on how we're supposed to receive the 10% staking bonus? From my understanding, if I'm staking 3000 coins in my wallet, at the 10% monthly rate; I should be receiving 10 MYX coins daily correct? Unfortunately, I'm receiving nowhere near that amount. More like 1-2 coins daily?

A wallet tutorial guide would be great for new users as well. Thanks!

**Comment by Blitzkitten** [comment]
it's about 1% per month by wallet predicition.
