### ISSUE TITLE
REQUEST EVERYONE TO FIRST REVIEW EXISTING SIMILAR ISSUE AND REASON BEHIND BEFORE CREATING NEW TICKETS

### ISSUE THREAD

**Issue by chakramchirkut** [monyxcoin/monyx-coin#203]
Just to reduce the load of same issues being reported over and over..lot of the answers are there in existing issues and chats.

**Comment by IamTheM8** [comment]
True m8, same issues already resolved over and over again. They should say that on the "News" section

**Comment by monyxcoin** [comment]
@chakramchirkut thanks.

I'll update the info on the site and soon will release a FAQ section.
