### ISSUE TITLE
Will whitepaper be released this weekend?

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#204]
Hi you said whitepaper is coming soon will it be this weekend. ? Just as a investor I did purchase this coin due to some of the points made in the old whitepaper so pretty anxious to see what it is now . 

Would be great if you could actually get a date . I think as investors especially one who invested due to the whitepaper its not asking for alot.

Thanks

**Comment by IamTheM8** [comment]
Hello,

Please update the whitepaper let everyone knows you are for the long run and the best one out there.

Go monyx GOOOO

**Comment by chass3768** [comment]
Yes please, we all want to know what the new road map and plan looks like!! As soon as possible!

**Comment by monyxcoin** [comment]
@2themoonandback as I said in another issue https://github.com/monyxcoin/monyx-coin/issues/208 the team experiencing some delays, so unfortunately it seems we still need to wait some time (can't say the exact date, but it's in their interest to start making price higher as soon as possible).
