### ISSUE TITLE
Wallet Not Syncing 

### ISSUE THREAD

**Issue by aalex2435** [monyxcoin/monyx-coin#205]
![20180215_134602](https://user-images.githubusercontent.com/35179186/36262615-e834f1a4-125f-11e8-848f-80a812b0a514.jpg)
![20180215_135629](https://user-images.githubusercontent.com/35179186/36262616-e84eabd0-125f-11e8-8487-108810ce2c71.jpg)

Wallet sync is stuck, what can I do?

**Comment by monyxcoin** [comment]
@aalex2435 try to delete everything in the Monyx folder `C:\Users\YourUserName\Appdata\Roaming\Monyx` **EXCEPT** `wallet.dat` file and run the app again.
