### ISSUE TITLE
News section help out

### ISSUE THREAD

**Issue by IamTheM8** [monyxcoin/monyx-coin#207]
I am willing to help out with the "NEWS" and spread the word of any announcements, update of any kind.

I will do it for FREE.
I just want for me and all the community to be aware of the coming updates. 

Contact me: btcoinmail@gmail.com
telegram: @lamTheM8 (https://t.me/lamTheM8)

Best. Go Monyx GOOOO

The Dude

**Comment by loydz21** [comment]
The trading platform on mobile is now fix..thank u @monyxcoin

**Comment by monyxcoin** [comment]
@IamTheM8 I'll let you know once we start getting new information, thanks.
