### ISSUE TITLE
2FA Issue

### ISSUE THREAD

**Issue by sungahidv** [monyxcoin/monyx-coin#209]
Hi, can you help me with my 2FA issue? Google Authenticator was re-installed to my phone but unfortunately, I lost my security code. It's been a month now that I was not able to access my account? I have already sent several emails to your support team but no one bothers to respond. Please help me as I still have trust with Monyx. I can provide you more details to verify that I am the true owner of the account. Thanks.

**Comment by monyxcoin** [comment]
@sungahidv what's your username?

**Comment by beerkumm** [comment]
@monyxcoin Hello. You can help me
I lost my phone and my 2FA code is gone. I want to remove 2fa code.
please remove 2fa code my account.
Username - beerkumm
E-mail - kummbeer@gmail.com
Create monyx account - 24/12/2017

**Comment by sungahidv** [comment]
Username - sungahidv

**Comment by sungahidv** [comment]
@monyxcoin Username - sungahidv

**Comment by monyxcoin** [comment]
@sungahidv @beerkumm disabled.

**Comment by beerkumm** [comment]
@monyxcoin Thank you sir.

**Comment by sungahidv** [comment]
@monyxcoin Thank you!
