### ISSUE TITLE
My deposit is not there my BTC address also just changed 

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#21]
My BTC address was 3KJz2wwHVjTPcTFSTsWrY6muqPBMqtfS7V  I sent money to this address before you guys froze the exchange 

than just now it switched to 3LpHJJRC3WEv3GXS9JtqbDLtb7Pxj2UfED 

My money didn't come through and now I have a different address.

Please address and let me know what I should do. 

Don't know why I have a different address now and where my money is now.

**Comment by 2themoonandback** [comment]
3KJz2wwHVjTPcTFSTsWrY6muqPBMqtfS7V 
71254a748983a585cede902e71d4940c10595d0f8e4ca175e41b3559a8ce3a0b

That is my deposit address which was changed when you fixed deposits and also the transaction Id of the money I sent over a hour and half ago. It already is confirmed. Please credit my account. 

My new wallet which was changed is 3LpHJJRC3WEv3GXS9JtqbDLtb7Pxj2UfED

**Comment by monyxcoin** [comment]
@2themoonandback should be resolved

**Comment by 2themoonandback** [comment]
Thank you very much.
