### ISSUE TITLE
BTC still pending after 29 hours

### ISSUE THREAD

**Issue by simonrob77** [monyxcoin/monyx-coin#213]
I've deposited BTC to my account, and it's been confirmed 159 times on the blockchain, but is still pending in my wallet. Please can you look into it? My username is simonrob77 and transaction ID is f21bd85e50557c6948ff441e0c8bf07ed32be12ea43b1e431c0662cfaa64272e.
Thanks

**Comment by Blitzkitten** [comment]
I've had a similar problem (shorter time frame).

Deposit has not shown up in my account (not even pending) has only had 20 confirms: 
username: Blitzkitten 
Tx ID: 17f28924df27ce0d1a1afeca45a9a4e840e842d1944ed33443749bdfd65fb385

Thanks
