### ISSUE TITLE
+++Staking reward issue+++ 1 week, 1,032 MYX staked, 2 MYX received... Possible explanations HERE

### ISSUE THREAD

**Issue by Xatra47** [monyxcoin/monyx-coin#216]
Dear Team,

I want to share with you my impression regarding my first staking week **with 1,032 MYX: I got 2 MYX** approx as rewards...
My computer is turned on nights and days, wallet software runs as administrator and I allowed the software in the W10 firewall tab for private and public network in order to avoid any connecting issue. Everything is synchronized in the wallet, no error message also.

I only see with the minting probability within Minting tab **a reward around 0.988% on 30 days!**

The 2 following things are a problem from my point of view:
-Refresh of Minting tab not automated:
Mint icon (next to network and lock ones on bottom right) does not reflect the correct number of active minting transactions. This may delay or does not take into consideration all the transactions minting, therefore no/delayed rewards for the missing one. I must restart the wallet after each reward...;

-Every reward makes the transaction splitted:
Your white paper said minimum staking time is 24h, but I do not think the rewarded transaction has to be splitted because after each reward (minimum 24h - depending of the transaction size I assume), the split makes the 1 old mature transaction into 2 new transactions. The latters will need 24h to mature.
**MYX stakers lose 1 staking day after each reward**, rewards reduce transactions size which decrease the minting probability and at the end get a rate like mine: around 1% instead of 10% a month!

Did you set up the maximum staking time at 24h/after each reward?

Why is a split necessary here except not to reward stakers every day after a transaction is mature but only every 2 days minimum (1 day to mature, 1 day to stake and few more time to get the reward, then split, again 1 day to mature, etc.)?
For my knowledge, as it is for many platforms and desktop wallets, once a transaction is mature, it keeps staking every day and gets recurrent rewards. **There are no splits and lost time for being mature again.**

Thank you for your honesty, clear answers for the Community and prompt software update if any (as, for me, that is not how it should work).

Regards,

Xatra47

**Comment by Blitzkitten** [comment]
@Xatra47 

From what I've experienced with the wallet it is a little hit and miss on updating the Minting page. I've only had minimal disturbances on the refreshing aspect but I know some have had more significant problems.
The best way to rectify the issues is simply to close the wallet and re-open it.

PoS splits transactions, all PoS works this way. If you want to keep them all together you can go to the 

Settings menu -> Options -> Display tab -> 'Display coin control features'

With that you can go to 'Send' and select the inputs you want and then send them to yourself, thereby recombining them.

So what you're experiencing is essentially the same as for any other PoS coin reward, when you get a stake the transaction splits in to two.
These are new transactions and take the required 'maturing period' 24 hours before they're eligible to stake again. 
The biggest difference is probably that Monyx has what I consider a long period for maturity. Some coins it is 2 hours, some 4, some less.

My advice: There is no need to have your wallet open constantly. Open it from time to time, you will get rewards less often but they will be bigger. You only miss out once a coin has gone beyond 'maximum probability'. If that does happen then you should use the above mentioned technique to re-combine your transactions but I doubt you'd need to as the wallet shows that the reward given increases over 90 days, so as long as you get a stake within 90 days you're receiving all the PoS reward you should.

Hope that helps.

P.S I've started a Discord server for real time community chat! Feel free to join us:
https://discord.gg/EzdxPVj

**Comment by Xatra47** [comment]
Hello,

Thank you first for your answer and all the informations shared.

"Settings menu -> Options -> Display tab -> 'Display coin control features'" ->
ticked now!

"long period for maturity. Some coins it is 2 hours, some 4, some less." ->
from what I see and according to the WP, 24 hours minimum. Shorter will be
better but I have not seen a transaction being mature in few hours only.

Do you reach the 0.3% daily approx./10% a month?

I am not registered at Discord, only Telegram and it is not already easy to
follow everything for every platform! 😉

Thanks again,
Have a good staking!

**Comment by Blitzkitten** [comment]
@Xatra47 

Sorry I wasn't clear on the "Some coins it is 2 hours, some 4, some less."By that I meant other PoS based coins, Whitecoin, Blackcoin, Elite, Stakecoin etc..

MYX is 24 hours.

Without doing the maths on it, I am getting pretty close to the 0.3% daily return, maybe a little under but it should all come out in the long run.

**Comment by Xatra47** [comment]
Ok, clear. I hope I'll get that reward level ASAP. Thank you!

**Comment by monyxcoin** [comment]
@Blitzkitten thanks for the help!
I'll probably put that info in our FAQ.

**Comment by Blitzkitten** [comment]
@monyxcoin 

My pleasure! Happy to help out.

If you'd like to join the Discord I've set up to try and get some more real time communication It'd be appreciated.

https://discord.gg/EzdxPVj
