### ISSUE TITLE
Withdrawl Attempt - No E-mail to confirm.

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#218]
I am attempting to withdrawl with username JCDenton and the email has not arrived after an hour. However, when I try to re-initiate the withdrawl, it says insufficient funds, as if the withdrawal is still pending and waiting for me to click confirm.

Please confirm the withdrawal team Monyx.

Thanks!

**Comment by 2themoonandback** [comment]
Did you click the confirmation email ? Check your spam.

------ Original Message ------

**Comment by loydz21** [comment]
@monyxcoin hello sir could u please fund the wallet we're going to withdraw..thank you

**Comment by t971005** [comment]
I checked my e-mail, previous attempts at withdrawal atleast created an e-mail. It was being denied because the hot wallet was empty, but now I am not even getting e-mails to confirm the withdrawal.

**Comment by monyxcoin** [comment]
There was in issue with the mailing provider, so emails were bounced, now you should get confirmation emails again.

**Comment by loydz21** [comment]
@monyxcoin I tried to withdraw but no email receive..

**Comment by langganijen** [comment]
i think there is problem with email verification using HOTMAIL....... i withdraw 2x already with hotmail but no verification sent... My friend uses GMAIL with no problem, email verificationa arrives in seconds.. PLEASE FIX IT,,,,

**Comment by monyxcoin** [comment]
@loydz21 the email is shown as sent: https://monosnap.com/file/iAOxmxH2K2BLNbS4xaXYcWiZg7F4W5

Check your spam folder maybe?

**Comment by loydz21** [comment]
@monyxcoin my withdraw is confirm but the btc is not receive to my wallet

**Comment by langganijen** [comment]
@loydz21  maybe hotwallet doest have enough btc for your request

**Comment by loydz21** [comment]
@langganijen idk but its just small amount.

**Comment by langganijen** [comment]
hot wallet only has 

Final Balance | 0.00188774 BTC
-- | --

**Comment by loydz21** [comment]
Ohhh.,thats y..i see where u get that info sir?

**Comment by loydz21** [comment]
@monyxcoin can u please fix my withdrawal the transaction is completed but i didn't receive any btc in my wallet

**Comment by loydz21** [comment]
This is my tx id..

TX Id: 787963097c68c13139378e14b143b477b3a5f51f455e953160f302cc104d38b8
