### ISSUE TITLE
Give me back to my account deduct its very big deduct.

### ISSUE THREAD

**Issue by combofiend** [monyxcoin/monyx-coin#221]
Hi,
I got this message but when i did calculation it doesnt seem to be right

You are one of the users whose balance was affected by the bug in the system and therefore got 0.1142230 BTC Confirmed BTC.
To correct your balance we deducted: 0.1142230 BTC and 8994.8527500 MYX (equivalently to missing BTC amount based on MYX price = 0.00004 BTC).

I have got referral in ICO around 285 Monyx bonus and after exchange opened I deposited 0.11 BTC for trading and buying more. Kindly recheck the deposits/withdrawal again or kindly deduct my Monyx which I got in trading and credit back my BTC deposit which I made recently.

-freemonyx

**Comment by monyxcoin** [comment]
@combofiend you deposited `0.1043181700` BTC in total and used it to buy `4451.40460650` MYX, I checked your balance, it seems correct.

**Comment by combofiend** [comment]
why you deduct my account  myx 8994.8527500 and 0.078344 btc

**Comment by combofiend** [comment]
i earn myx in exchange buy and sell.

**Comment by monyxcoin** [comment]
@combofiend is your username "freemonyx"?

**Comment by combofiend** [comment]
yeah. or my balances bugging

**Comment by combofiend** [comment]
missing my balance what happen

**Comment by combofiend** [comment]
why you deduct my account myx 8994.8527500 and 0.078344 btc

**Comment by monyxcoin** [comment]
@combofiend I don't understand where did you see those values. I just tried to log in your account and see this: https://monosnap.com/file/wKDHGf9gSlfEX2qRdfv2klJ3E1SA2q

Are you sure your username is "freemonyx"?

**Comment by combofiend** [comment]
this is a another deduct to my account.

**Comment by combofiend** [comment]
my second account - manojaum check it and i want to change my email. to paoarceo2005@gmail.com i put wrong email.

**Comment by manojaum** [comment]
Why are u using my user name lol. Shut up. manojaum is mine. What u r trying to prove here
