### ISSUE TITLE
error in sale

### ISSUE THREAD

**Issue by chass3768** [monyxcoin/monyx-coin#222]
I did not sell for this amount. please fix this. My bitcoin balance isnt right either from the sale.

SELL | 121.61366040 | 0.00000200 | 0.00024322 | 2018-02-17 01:33:02
-- | -- | -- | -- | --

User name chass3768

**Comment by monyxcoin** [comment]
@chass3768 will investigate.

**Comment by monyxcoin** [comment]
@chass3768 should be fixed. Let me know if you'll notice something similar again.

**Comment by chass3768** [comment]
For sure, thank you for fixing it for me!
