### ISSUE TITLE
HOTMAIL no email verification received with withdrawal..

### ISSUE THREAD

**Issue by langganijen** [monyxcoin/monyx-coin#225]
i think there is problem with email verification using HOTMAIL....... i withdraw 2x already with hotmail but no verification sent... My friend uses GMAIL with no problem, email verification arrives in seconds.. PLEASE FIX IT,,,,

**Comment by monyxcoin** [comment]
@langganijen when did you try that last time? The problem should be fixed already.

And what's your email?

**Comment by JamjamMcjammerson** [comment]
I use hotmail. My confirmation emails Kept going to my junk email folder even after I confirmed it wasn’t junk. Keep an eye on junk folder, might be there.

**Comment by langganijen** [comment]
1st withdrawal 1 hour ago, and need the withdrawal to reset again,,, now i withdraw again, still no confirmation sent to email.. can you check please jenxious1@hotmail.com

**Comment by langganijen** [comment]
i used to received them very quickly, today no confirmation received 2x already. now im waiting the withdrawal to reset so that i can make my 3rd try.. :)

**Comment by monyxcoin** [comment]
@langganijen emails are shown as sent, so no debounce happened. https://monosnap.com/file/pH6pVG5RE1N8Umlk0SKp0pHRbis1x8

Check your spam folder maybe?

**Comment by langganijen** [comment]
my last email received was yesterday.. :(
![6](https://user-images.githubusercontent.com/36563229/36340266-f0cb0c7e-13d9-11e8-8928-0ab44e09188e.png)

**Comment by monyxcoin** [comment]
@langganijen interesting, I'll keep an eye on emails, for now it doesn't show new emails as bounced, so I can't really do anything, but I'll anyway contact the email service provider support.

**Comment by sa3llo** [comment]
I'm having the same problem too
I've tried to withdraw about 20 minutes ago

**Comment by monyxcoin** [comment]
So yeah, that's hotmail who blocks emails. Interesting, I'll investigate.

**Comment by marcelvan** [comment]
I had this problem on another platform it's a hotmail issue.  you have to add monyx to your email in setting. Tutorials on YouTube

**Comment by langganijen** [comment]
i put there email already to my safe senders and safe mailing list... but still no email verification received

**Comment by monyxcoin** [comment]
@langganijen check that you also have`noreply@mail.monyx.io` in the lists.

**Comment by langganijen** [comment]
i addedd already and try to send monyx to other wallet. but still no email confirmation received... i used to received it... but as of yesterday not anymore..
