### ISSUE TITLE
BTC Witdrawal issue

### ISSUE THREAD

**Issue by CryptoKJ7** [monyxcoin/monyx-coin#226]
Heloo guys I try to withdraw BTC from my wallet since 2 days and it doesn't work. I receive the validation mail I have the message succes but it still locked on my MYX account. Do you know what's going on? Thanks

**Comment by chass3768** [comment]
If the hot wallet is not funded withdrawals wont go through. Hot wallet should be funded again sometime today. People really need to start reading closed issues before posting the same stuff over and over and over and over and over and over again!!!!!!! I little investigation and reading goes a long way to limiting these repetitive posts!

**Comment by CryptoKJ7** [comment]
I finally found it out. Excuse me but since the time I invest in those kind of platforms I'm not used to see what's happening. So if I understand I just have to wait again and again and again. The issue is that there is this hot wallet issue since more than 2 days so I hope you could understand.
Thanks for the answer @chass3768

**Comment by chass3768** [comment]
If you are new to this type of investing, then you need to understand these are start up tech companies, there will be issues, there will be bugs. It takes time to get everything coded correctly and operating smoothly. Be patient and just keep trying to withdraw your btc if that is what you want to do. I withdrew some yesterday myself, so I know it is working when they have the funds in the wallet.

**Comment by CryptoKJ7** [comment]
Oh yes I understand. It's been a few time now that I invest in these kind of companies so I know the patience more now ^^ . Like I said I didn't get this kind of issue before that's why I posted the comment before to see it in the Q&A. So now I know. 
Thnks for you're advises and have a good day

**Comment by monyxcoin** [comment]
Hot wallet will be funded tomorrow after the official statement will be released.

Thanks @chass3768 for the help.
