### ISSUE TITLE
Btc withdraw problem!!

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#229]
@monyxcoin it say I successfully withdraw my btc to ur platform..the problem now is the confirmation of the tx id is 33 confirmation but until now I didn't my btc yet please help me..

Tx id: 787963097c68c13139378e14b143b477b3a5f51f455e953160f302cc104d38b8

**Comment by monyxcoin** [comment]
@loydz21 i see that withdrawal was successful. BTC was sent from our platform as you can see in block explorer. Are you sure you specified the right address?

**Comment by loydz21** [comment]
Yes this is the address wallet: 

32BaTdyKkeB2MNqHhmNyS6fYDc52RSZRoo

**Comment by loydz21** [comment]
![img_20180218_200219](https://user-images.githubusercontent.com/36193728/36351540-a69dff9a-14e6-11e8-8764-ca18cdec42eb.JPG)

**Comment by loydz21** [comment]
@monyxcoin please monyx.

**Comment by monyxcoin** [comment]
@loydz21 well, you can see the transaction is confirmed and BTC was sent to the address you specified.
So either that's a problem with your wallet or something else, in any case I can't help you.

**Comment by monyxcoin** [comment]
@loydz21 actually I see that the tx was sent to `19DbuSJrTPfAithKN1csJMRZidXQcePVSe` address. So either you specified an incorrect address or idk.

**Comment by loydz21** [comment]
What..you can't do that to you investor..

**Comment by monyxcoin** [comment]
@loydz21 as I said - you sent the withdrawal to the address you clearly could see in the form.
We are not responsible for users actions.

I see that this address was already used by you previously. So try to find a way to access your old address.

**Comment by loydz21** [comment]
@monyxcoin this is not an incorrect address..this is nuts

**Comment by monyxcoin** [comment]
@loydz21 look - https://blockchain.info/en/address/19DbuSJrTPfAithKN1csJMRZidXQcePVSe

This is the address you used before to withdraw 0.15 BTC (that even didn't belong to you actually and you got them because of the bug). The current withdrawal also got to this address, so it's your problem you can't access it.
