### ISSUE TITLE
Monyx Exchange

### ISSUE THREAD

**Issue by carlobaldevia22** [monyxcoin/monyx-coin#23]
Hello monyxcoin. just a suggestion.
Can you put limit sell orders in the earlier stage of your launch? so we can maximize the price of the coin for the upcoming Lending platform. As you said earlier, it will start probably end of february. that is a long time to wait while just trading and it can lose confidence in the platform.

**Comment by monyxcoin** [comment]
@carlobaldevia22 that's what we doing right now, thanks for the suggestion.
