### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by tipertippy** [monyxcoin/monyx-coin#230]
I tried backing up your windows wallet on a usb but it won't save it.  Do you know how to save your wallet.key (*dat) file?  And how do you open it once it is saved.

**Comment by Blitzkitten** [comment]
so you can use the backup wallet function inside the wallet to export a copy.

Or you can go into: Users\YOURNAME\AppData\Roaming\Monyx
the copy the 'wallet.dat' file to wherever you want it.

to open it, you need to use the wallet program.. the best way to check your backup worked is to:
1. Make the copy called something like 'wallet-backup.dat'
2. Cut the 'wallet.dat' file from the above mentioned folder and place it somewhere temporarily. DO NOT DELETE THIS FILE!
3. Paste your 'wallet-backup.dat' into the folder and rename it 'wallet.dat'
4. Open wallet and make sure your wallet and amounts are all there.

you now have 2 wallet files, one you can put somewhere else.
