### ISSUE TITLE
MISSED DEPOSIT

### ISSUE THREAD

**Issue by Konstantin005** [monyxcoin/monyx-coin#231]
Dear administration of the MONYX project !!!

I ask you to answer ME !!!!

I participated in your ICO and purchased 5686 MYX, then I sold them ALL at the opening  exchange and I have 1.37 BTC. I withdraw 1BTC  to my wallet. After withdraw I had 0.37 BTC on my deposit. 

On February 12 you opened withdraw of  BTC and I still have 0.37 BTC on my deposit. I trade MYX on exchange and February  13,  the whole BTC deposit is gone, and the MYX balance has a negative value (-3000 MYX).  

Where is MY deposit of BTC????  
 WHY my  MYX balance has a negative value???????

I ask you to solve the problem with the disappearance of BTC and return the deposit.

login: kerk041185@gmail.com
![1](https://user-images.githubusercontent.com/36576969/36346350-04382bf6-144e-11e8-9374-2e5035b336f4.jpg)
![2](https://user-images.githubusercontent.com/36576969/36346351-04573730-144e-11e8-89eb-4b12df80dab3.jpg)
![3](https://user-images.githubusercontent.com/36576969/36346352-0473deee-144e-11e8-9b8a-9ec3c9754bc2.jpg)
![4](https://user-images.githubusercontent.com/36576969/36346353-048dea6e-144e-11e8-8236-d31f59931e97.jpg)
![5](https://user-images.githubusercontent.com/36576969/36346354-04a8977e-144e-11e8-9640-b67799c11e2f.jpg)

GIVE YOU A SCREENSHOTS OF MISSED DEPOSIT

**Comment by monyxcoin** [comment]
@Konstantin005 interesting, investigating.

**Comment by monyxcoin** [comment]
@Konstantin005 can you check your balance now?

**Comment by Konstantin005** [comment]
Dear administration of the MONYX project,  0.046406 BTC is still missed !!!

![my closed orders part1](https://user-images.githubusercontent.com/36576969/36352857-fc662950-14cf-11e8-8bb3-8c0984ffeb8a.jpg)
![my closed orders part2](https://user-images.githubusercontent.com/36576969/36352858-fc8356b0-14cf-11e8-94c3-78a0e2c4babe.jpg)
![my returned deposit 18 02 2018](https://user-images.githubusercontent.com/36576969/36352859-fc9ff18a-14cf-11e8-8822-fad13f1aa76d.jpg)
![my withdrawals](https://user-images.githubusercontent.com/36576969/36352860-fcb9bd7c-14cf-11e8-9356-8007ad32db26.jpg)

Here is the calculation, according to the order book:

SELL 5686 MYX  = 1.37032600 BTC
-
BUY 1000 MYX   = 0.04 BTC
+
SELL 1000 MYX  = 0.05 BTC
-
BUY 1000 MYX = 0.03812000 BTC
-
BUY 1000 MYX = 0.02500000 BTC
-
BUY 1000 MYX = 0.02730000 BTC
-
BUY 1000 MYX = 0.02500000 BTC
-
BUY 500 MYX  = 0.0130000 BTC
+
SELL 500 MYX = 0.01750000 BTC
-
BUY 5000 MYX = 0.12500000 BTC
+
SELL 3000 MYX = 0.0990000 BTC
+
SELL 3000 MYX = 0.0900000 BTC

= 1.33340600 BTC  - withdraw 1 BTC = 0.33340600 BTC  (- 0.2870 BTC) = 0.046406 BTC is still missed

If I carry out the arithmetic of all orders, my balance should now be: 0.333406 BTC and 3000 MYX

Dear project MONYX, I believe in you! I hope you solve my problem with the missing balance!

Thank you in advance!

Screenshots with my appearing deposit and order book is here

**Comment by monyxcoin** [comment]
@Konstantin005 ok, i checked the history of transactions and orders and it seems you're right, now your balance should be fixed.
