### ISSUE TITLE
My balance is gone. Not showing.

### ISSUE THREAD

**Issue by CryptoRod** [monyxcoin/monyx-coin#232]
I have not done any withdrawals. I purchased 2000 myx in the ICO and the balance was there. 
Now it isn't. Please resolve this matter, I want to start staking my coins.

user: cryptorod

**Comment by monyxcoin** [comment]
@CryptoRod it wasn't you who made a sell order?

**Comment by CryptoRod** [comment]
No I did not make a sell order.

________________________________
