### ISSUE TITLE
Btc withdrawal blocked

### ISSUE THREAD

**Issue by giantjames** [monyxcoin/monyx-coin#235]
I'm unable to withdraw my btc. I fill out the address, the amount and the 2fa code. Click withdraw and the page simply reloads/refreshes. Nothing happens. 
I've read through all previous support requests but can't find anything. Can you please look at my account or tell me what to do. User giantjames

**Comment by monjil43** [comment]
My BTC withdraw in not working too why??..user name Monil43

**Comment by monyxcoin** [comment]
Withdrawals are blocked until tomorrow when an official statement will be released.

**Comment by langganijen** [comment]
@monyxcoin is the hotmail verification email fixed already?

**Comment by JamjamMcjammerson** [comment]
I use hotmail and have not had issues, maybe check your security settings in hotmail

**Comment by langganijen** [comment]
@JamjamMcjammerson it worked before until friday, starting on saturday no more verification sent in hotmail. can you confirm it work on your part starting saturday?

**Comment by 2themoonandback** [comment]
Withdrawals are blocked till 1500 UTC Monday today so basically in 10 
hrs or so . The admin said that a day and a half ago. We will learn more 
when the big announcement happens today .

------ Original Message ------

**Comment by mjlonok** [comment]
when hot wallet will be repenish again ?

**Comment by giantjames** [comment]
Now I can initiate withdraw but can't verify. Fucking useless monyx
