### ISSUE TITLE
I can not withdrew btc 

### ISSUE THREAD

**Issue by mihomike** [monyxcoin/monyx-coin#237]
Why not withdraw btc?  Error

**Comment by monjil43** [comment]
please solve the issue of tour hot wallet because it's  empty..we can't
withdraw our fund.

**Comment by mihomike** [comment]
Can you help me please

I not know hot wallet

**Comment by monjil43** [comment]
Hot wallet is that kind of wallet provide by this platform which is empty.
thats  why if we withdraw our fun it says hot wallet is empty .

**Comment by mihomike** [comment]
I getting already.   

I must wait until wallet cool yes/no

**Comment by monjil43** [comment]
yes. they have to put some btc on their hot wallet.

**Comment by mihomike** [comment]
Haha.   Thankyou I think that security system

**Comment by Palkkari** [comment]
Guys, please check previous issues made in here. They have said atleast two times already, that withdrawals are going to open again tomorrow after announcement. To that point, you can not withdraw. Scroll through the previous issues before making one next time.

**Comment by bnoizem** [comment]
still can't withdraw btc (

**Comment by t971005** [comment]
Please fill hot wallet
