### ISSUE TITLE
My balance is gone Not showing

### ISSUE THREAD

**Issue by rathorep06** [monyxcoin/monyx-coin#238]
You are one of the users whose balance was affected by the bug in the system and therefore got 0.08168995 BTC. 
To correct your balance we deducted: 0.00000001 BTC and 1,779.37325220 MYX (equivalently to missing BTC amount based on MYX price = 0.00004 BTC).

i have loss my  0.08168995 BTC. today i have open my account please deposit my amount 
what happend with me please slove my problem  !
username - pritishrathore

**Comment by monyxcoin** [comment]
@rathorep06 you didn't make any transactions at all.
