### ISSUE TITLE
IMPORTANT: Lending platform

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#24]
For the price to go up pls release an official statement of when the Lending platform will be released.  A countdown would be great! 

Yours sincerely 
Loyal investor - Carlos Matos

**Comment by CryptoSums** [comment]
this would be great! as well as releasing staking with your wallet today!

**Comment by monyxcoin** [comment]
@CryptoSums withdrawing will be enabled tomorrow, so you'll be able to start stacking.

**Comment by CryptoSums** [comment]
@monyxcoin this is great news! I would love for you to add this news to your dashboard. The exact time of when you are starting staking!

**Comment by alexpride007** [comment]
Yes please inform your team to send out an official announcement. This is crucial while all the attention is on your ICO. 

Yours sincerely
Carlos Matos: aka - Bitconnecttttt

**Comment by loudiyi1** [comment]
why i didn't found my balance?

**Comment by loydz21** [comment]
I didn't found my balance too please help @monyxcoin 

TX ID: d32a35629a96178e954ea77be07c6efc2f04587bcf0e4d1ac216fd4f7ab15d1e

**Comment by loudiyi1** [comment]
What is this i’M not make any withdrawal ??

**Comment by suyanthan** [comment]
I purchased some monyx via the exchange but still under open order. Why is that?

**Comment by monyxcoin** [comment]
I got the information that an official statement will be released in 1-3 days on our site, I hope it will clarify all the answers.

Regarding withdrawals made by someone, but not you, please let me know in this issues: https://github.com/monyxcoin/monyx-coin/issues/50

**Comment by loydz21** [comment]
Mine..i will put my reference screen shot here my balances
![received_1697845430238858](https://user-images.githubusercontent.com/36193728/35916166-77359ace-0c44-11e8-886e-318358f0b392.png)

**Comment by loydz21** [comment]
My 2k waiting for lending is gone..
![screenshot_2018-02-07-20-03-15](https://user-images.githubusercontent.com/36193728/35916216-a02ee82c-0c44-11e8-8974-2f4a01945a91.jpeg)

**Comment by loydz21** [comment]
Please help me retrieve it sir @monyxcoin

**Comment by loudiyi1** [comment]
also i have the some problem someone withdraw from my account all balance
and sell my monyx
mu user is : loudiyi
and this is the withdraw transaction
https://chain.so/tx/BTC/886b181d8555962028d555786575469e0c5dda7b9ed29fceb6040bb4fe95c3cc
