### ISSUE TITLE
Deduction of BTC and MYX due to System bug

### ISSUE THREAD

**Issue by rocky8888** [monyxcoin/monyx-coin#241]
Dear Sirs,

Monyx account: rocky88
Email: trungmai280388@gmail.com

First of all, I wish that your project will be successful.

I want to report an issue to my account due to System bug as below:

1. In ICO stage (25/12/2017):
I deposit BTC 3 times ( 0.02160365+ 0.01296407 + 0.00441586) and withdraw BTC 1 time ( -0.027). Total BTC = 0.01198358. You can check my history transactions.
At that time BTC is around 14 000 USD. So my total amount at ICO stage ~ 168 USD. 

I bought 253 MYX (0.7$/MYX plus referral bonus 8%).
I feel lucky to get it.

2. Exchange opening:
I deposited 0.0145 BTC (07/02/2018) in order to buy more MYX.
 I placed buy MYX with all my BTC. However, I got the problem with canceling the buy order, then I sent an email "Cancel the sell/buy order" to you.

After that I can cancel the buy order. Then I placed another my buy order with all BTC. Then my order complete and my MYX increase from 253 to 870. 

Then you issue a notice that you have the problem with system bug in the Dashboard. From this time, I don't touch the account again (no sell/buy, no deposit/withdraw). I wait for your fixing error.

3. Deduction of BTC and MYX due to System bug:
Now I see my balance is only 146 MYX and Zero BTC.
And in the Dashboard, it showed a notice:
Important Notice: 
"You are one of the users whose balance was affected by the bug in the system and therefore got 0.02935086 BTC. 
To correct your balance we deducted: 0.00036118 BTC and 724.74200000 MYX (equivalently to missing BTC amount based on MYX price = 0.00004 BTC)."

 I am very surprised.  It's unreasonable because I only buy more MYX.

4. Conclusion:
My suggestion for handling this matter is my account will be corrected to  (253 MYX + 0.0145 BTC).

I hope that you will check my history activities and fix the issue within 48 hours so that I can soon continue trading/deposit/withdraw MYX, BTC.

Your early review would be highly appreciated!

Thank you so much!

**Comment by monyxcoin** [comment]
@rocky8888 investigating.

**Comment by monyxcoin** [comment]
@rocky8888 ok, I see that you had 235 + 18 = 253 MYX before the exchange, then deposited 0.0145000000 BTC and bought 222 more MYX with this amount.

Right now you have 146 MYX, but should have 253 + 222 = 475 MYX, so I restore you 330 MYX.
