### ISSUE TITLE
Question about the Announcement

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#242]
Just want to know if you could atleast tell us if we should have BTC prepared for the announcement. I would like to be prepared as much as I can and it would be better to have BTC on the platform. 

Will the news in anyway be better if I had BTC on the platform?

Thanks for answering in advance

**Comment by Blitzkitten** [comment]
That's a really subjective sort of question...

The news will be what it is.. if you want to be in a position to buy because of the news.. well then best to have it on there I guess.

**Comment by 2themoonandback** [comment]
Not a problem . I'm sure the admin can answer me or not since he is the 
one who knows the news. I think any investor would want to be prepared 
atleast. Thanks for your comment though.

------ Original Message ------

**Comment by Blitzkitten** [comment]
I doubt you'll get an answer to be honest... 

what you're asking for is a pretty big 'spoiler alert'.. also making devs responsible for your level of reaction to news is a risk they shouldn't take.

If they say 'yes, get your money ready' and then you feel let down by the news, who is responsible? 

As an investor you are prepared, you know there is going to be a news update

**Comment by 2themoonandback** [comment]
How about you just let the Admin answer so we don't even have to 
speculate what he is going to say or better yet lets wait for his 
response or non response than have a talk sorry it's just more efficient 
for my time.

  Thanks.

------ Original Message ------

**Comment by Blitzkitten** [comment]
No problem..

Have a good one

**Comment by 2themoonandback** [comment]
you too :)

------ Original Message ------

**Comment by chass3768** [comment]
You are an idiot if you think admin is going to answer this question. You would be better off playing with hot wheels cars than investing in ICOS!

**Comment by 2themoonandback** [comment]
Oh man shutup... Please do us all a favor and shut up. Are you the admin 
? Are some psychic who can see the future? Is Monyx paying you hourly 
for support?

Shutup no one asked you for help.

------ Original Message ------

**Comment by JamjamMcjammerson** [comment]
Chass3768 you’re right on the money buddy
