### ISSUE TITLE
Monyx Windows Wallet Out of Synch

### ISSUE THREAD

**Issue by MongsterB** [monyxcoin/monyx-coin#243]
Hi team, 

I am having issue with my Monyx Wallet 64bit that still shows Out of Sync. Tried to install on 2 different laptops but same results. I left it open for hours but still same. Shows Wallet Offline & 0 network connection to Monyx.

Please note that I also  tried to clear Monyx folder files except wallet.dat, restart my laptop by still same.

Hoping you can assist on this issue.
![monyx](https://user-images.githubusercontent.com/36616485/36363673-ab26d994-14f3-11e8-98bb-9475be6fa495.jpg)

Regards,

Oliver

**Comment by Blitzkitten** [comment]
@MongsterB 
I use the 32 bit version on a 64 bit OS.. 
That could be a good option to try, I haven't seen any other wallets benefit from 64 bit.

best suggestion I've got

**Comment by monyxcoin** [comment]
@MongsterB maybe you also have antivirus or firewall blocking 41906 port?

**Comment by MongsterB** [comment]
Tried the 32 bit and allowed monyx qt in firewall but still same, wallet offline and 0 connections in Monyx network.
