### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Adebola100** [monyxcoin/monyx-coin#244]
Hello
I'm getting this assertion failed message now with windows wallet, how do i fix it?

![screenshot 2018-02-18 22 38 33](https://user-images.githubusercontent.com/35854938/36365123-d4ef61ca-14fc-11e8-88f6-796bd78afa62.png)

**Comment by Adebola100** [comment]
when I get this message my wallet does not sync to the blockchain

**Comment by Blitzkitten** [comment]
@Adebola100 

The best thing I can think of is go to your:

Users\YOURNAME\AppData\Roaming\Monyx folder.

In there, delete everything EXCEPT your 'wallet.dat' file.

This will essentially re-install the wallet for you but keep your personal wallet file.

NEVER EVER DELETE 'wallet.dat'
