### ISSUE TITLE
BTC Deposit not showing

### ISSUE THREAD

**Issue by jv65644** [monyxcoin/monyx-coin#245]
Hello, I have a confirmed BTC deposit but it is not reflected in my wallet. Are deposits still messed up?

3ccfb208f9ff9d31449876def8174900a08e73f725ce8078c216728d29b633c9

**Comment by Blitzkitten** [comment]
I had to wait a while before mine showed up.. about 20 confirms before it showed up in my account.. 

looks like only 3 so far, give it a little bit

**Comment by jv65644** [comment]
damn 20 confirms for $500.. lol :(

**Comment by Blitzkitten** [comment]
It might be less for you, I did got AFK for a while and found it was there when i returned (20 confirms)... so expect less than 20 :) good luck

**Comment by monyxcoin** [comment]
@jv65644 it should be deposited already, check again?
