### ISSUE TITLE
ISSUE RECEIVING LINK WITHDRAWAL MAIL

### ISSUE THREAD

**Issue by Soussie27** [monyxcoin/monyx-coin#246]
I made a WITHDRAWAL  0.04856114  BTC  and didn t received the link in my mail to confirm the withdrawal.

Please could u solve this.

Username is my emailadres:  cantona300@hotmail.com

Btc withdrawal adress:  18mCBWEnc7KtzDaXn651osL8M3FaqGY6WD

**Comment by monyxcoin** [comment]
@Soussie27 yeah, that's the known issue with hotmail, we're working on resolving it.

**Comment by Soussie27** [comment]
Okay...in meantime do I have to do something to complete my withdrawal that still is in processing transactions?

**Comment by Soussie27** [comment]
okay...in meantime do I have to do something to complete my withdrawal that still is in processing transactions?

________________________________
Van: monyx.io <notifications@github.com>
Verzonden: maandag 19 februari 2018 13:05
Aan: monyxcoin/monyx-coin
CC: Soussie27; Mention
Onderwerp: Re: [monyxcoin/monyx-coin] ISSUE RECEIVING LINK WITHDRAWAL MAIL (#246)


@Soussie27<https://github.com/soussie27> yeah, that's the known issue with hotmail, we're working on resolving it.

**Comment by monyxcoin** [comment]
@Soussie27 can't do anything really right now, we have to wait for the delisting in microsoft email providers. It should be done soon.

**Comment by Soussie27** [comment]
okay but i used to withdra always and not so long ago and always received my withdrawal request, so for now i can not withdraw...?


________________________________
Van: monyx.io <notifications@github.com>
Verzonden: maandag 19 februari 2018 13:31
Aan: monyxcoin/monyx-coin
CC: Soussie27; Mention
Onderwerp: Re: [monyxcoin/monyx-coin] ISSUE RECEIVING LINK WITHDRAWAL MAIL (#246)


@Soussie27<https://github.com/soussie27> can't do anything really right now, we have to wait for the delisting in microsoft email providers. It should be done soon.

**Comment by goldnpower** [comment]
Simply add noreply@mail.monyx.io to your safe mail list and you will get the emails in your protective options.

**Comment by Soussie27** [comment]
Thanks a lot, I just did what you said and unfortunately still nothing.




________________________________
Van: goldnpower <notifications@github.com>
Verzonden: maandag 19 februari 2018 14:32
Aan: monyxcoin/monyx-coin
CC: Soussie27; Mention
Onderwerp: Re: [monyxcoin/monyx-coin] ISSUE RECEIVING LINK WITHDRAWAL MAIL (#246)


Simply add noreply@mail.monyx.io<mailto:noreply@mail.monyx.io> to your safe mail list and you will get the emails in your protective options.

**Comment by acfa18** [comment]
Hello, I have the same problem here. Error trying to validate my withdrawal. My email: andrade2005@gmail.com Please, how to proceed with Gmail?

**Comment by acfa18** [comment]
Problem solved. I just disabled my VPN and everything worked perfectly.

**Comment by acfa18** [comment]
![image](https://user-images.githubusercontent.com/36637417/36387197-06e3a0f4-1577-11e8-8910-37cad3096b8c.png)
Please help me...
