### ISSUE TITLE
not found my all monyx

### ISSUE THREAD

**Issue by sabbirsultan** [monyxcoin/monyx-coin#247]
Dear sir / madam
                         My name is Mohammad Sabbir Sultan, my email Id is sabbirsultan15@gmail.com. I had participate ICO, buy 79 monyx, I had deposited on 25/12/2017,time is 06:46:51, 0.00440467 BTC. And after ICO buy 155.23889325 monyx. Again I had deposited on 07/02/2018,time is 09:40:00, 0.00884147 BTC. So, my totat BTC (0.00440467 + 0.00884147) = 0.01324614 BTC. And my total monyx is (79 + 155.23889325) = 234.23889325 monyx. Suddenly You deducted all monyx from my balance. I have not found my all monyx. Please check and correct it. I request that resolve my problem as soon as possible.

   Thanking You

**Comment by monyxcoin** [comment]
@sabbirsultan investigating.

**Comment by monyxcoin** [comment]
@sabbirsultan right, you had 79 MYX + bought 155 MYX with the last deposit you made (0.0088414700 BTC), so I restore you 235 MYX as you would have if not the bug.
