### ISSUE TITLE
2FA / Phone Stolen

### ISSUE THREAD

**Issue by setonjac** [monyxcoin/monyx-coin#248]
Dear Devs,

PLEASE HELP! My phone got stolen, and I have 2FA google auth. on it. I don't have my backup data.
My account name is **setonjac** and my email address is "zstevic86@gmail.com"

Can you asist me, please? 

Many thanks!

**Comment by setonjac** [comment]
guys - pls help me.

**Comment by monjil43** [comment]
no needed monyx gone..you don't need you account anymore...

**Comment by setonjac** [comment]
If you don't have anything else to say, better just hold your tung.
You're smarter when you're quet.

**Comment by monjil43** [comment]
are cry babies are here...haha

**Comment by setonjac** [comment]
man, pls, I'm waiting some help from the devs. Just stay off the chat. 
what's the point of writing here? You should be quite stupid to invest somewhere and then create fud against your own money...
