### ISSUE TITLE
Sooo wth?

### ISSUE THREAD

**Issue by jv65644** [monyxcoin/monyx-coin#249]
So there will be no lending or staking program now, just a casino? You know, the reason people invested was for lending. You supposedly have bots so why would you not do both, instead of using investor money for something they did not invest in?

**Comment by IamTheM8** [comment]
just a casino? You think is that an easy platform, thats way more better than a lending platform.

**Comment by jv65644** [comment]
I dont give a shit what you think is better. People invested in a lending platform. It is completely unethical for them to use investor money for something they did not choose to invest in. They should have refunded and started a new business plan/ ico

**Comment by iDarkXY** [comment]
yes its not right to abuse investors money. on the other hand i am in crypto....the wild wild west where everyone does what he likes

**Comment by IamTheM8** [comment]
First I am not insulting you, respect above all.

Second, they don't want to be link by the last events like Davor or Bitconnect.

They want something better for all of us investors

**Comment by manojaum** [comment]
If they want better, then why they dodnt follow FICoin path of staking. 36% profit, payment in ETH and you can keep your ficoin in your personal ETH Wallet. Trade FIBO in major exchanges. MOnyx have a working bot which has outperformed right, so why cant do that and pay us staking profit in BTC/ETH atleast 36%

**Comment by xStarBlade** [comment]
@manojaum Agreed.

**Comment by jv65644** [comment]
This would have been great had they done a staking model like mentiined. They could have made a seperate utility coin for the casino

**Comment by monyxcoin** [comment]
I showed this issue to the guy from the team, unfortunately I'm quite surprised to hear the todays news, and I didn't get any response from them yet.

**Comment by jv65644** [comment]
I dont expect you wilk. They badically stole our fucking money to fullfill their little pipe dream of a casino.

**Comment by chass3768** [comment]
The crybaby stuff kills me. Hold and sell like you obvioulsly would any other alt coin now smdh!

**Comment by jv65644** [comment]
Crybaby? They stole investor money to do a different project. Only reason you are running around defending monyx is because you're a blind fool.

**Comment by chakramchirkut** [comment]
@monyxcoin Hi MAte, an honest Q, is there really trading AI bot that the team developed? did it actually generate profit?
