### ISSUE TITLE
Nice scam.

### ISSUE THREAD

**Issue by jmunky85** [monyxcoin/monyx-coin#25]
I love how you guys declared that the lendi g would come before the exchange and then launch the exchange before lending without any notice. Then you launch the exchange at 1.80 with "problems" and reopen it with no floor because you k ow everyone will dump btc i to it so yu can all cashgrab it.

**Comment by CryptoSums** [comment]
BTC is being transfered between investors, it isn't going to Monyx... SMH. Dumbass Fud Packer, delete your stupidity from the internet please.
