### ISSUE TITLE
10% Yearly Buy-Back Plan

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#250]
Hi can Monyx confirm that they will be buying back more than 30% of the coins each day as there are too many holders with more than 10k each?  Price is tanking and the updates won't be for a few months. How realistic is the  $2 - $5 price in a couple of weeks?

**Comment by jv65644** [comment]
This coin will never break $1 until its use case is put into function.

**Comment by 2themoonandback** [comment]
Are you psychic also ? You don't know that at all.

------ Original Message ------

**Comment by jv65644** [comment]
Use some common sense dumbass
