### ISSUE TITLE
3 month lend/stake option befote casino?

### ISSUE THREAD

**Issue by jv65644** [monyxcoin/monyx-coin#252]
Everyone is furious. Wht not offer us all a 3 month lending/staking option at a reasonable starting value, while you impliment a new road map?

**Comment by jv65644** [comment]
Its a win for everyone. You dont piss off you Investors base and they get what they invested in. Then If you guys pull this off we all have twice the funds to invest into tne casino project.

**Comment by doncrypto** [comment]
They said weeks ago no lending/investment platform.

**Comment by jv65644** [comment]
Don, are you fucking retarded? In no way did they say that. Below is exactly what they said. What part of the below statment, in any way, states that they were not fucking doing lending or staking? What they are doing is trading all our fucking ico money and keepong the profits for themselves, while they fulfill their little pipe dream of a casino. 

"Due to uncertain regulatory landscape in some countries, and changed market conditions and situations, we’ve decided to NOT launch the lending/investment platform at this stage. We’re considering taking the project in a different more profitable direction."
