### ISSUE TITLE
Cant withdraw?

### ISSUE THREAD

**Issue by cryptokid3** [monyxcoin/monyx-coin#254]
Dear Monxy,

I tried to withdraw my BTC, but after I verified the withdrawal email, it didnt go through as the hot wallet was empty. I know that is normal, but after that, my withdrawal history disappeared. Is it normal?

**Comment by iDarkXY** [comment]
yes had the same its normal

**Comment by mjlonok** [comment]
when withdrawal ?

**Comment by cryptokid3** [comment]
@iDarkXY but you managed to get your btc?

**Comment by iDarkXY** [comment]
@cryptokid3 yes a week ago

**Comment by mjlonok** [comment]
2 days no withdrwal tst2xxxx

**Comment by mmgva** [comment]
Que pasa que hace rato hice una venta de monyx y aun no se procesa que problema

**Comment by cryptokid3** [comment]
@monyxcoin when the hot wallet will be refilled?

**Comment by bnoizem** [comment]
still don't have any witdraws

**Comment by mmgva** [comment]
No entiendo lo que me quiere decir! Quiero saber por qué aún no se ha procesado la venta que hice hace mas de 1 hora

**Comment by cryptokid3** [comment]
@iDarkXY so even though the withdrawal history disappeared, the withdrawal will still get through after the hot wallet gets refilled?

**Comment by mmgva** [comment]
Tipo	Monto (MYX)	Precio (BTC)	Valor (BTC)	
VENDER	202.49698254	0.00012200	0.02470463	✖
Aun no se procesa esa VENTA QUE PASA ESTA MUY LENTO

**Comment by iDarkXY** [comment]
@cryptokid3 no u will have to re do it

**Comment by mmgva** [comment]
Por que debo hacerlo de nuevo??

**Comment by mjlonok** [comment]
no withdrawal lol dont believe the buy plan

**Comment by acfa18** [comment]
![image](https://user-images.githubusercontent.com/36637417/36389301-684ba48a-157d-11e8-9459-e3c98a76fd47.png) 
I tried 5 times, with the same message ...

**Comment by mjlonok** [comment]
they kick me from the telegram lol dont believe in the buy back plan they just asking you to put more btc they will exit soon

**Comment by Palkkari** [comment]
@cryptobulot
You seriously thought it was official telegram? Their official telegram has 7,4k followers and you can't write there, so you can't get kicked. You got kicked from unofficial telegram for FUDDING I guess.

**Comment by ampersent525** [comment]
I can not withdraw my BTC to an external wallet. When will the output work?

**Comment by mmgva** [comment]
Sigo esperando que se ejecute la venta de monyx que hice ayer

**Comment by giantjames** [comment]
Still can't verify withdraw despite monyx stating you can. Seems like they are just in a last ditch effort to get more btc

**Comment by mmgva** [comment]
Ahora no dejan retirar los BTC
