### ISSUE TITLE
Includes fee 7%

### ISSUE THREAD

**Issue by Annow2011** [monyxcoin/monyx-coin#255]
what is this for joke?

**Comment by kamillasecki** [comment]
This is radiculous indeed. 5% was high already.

**Comment by Annow2011** [comment]
exactly, i was think about decrease till 2%...

**Comment by Alentype** [comment]
They didn't even told us about that ''little change''.

**Comment by Alentype** [comment]
AND NOW THEY CHANGED IT BACK TO 5% FUCK YOU GUYS

**Comment by chass3768** [comment]
0.5%

**Comment by JamjamMcjammerson** [comment]
.5% buy 5% sell

**Comment by cryptobulot** [comment]
btc withdrawal is important, all useless without it
