### ISSUE TITLE
where is my MYX

### ISSUE THREAD

**Issue by jakbtc** [monyxcoin/monyx-coin#256]
Is there a way for me to contact Monyx?
I bought in the ICO at 0.50 but I see that it all got sold on the exchange for like 0.12, on Feb 7th.

**Comment by monjil43** [comment]
they are gone buddy...

**Comment by mjlonok** [comment]
they will exit soon

**Comment by monyxcoin** [comment]
@jakbtc what is your username? There was a bug in the system on 7th Feb.
