### ISSUE TITLE
Fill Hot Wallet Please

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#259]
Hello team Monyx, as im sure you are aware

to each investor their BTC is very important to them, currently the hotwallet being empty is causing lots of stress, for the past few days almost no one can withdrawal.

Many are trying to take BTC to sell at these prices, but we are being denied this priviledge by the Monyx Team.

Whatever the issue is, please get it fixed.

If .1 BTC is alot to members of team monyx, it is alot to the users. Let us withdrawl.

**Comment by cryptobulot** [comment]
3 days had been passed the hot wallet is empty i dont think so they will fill it anymore

**Comment by t971005** [comment]
The earlier people who left the platform as soon as it opened were given the privilege to take out their BTC, but now the honest investors are being hung to dry, unable to withdrawal. Disappointing :\

**Comment by cryptobulot** [comment]
yes very disappointing still have  .2 btc in the platform , the buy back plan its only attracting people to put more btc then say bye2x!!!
