### ISSUE TITLE
BTC Deposit not working

### ISSUE THREAD

**Issue by manojaum** [monyxcoin/monyx-coin#26]
Hi,

I made a BTC Deposit a while ago. 000711d609330585ab0144e003c3218d1cbf450839c3c943fcbcff3124010213 transaction id and confirmed in blockchain. How long will it take to get deposited>?

**Comment by monyxcoin** [comment]
@manojaum I'll check

**Comment by monyxcoin** [comment]
@manojaum will be deposited in 10-20 minutes
