### ISSUE TITLE
Thank you Monyx

### ISSUE THREAD

**Issue by Alentype** [monyxcoin/monyx-coin#261]
You got our money and now you are going to trade with it, but we will get casino after 3 months, that is completely "normal". Bought for 45 cent now 17 excellent! That is how you appreciate your early investors!
Guys do something.

**Comment by IamTheM8** [comment]
buy-back plan tomorrow at MARKET PRICE

**Comment by cryptobulot** [comment]
no btc withdrawal for 3 days lol ,,, im losing hope to get my .2 btc ----

**Comment by Alentype** [comment]
Where did you read that they are going to buy at market price?

**Comment by chass3768** [comment]
WOW! You people literally kill me with this bs! Please do us all a favor and sell as soon as you possibly can and get on down the road! buh bye now!

**Comment by IamTheM8** [comment]
Read Twitter People

**Comment by t971005** [comment]
Doesnt matter if we sell or buy lol. Cant Withdrawal your funds, try it yourself

**Comment by IamTheM8** [comment]
They are going to fix that soon, read other thread on Github

**Comment by cryptobulot** [comment]
the buy back plan only to attract people to put more btc into platform,  before they will exit !!!!

**Comment by Alentype** [comment]
Thanks IamTheM8

**Comment by IamTheM8** [comment]
no worries m8, we all are here to help, and carry on

**Comment by acfa18** [comment]
![image](https://user-images.githubusercontent.com/36637417/36398431-e13656d8-15a5-11e8-8bb0-4bb58ae8f9ab.png)

**Comment by anj2208** [comment]
market price is 16c lol

**Comment by cryptobulot** [comment]
ALL PLAN ARE USLESS WITHOUT BTC WITHDRAWAL

SCAMMMM
