### ISSUE TITLE
This is what we care about and where we think the value is:

### ISSUE THREAD

**Issue by Dualism2** [monyxcoin/monyx-coin#262]
Monyx AI - The Heart and Core of Monyx
Monyx AI technology is being used to find the best prices, fastest way to execute trades and to make bets on market momentum and trends. By using Artificial Intelligence, Machine Learning, Big Data extraction, quantitivate indicators our trading bots can predict the probability for a cryptocurrency to rise or fall. We have several such systems at work. 

All trading is automated and occurs daily on a timeframe ranging from milliseconds to hours. Trading is based on our own trading platform which is based on algorithmic trading aided by artificial intelligence.

**Comment by Blitzkitten** [comment]
That's it man!

**Comment by xStarBlade** [comment]
1000% agreed. The AI literally is the heart and core of Monyx. You guys said it yourself.

**Comment by cryptobulot** [comment]
scam

**Comment by chass3768** [comment]
Speak for yourself. An online gambling and casino platform is far more sustainable than any traditional lending platform. I guess you clowns have not been paying attention to what has happened to damn near all of the traditional lending platforms at this point!

**Comment by Dualism2** [comment]
With all due respect, just run your AI bots and use part of the trading profits to buy back MYX coins. The rest works out organically.

Lending is not needed. Staking reward is sufficient for the investor, as long as coin price rises.

**Comment by cryptobulot** [comment]
all useless without btc withdrawal

**Comment by t971005** [comment]
we need hotwallet filled

**Comment by acfa18** [comment]
Scam³

**Comment by cryptobulot** [comment]
SCAM
