### ISSUE TITLE
News Tab/Page removed? why...

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#263]
News Tab/Page removed? why...

**Comment by cryptobulot** [comment]
because they will exit soon, no btc withdrawal

**Comment by new2018man** [comment]
Becasue they are not know what doing

**Comment by cryptobulot** [comment]
@chass3768

![5522222222222222](https://user-images.githubusercontent.com/36637628/36433762-6190c188-166e-11e8-8118-9cf8960179bc.JPG)
