### ISSUE TITLE
Only way for Monyx to Recover is to return price above  0.49 cents

### ISSUE THREAD

**Issue by alexpride007** [monyxcoin/monyx-coin#264]
Only way for Monyx to Recover it's reputation and ease the very rocky sentiments of your investors is to return the price above $0.49 USD, that's really the issue here. People will invest in anything so long as they are in profit and feel they can make more.

So Monyx please for your investors, raise the price up to at least 0.49 cents tomorrow and keep it above that... otherwise you will have 99% very pissed off investors who will exit the moment that withdrawal is activated 

This is not Fud.. but to simply convey what most of us are thinking.

Thank you
Carlos Matos

**Comment by Adebola100** [comment]
Thats manipulating the price, thats even worse bad idea!

**Comment by alexpride007** [comment]
and u rather stay @ 0.2 cents??  wtf. ok

**Comment by chass3768** [comment]
Price will naturally come up, if people would just start consistently trading some coins smdh!

**Comment by Velorx95** [comment]
only way consistent trading is gonna happen is if they keep the hot wallet funded at all times.

**Comment by alexpride007** [comment]
your all wrong,  vast majority here don't want anything to do with the casino project so pretty much everyone is just itching to sell at a loss and exit and i mean over 80% of investors. Damn.. only way people will stay is if Monyx can control the price. What you guys are referring to is project where people are actually interested in like lending or staking or whatever form that has to be with them getting a percentage every da/week/month whatever. Right now there is zero confidence in this casino project. so best move for monyx is to Buy back  aggressively,  rid of all those weak hands, set floor price to 1 usd. Start providing updates ASAP then people might stay and think hmm actually this look promising i will stay.

**Comment by jv65644** [comment]
They emptied the wallets. Wake up... They exited. Chass is ignorant as fuck btw.

**Comment by cryptobulot** [comment]
WE NEED OUR BTC OUT

**Comment by cryptobulot** [comment]
SCAM .
