### ISSUE TITLE
Just Exit Scam Already

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#268]
The blood on the walls should be apparent to everyone by now,

No BTC in the hot wallet, 18k USD in the cold wallet. They have no BTC to do a buy back.

They have no BTC to fund withdrawals. 

They have sent all of our BTC to exchanges and sold right away right after ICO, and today also.

**Comment by chass3768** [comment]
People like you should be banned from these pages immediately. You have absolutely no proof and are just spewing bullshit! Go sit your ass down somewhere and shut the hell up!

**Comment by t971005** [comment]
No proof/ check their hotwallet addresses kid, you are in denial. Have fun waiting for this Casino in 3 months (LOL), also, go ahead and try to withdrawal your BTC - you will never be able to. CYA

**Comment by t971005** [comment]
The only non scammer in this whole operation is the github dev! He is a hero amongst thieves!

**Comment by chass3768** [comment]
No proof, bye felicia!

**Comment by NeekCrypto** [comment]
t971005: Please shut the f*ck up. Sounding like a miserable cry baby b*tch. You should exit your damn self away from the MonyX community.

**Comment by t971005** [comment]
Oh I am and will - enjoy the 2400 myx buyback a day lol, thats all they can afford because they sold the rest of your bitcoins

**Comment by chass3768** [comment]
No proof, bye felicia, take your bitch ass on down the road!

**Comment by NeekCrypto** [comment]
t971005: Tell yourself whatever you need to hear in order to feel better. I'm actually good! This is crypto baby! Win or lose I know what I signed up for. So there should be no reason for you to cry out and suggest for them to "Exit scam already" like a sore fcking loser lmfao.... You'll be fine young grasshoppa. Just remember to always invest what you could afford ;)

**Comment by t971005** [comment]
Sure, i'm sure its comfy to go quietly into the night. 
To make me feel better about what is the question, it's like you are implying that indeed you agree we are being hung to dry. 


Its been months now, I guess it does take a fair amount of time to liquidate 400 BTC

**Comment by TonyMcclure** [comment]
It may be a scam. If they r not  concerned about keeping the hot wallet filled. They should know, if BTC can't come out  frequently. Why would people refer people. They have to know that. I tried withdrawing just .02 BTC the other day. Same problem. I made a ticket, other people commented &  eventually  GitHud said he filled the wallet. I didn't even try again. 
  GitHud didn't add in my issue, that he fills it once a day. But the next day that's what they was saying on telegram.
  But the point is they have their BTC & we have ours. The wallet should be fill 2 , 3 or how every many times needed to keep BTC flowing out, so more can come in. I won't recommend anyone to put BTC in Monyx till BTC can flow like water

**Comment by 2themoonandback** [comment]
You guys forget the ONLY reason the hot wallet is funded is because 
USERS I REPEAT USERS STOLE MONEY . Get the facts straight or you just 
sound foolish. Blame the USERS who STOLE money not the platform. If 
USERS didn't steal we wouldn't even have this hot wallet issue. They had 
NO choice . Would you guys prefer they kept funding the wallet while 
users keep stealing. WAKE UP. You sound dumb.

------ Original Message ------

**Comment by TonyMcclure** [comment]
They lost BTC due to a bug. Not hacked! & still that's no excuse. Their BTC their bug. Can't hold people's BTC hostage for that.

**Comment by TonyMcclure** [comment]
People can't pull out their BTC. What's good about that? What makes u think ur going to be able too? Thank McFly think 🤔

**Comment by 2themoonandback** [comment]
I already pulled my BTC out days ago and this has been happening since 
launch 3 weeks now . We have always pulled out BTC out . This isn't new. 
It may be for you though.

------ Original Message ------

**Comment by TonyMcclure** [comment]
Fact remains, u see new can't withdraw issues every day. Who's going to put BTC in when they can't withdraw?
