### ISSUE TITLE
Round 1 bonus is not received.

### ISSUE THREAD

**Issue by manojaum** [monyxcoin/monyx-coin#27]
Havent received the round 1 bonus, i purchased more than 2k monyx in ICO. Kindly check.

**Comment by monyxcoin** [comment]
@manojaum you bought 2470 tokens and got 247 bonus tokens on 25th December. Seems like you got the bonus?

**Comment by manojaum** [comment]
Yes, my mistake. thanks for quick response :)

**Comment by manojaum** [comment]
closed
