### ISSUE TITLE
Proposed Suggestion for Monyx's Direction and Sample Announcement

### ISSUE THREAD

**Issue by dannyokay** [monyxcoin/monyx-coin#271]
Hi Monyx and Monyx Github Guy (You are the Real MVP),

I am an investor in Monyx and I wish to see the project continue in the positive direction amidst all the unnecessary and needless fud. I have came up with an announcement summarizing what most of what we investors really want and the reason we invested in your platform in the first place. I hope you can relate to the developers regarding this as I truly wish to see Monyx succeed for the sake of all of us, investors.

[Proposed New Announcement for Your Consideration]

Dear Investors,

We had a very extensive discussion and decided to resume our initial lending programme. We will be promising the highest rates in the market as per the whitepaper 53-60%, we will not be announcing any promotions as we believe they are just gimmicks for the short term and we wish to grow as a community organically. We will strive to be the industry's No.1 and restore the faith in lending platforms again.

As for the external exchanges, a few of the more renowned ones has stopped taking in lending platforms but we are not afraid that it will affect us in anyway with the direction which we have chosen. Our internal exchange will be sufficient enough for a strong daily volume. We will be actively and aggressively marketing Monyx through social media and other means.

In regards to the fud and uncertainty surrounding the term "Lending", we want to assure our investors that we are confident and steadfast in our decision to resume our lending programme as we are based in Europe where there are no strict or firm regulations in regards to Lending.

No US Citizens shall be allowed to participate in the programme and it has already been mentioned in our whitepaper.

Buyback programme will be every Monday without fail to push up the price and we have revised our staking programme to incentivize holders of Monyx tokens.

Plans for the casino will still be in place and we will be actively work on it behind the scenes for Q3 and Q4. We plan to progressively transition our lending programme towards that direction while remaining as profitable for both our investors and us. Lending will then be scrapped completely.

We will then push to get listed on external exchanges once we have accomplished our vision.

New roadmap to be announced by the end of February.

We sincerely appreciate and hope you keep the good faith in us as we take Monyx together to the moon.

Monyx Team

**Comment by JamjamMcjammerson** [comment]
👍🏼

**Comment by TonyMcclure** [comment]
👍

**Comment by t971005** [comment]
First things first though - fill the hot wallet and the cold wallet. Both are empty. Thanks

**Comment by durgaavinash4** [comment]
Give us correct clarification

**Comment by bbits91** [comment]
MONYX PLEASE LISTEN THIS!!! WE WANT TO SUPPORT YOU. <3

**Comment by JamjamMcjammerson** [comment]
T971005, you got those hot and cold wallet addresses. Wouldn’t mind crawling down the rabbit hole a bit

**Comment by t971005** [comment]
I'll give them a few days to amend the issue otherwise yes I will link the wallet addresses and some of the associated larger transactions, they sent over 300 btc on December 26th which has never returned so presumably all of those were sold onto an exchange for fiat money. Pretty disappointing.

**Comment by chass3768** [comment]
@t971005 I think it is completely funny you think looking at wallet address and transaction of sending to other addresses supports your asinine assumptions lmo! You are complete idiot and have no business being in these ICOs period!

**Comment by chass3768** [comment]
You are an idiot, go play with hot wheels instead of investing in ICOs!

**Comment by t971005** [comment]
To top it off, the price of MYX is half of that value (BTC) so you are currently at 25% of your initial value! And still you defend.

**Comment by TonyMcclure** [comment]
It may be a scam. If they r not concerned about keeping the hot wallet filled. They should know, if BTC can't come out frequently. Why would people refer people. They have to know that. I tried withdrawing just .02 BTC the other day. Same problem. I made a ticket, other people commented & eventually GitHud said he filled the wallet. I didn't even try again.
GitHud didn't add in my issue, that he fills it once a day. But the next day that's what they was saying on telegram.
But the point is they have their BTC & we have ours. The wallet should be fill 2 , 3 or how every many times needed to keep BTC flowing out, so more can come in. I won't recommend anyone to put BTC in Monyx till BTC can flow like water. 
   Yea, I'm posting this everywhere lol

**Comment by t971005** [comment]
There is no BTC, they sold it all for real money. They are rich in their country now. Very rich.

**Comment by t971005** [comment]
They will wait until after bitcoin dumps below 10k again to fill the hot wallet. Best business practices!

**Comment by cryptobulot** [comment]
THE BUY BACK PLAN ONLY ATTRACTING PEOPLE TO PUT MORE BTC INTO THE PLATFORM THEN SAY BYE2X,,,,, ALL PLAN ARE USELESS WITHOUT BTC WITHDRAWAL,,,,

**Comment by Ghabh** [comment]
External exchange very important. Get it listed on coinexchange as soon as possible. Staking very important. Make sure the system really generate 10 percent per month and show proof that the staking really work and generate percentage as promised. With that it would be good enough. Lending will not attract anymore buyer, as most are scared already. Casino will split investors and damage the unity among investors as there are different opinion on the subject.

**Comment by Ghabh** [comment]
Monthly buyback plan, staking, external exchange and easy in out BTC will already spur interest in the coin and could bring the price higher. Only loyal investors are left at this level and pls increase the unity to among us. This 9 mill ++ coin could easily push higher in time to come.

**Comment by chakramchirkut** [comment]
Why not just burn 30% coins to jack up the price. Use the MYX as token in the casino platform.

**Comment by Ghabh** [comment]
What up monyx? Where are you?
