### ISSUE TITLE
My  990 MYX are gone

### ISSUE THREAD

**Issue by wintrade56** [monyxcoin/monyx-coin#272]
Dear sir .Admin please fix my account .My account was hacked....my 990 MYX coins are gone . I never request open sell order .My username : wintrade56 E-mail: wintrade56hotmail.com Thanks: 20Feb2018

**Comment by cryptobulot** [comment]
monyx gone ,,,, scam

**Comment by t971005** [comment]
If they dont add bitcoin to the hotwallet tomorrow this scheme is done
