### ISSUE TITLE
Withdraw problem

### ISSUE THREAD

**Issue by Konstantin005** [monyxcoin/monyx-coin#275]
I can't withdraw my BTC
![screenshot_2018-02-20-09-21-08-029](https://user-images.githubusercontent.com/36576969/36410185-90b6a0c0-1620-11e8-9fc3-65946591621b.jpeg)

**Comment by cryptobulot** [comment]
there is no more withdrawal they wont pay us anymore

**Comment by Adebola100** [comment]
They said they will fund hot wallet today idk tho... they havent been really keeping there word

**Comment by monjil43** [comment]
because they scam us man....

**Comment by Adebola100** [comment]
i wouldn't go as far as that right now, I was able to withdraw a couple of days ago they just moving hella slow at times

**Comment by chass3768** [comment]
I got all my Investment bitcoin out plus some profits, a week ago, am only working with profits in this now. So if you sat on your hands and did nothing when the exchange opened, you have nobody to blame but yourself for your lack of getting bitcoin out of the platform at this point!

**Comment by anyagixx** [comment]
@Konstantin005 напиши мне в телеграмме @putopelatudo

**Comment by JamjamMcjammerson** [comment]
Chass3768 you’re admitting you think they’ve scammed off then because if you didn’t pull profits already ‘you have nobody to blame but yourself’ 

You seem to be changing your tune all of a sudden.
