### ISSUE TITLE
Staking+"Error or the hot wallet is empty and soon will be funded"

### ISSUE THREAD

**Issue by Xatra47** [monyxcoin/monyx-coin#277]
Hello,

"Error or the hot wallet is empty and soon will be funded"
Please put some BTC in for us to spend our BTC somewhere else than in MYX.

Staking reward is at 1% on my wallet, not 10%. Why such a difference?

**Comment by chass3768** [comment]
Because it is not staking, it is mining also known as minting.

**Comment by Xatra47** [comment]
Thank you for your answer. So staking and its 10% is not yet available (and may not be at all)? Is it mentioned somewhere that minting is 1% or it depends of your luck?

**Comment by chass3768** [comment]
You will be lucky to get 1% ROI every 48 hours from minting.

**Comment by chass3768** [comment]
It will most likely be around 0.33% ROI every 48 hours.

**Comment by Xatra47** [comment]
On probability in minting tab at 30 days, it says equivalent to 1%... Wait
& see. Thanks.

**Comment by chass3768** [comment]
Everytime you get a payout, they split your amount of coins and the maturing starts over again. The smaller the amount of coins, the longer it takes to get a payout. Minimum will be about every 48 hours.

**Comment by Xatra47** [comment]
Yeah I saw that. Thank you.

**Comment by cryptobulot** [comment]
scammed

**Comment by Xatra47** [comment]
I hope no. Coming days will tell us! At least they communicated, as
planned, yesterday.

**Comment by chass3768** [comment]
@Xatra47 Don't pay that idiot @cryptobulot any mind, he is just an idiot troll who has no business even being on this page! I hope @monyxcoin bans, blocks, and removes him and a few others!

**Comment by Blitzkitten** [comment]
minting/staking is the same thing, just two names for it.

It is all a Proof of Stake block reward system. 

If I recall correctly, they changed the reward when they did a fork/changed the code after the ICO (but before the wallet release)

**Comment by Xatra47** [comment]
Ok, thanks. They did change from 10 to 1% then, or had forgotten a 0.
