### ISSUE TITLE
Error or the hot wallet is empty and soon will be funded

### ISSUE THREAD

**Issue by anyagixx** [monyxcoin/monyx-coin#281]
@monyxcoin 
Why I can't withdrawal my BTC???
Error or the hot wallet is empty and soon will be funded
--

**Comment by chass3768** [comment]
Go read the other posts about this, it is nothing new smdh!

**Comment by cryptobulot** [comment]
because its
 already scammed

**Comment by chass3768** [comment]
@cryptobulot I HOPE @monyxcoin  BLOCKS AND BANS YOUR DUMB ASS FROM THIS PAGE! I HOPE THEY BAN A FEW OF YOU IDIOTS!

**Comment by t971005** [comment]
Yeah its a scam, they wont be filling the hot wallet again it looks like

**Comment by chass3768** [comment]
I hope @monyxcoin bans and blocks both of you assholes! @cryptobulot @t971005

**Comment by mjmv16** [comment]
Realice una venta el día de ayer y aún no la procesan sigue en mis pedidos abiertos.. Cuánto más debo esperar? @monyxcoin

**Comment by Velorx95** [comment]
No reason to call these guys assholes because they are right. Everything that is happening is leading towards clear signs of a scam. When they lock your withdrawals for no reason at all and aren't allowing investors to take their money out, it usually ends up being a scam sadly :(

**Comment by Velorx95** [comment]
Also the dev is completely gone who was always here everyday answering every question
