### ISSUE TITLE
MXY Withdrawal Issues

### ISSUE THREAD

**Issue by drunksteve** [monyxcoin/monyx-coin#282]
I'm trying to withdraw MXY into my QT Wallet. I have 2750 coins and the only amounts I have been able to transfer so far are: 250, 500, and 1000... Every time I try to transfer more I get an error. Any suggestions?

**Comment by chass3768** [comment]
Hard close and reopen the wallet, so it resyncs! If that doesn't fix it, I don't know what to tell you.

**Comment by drunksteve** [comment]
I did try that :( thanks. The error is within the website as I'm trying to transfer from platform to QT.

**Comment by t971005** [comment]
You can't withdrawal because they are laughing all the way to the bank, with your money

**Comment by cryptobulot** [comment]
lol,,,,,,they are gone , thanks i x40 my btc thnks monyx lol !!!
