### ISSUE TITLE
FILL THE HOT WALLET!

### ISSUE THREAD

**Issue by oildude** [monyxcoin/monyx-coin#286]
Monyx, why are you holding our funds hostage. Either deposit funds in the hot wallet so people can cash out or issue a statement saying you're done. Right now, all you are doing is playing with peoples money! No matter what kind of idea you come up with, do you really think people will now trust their money with you? The only way to communicate with you is on a coding site? Get real!  TOO MANY RED FLAGS!!!

If you cant pay out on a 0.13 coin why would people think you would pay out if they hit big at a casino!! Tell me...... the casino thing, was that a last minute squeeze attempt. Just curious!

**Comment by JamjamMcjammerson** [comment]
Monyx GitHub has gone completely silent since the casino update. Hmmmmm

**Comment by acfa18** [comment]
In addition, at exactly the same time they removed the news section of the site,...Smell Scam...
