### ISSUE TITLE
Scam Scam Scam Scam Scam Scam

### ISSUE THREAD

**Issue by t971005** [monyxcoin/monyx-coin#289]
Since they have exit scammed, this post wont get removed.

The only non-scammer in the whole operation was the github developer

Just fill the hot wallet and prove me wrong

**Comment by Velorx95** [comment]
Well even the github developer is gone now. So he might not be so innocent after all.

**Comment by combofiend** [comment]
the buyback will definitely happen, but with some delay it seems. Still waiting for the details from the team.

**Comment by xStarBlade** [comment]
@combofiend are you a dev now?

**Comment by CryptoNaj** [comment]
FILL THE DAMN HOT WALLET
