### ISSUE TITLE
my balance

### ISSUE THREAD

**Issue by loudiyi1** [monyxcoin/monyx-coin#29]
why i didn't fund my balance ?

**Comment by loudiyi1** [comment]
I’m not make any exchange or withdraw why i see that i’m exchanged my balance and withdraw it?

**Comment by monyxcoin** [comment]
@loudiyi1 if it wasn't you who made sell orders and withdrew the funds, then it means your account was compromised. We can't do anything in this case. Last login was made from 188.114.110.184 IP, if it's not yours, I suggest you to change the password.
