### ISSUE TITLE
buy back promise or scam promise

### ISSUE THREAD

**Issue by combofiend** [monyxcoin/monyx-coin#290]
wheres the buy back promise. or scam promise. im waiting 12hours to buy back promise but nothing happen. scammer idiot. go to hell

**Comment by jv65644** [comment]
You do realize their buyback was 20% over the  course of a year? Their "buyback" will make very little difference in the market price.

**Comment by combofiend** [comment]
the buyback will definitely happen, but with some delay it seems. Still waiting for the details from the team.

-monyx.github
