### ISSUE TITLE
Dear Lord MonyX Staff Read This

### ISSUE THREAD

**Issue by techy326** [monyxcoin/monyx-coin#291]
Fund your wallet, talk to your damn investors, and switch to Thorn Coins model....They switched their entire system in days. Staking is not much different from lending. Your block explorer and internal exchange actually look decent. Sure, we had a glitch here and there, but that is to be expected.

You haven't funded your wallet and you turned off your News tab. Some people liked the casino idea, but a bunch more did not. You can still turn the ship around, but you are hurting your credibility by not talking to us......It's such a shame. You have potential. Was this really just a scam or is it just lack of leadership? Listen to your investors. If you build it nerds will come.

**Comment by Ghabh** [comment]
The BTC our team got... reserve to pump monyx on external has finally been channel to lend connect. Lend connect to the moon today...and onward. Mkt have improved.

**Comment by Ghabh** [comment]
Dev seems not showing responsibility.
