### ISSUE TITLE
Strasbourg court

### ISSUE THREAD

**Issue by snicksand** [monyxcoin/monyx-coin#293]
I believe that if there is no answer, there should be a collective statement in the Strasbourg court. It does not matter what bitcoin is, there is a fact of fraud and this is enough. Wait a couple days and proceed to the organization of collective treatment

**Comment by snicksand** [comment]
I think it would be smarter for them to buy all the coins at 20-50 cents and stay clean and in profit

**Comment by t971005** [comment]
They are based in Nigeria. If you can find their identities perhaps there can be some reprisal. 

The police would love to loot these scammer's treasure box i'm sure.

**Comment by t971005** [comment]
But yes, the fraud should be documented so that if this case ever gets the light of day, these people will be held accountable.

**Comment by chass3768** [comment]
HAHAHAHAHA you crybabys are funny, nobody forced you to invest in this, yet here you are! Even if they exit, nobody will be held accountable you fools, that is the risk with ICO investing like this! Get over it, move on to the next one, or go play with your dolls in a corner for fucks sake!
