### ISSUE TITLE
Round 1 token purchase bonus

### ISSUE THREAD

**Issue by glessor** [monyxcoin/monyx-coin#3]
Could you fix an issue where your system failed to credit me 150 tokens for 1,500 purchased in round 1? I made 3 purchases and this one received no bonus. Sent several emails to support. 
Monyx username is glessor.

**Comment by monyxcoin** [comment]
@glessor unfortunately our support team experiences heavy load, and this repository is more for coin-related issue. But I asked my colleague to look at the issue, check your balance, it should include the missing bonus.

**Comment by glessor** [comment]
Amazing!

Thank you.
