### ISSUE TITLE
my btc payment missing still 

### ISSUE THREAD

**Issue by kalpanos1** [monyxcoin/monyx-coin#30]
Hi,

It has been passed more than 3 hours since i sent my btc for buying more tokens and although it got more than 20 confirmations still havent been credited into my wallet.So please could you please check it ?

The TX id is 68c931bc0205d52c9f7d6dbe6a6bd688cb76cee0d87c564a989278561d902ca8.

Thanks in advance,
Panos

**Comment by loydz21** [comment]
@monyxcoin mine too..i send my btc so that i can buy more token it has 5 confirmation but my btc didn't appear to your platform please help.
TX ID: d32a35629a96178e954ea77be07c6efc2f04587bcf0e4d1ac216fd4f7ab15d1e

**Comment by monyxcoin** [comment]
@kalpanos1 @loydz21 as we stated on the site, deposits are still collecting, it should be there now, check your transactions history.

**Comment by kalpanos1** [comment]
Hi,

Yes on the transaction history they are still in pending status ,anyway hope it got confirmed soon so to be able to buy asap more tokens.
