### ISSUE TITLE
BTC withdrawal

### ISSUE THREAD

**Issue by falconsoars** [monyxcoin/monyx-coin#31]
I'm new to Monyx but was told by others already in Monyx that you are reachable on Github I'm interested in Monyx , but always test deposit/withdrawal BTC, I deposited BTC, was smooth bought 200 moneyx & then sold very smooth. I tried to withdraw BTC 0.0129 as this is a very important function to make sure works it keeps saying "error" this is on 2/6, am I doing something wrong? please explain. my user is falconsoars, email cryptocrunch7@gmail.com.
Thank you

**Comment by monyxcoin** [comment]
@falconsoars our hot wallets are deposited from time to time. We'll make it more stable during next few days.
