### ISSUE TITLE
TrollBox suggestion

### ISSUE THREAD

**Issue by IamTheM8** [monyxcoin/monyx-coin#32]
It would be nice and a good experience to have a trollbox on the exchange, here are some codes for you to use in a beta version.

-https://github.com/miguelmota/trollbox
-https://github.com/gloryman/btce-trollbox-rs

If you consider good the idea, first make a poll on the website, to see if the community agree/disagree the idea.

Thanks, Best to the Project

**Comment by monyxcoin** [comment]
@IamTheM8 sounds good, yes, we'll consider it

**Comment by CryptoSums** [comment]
great idea

**Comment by loydz21** [comment]
@monyxcoin Can u please my order i want to cancel it but nothing happens, cancellation succeed...thank you

**Comment by IamTheM8** [comment]
Thanks for reading all our request @monyxcoin
