### ISSUE TITLE
Windows wallet, Staking and My favorite  No BTC in deposit

### ISSUE THREAD

**Issue by Sirbearingson** [monyxcoin/monyx-coin#37]
Im a noobie when it comes to tech stuff so can someone please help me with downloading installing and running the windows wallet? It says in the Ico section that it was available however when i got on github it says only for mac and linux 
ALSO 
BTC deposits are snoozing
why is this?

**Comment by loydz21** [comment]
thats the os dude..win 32 or win 64 is the system type

**Comment by Sirbearingson** [comment]
told you im a noobie.... 
i already started downloading it thanks for the ouch in the right direction <3

**Comment by loydz21** [comment]
No problem dude..lets all help each other..

**Comment by Sirbearingson** [comment]
How may i be of service 🖌
