### ISSUE TITLE
Trading Problem

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#38]
@monyxcoin I can't cancel my order. while im on trading suddenly my order lag even the last price and my bid is coincide it didn't succeed..how do I do can you please help me.

**Comment by jaytan17** [comment]
Use laptop or pc to cancel your order

**Comment by loydz21** [comment]
I already use pc sir.

**Comment by monyxcoin** [comment]
@loydz21 will check.

**Comment by loydz21** [comment]
@monyxcoin Thank you sir

**Comment by monyxcoin** [comment]
@loydz21 I don't see any active orders on your account (username "loydz21", right?). Try to reload the page.

**Comment by loydz21** [comment]
yes sir..i will refresh my browser for a bit

**Comment by loydz21** [comment]
the order bug gone sir..

**Comment by loydz21** [comment]
Thank you so much

**Comment by monyxcoin** [comment]
@loydz21 np!
