### ISSUE TITLE
Please halt the exchange immediately!

### ISSUE THREAD

**Issue by xStarBlade** [monyxcoin/monyx-coin#39]
Someone is hacking the exchange. they purchased 9 million tokens! also time stamps are incorrect and out of order. Something is going wrong. Please check it out!

**Comment by monyxcoin** [comment]
@xStarBlade investigating

**Comment by xStarBlade** [comment]
![photo_2018-02-07_02-27-20](https://user-images.githubusercontent.com/36200500/35905953-7d5fb150-0bae-11e8-88d5-c6c5ad46dbfd.jpg)

**Comment by monyxcoin** [comment]
@xStarBlade thanks for the information!

**Comment by loydz21** [comment]
Woahh..thats a big one.

**Comment by loydz21** [comment]
Good job sir @xStarBlade

**Comment by loydz21** [comment]
@monyxcoin Sir, I think we the should paused the trading for the mean time and go for lending platform i guess.

**Comment by xStarBlade** [comment]
Thank manojaum too he caught it. Keep up the good work guys!

**Comment by monyxcoin** [comment]
@xStarBlade so the order isn't actually processed, it was cancelled, but somehow got to the history table. Thanks anyway, that's very useful that there are someone who watches! We will fix the displaying bug!

There are also automatic systems that prevents something like this to happen.

**Comment by manojaum** [comment]
V can't let monyx go down like this. 😊

**Comment by loydz21** [comment]
@monyxcoin I hope..it will not stop the monyx..we will help for the security sir if must.

**Comment by Inspiratornels** [comment]
Great job to everyone at MONYX working hard for the platform, keep up the good work.

Please I will like to humbly request that you keep the community updated every day, MonyX has all the attributes to be a $30 coin right now, uncertainty is affecting investors, please keep everyone in the loop of things a little update here and there on Twitter and Telegram keeps the confidence and community happy.

Lastly the Staking and lending platforms are the key features needed to drive the use of the coin and thus the value up to where it deserves to be, opening up lending at minimum $5 with early lending bonus will be a great deal for the community.

once again keep up the good job.

InpiratorNelson
