### ISSUE TITLE
Wallet for windows

### ISSUE THREAD

**Issue by jwsbj** [monyxcoin/monyx-coin#4]
will there be an easy way to get the wallet for windows, we would love to have the wallet just as much as everyone else (i have MYX coins)

**Comment by Adebola100** [comment]
need wallet for windows

**Comment by Cryptomaster23** [comment]
Really hoping for a windows wallet sometime before launch. THAT"LL BE GREAT !!! @monyxcoin

**Comment by monyxcoin** [comment]
Sure, the wallet comes asap, sorry for the delay, had some complexity accessing a windows machine.
