### ISSUE TITLE
Issue with Monyx exchange page in mobile

### ISSUE THREAD

**Issue by manojaum** [monyxcoin/monyx-coin#40]
Hi

I have been trying to trade in exchange from my mobile chrome using desktop site option. Some of the tabs are misaligned and if I place an order am not able to cancel it because of window size.  Kindly check from your side and improve the user interface for accessing through mobile

**Comment by monyxcoin** [comment]
@manojaum thanks for the info, we'll optimize the exchange for mobiles in the coming days.

**Comment by monyxcoin** [comment]
@manojaum check now please, is it better?
