### ISSUE TITLE
ICO SUPPORTERS

### ISSUE THREAD

**Issue by NoobHere2018** [monyxcoin/monyx-coin#41]
HI Team Monyx,

I'm new to this so i was just hoping someone on the Monyx team can explain to me what was the point or "benefit" of supporting the ico stage of the project? I would have been 100X better off if i had saved my money till the exchange and buy ridiculous amounts of Monyx coins at cheaper than ico prices. Is there some sort of bonus that people that supported you guys since Dec. 25 will be receiving? Thank you in advance for helping me understand.

**Comment by monyxcoin** [comment]
Sorry, I'm not responsible for the decisions the team makes (though I'm redirecting all questions to them).

If I understand correctly, this decision was made to make the market more active. Also if I understood them right there are no new tokens on the market yet, so nobody forces people to sell at this low price, considering that with staking and lending openings price should and will go higher than the last round price.

So I just hold my small amount of tokens (that I also bought via BTC) until the point when the price is higher than the last round price (at least).

**Comment by NoobHere2018** [comment]
yes i understand that and i will hold my coins, i actually bought more coins. That still leaves everyone who joined the ico wondering why did we buy a thousand coins at $1 when if we waited 2 MONTHS we could have bought 10,000 coins at .10 when the exchange opened. The day one supporters were tossed to the side and all new whales are just coming in and buying monyx at insanely low prices.

**Comment by NoobHere2018** [comment]
Hopefully the devs can do something for their day one supporters who stuck around through delays, terrible communication, supporting them on Christmas day etc.

**Comment by kamillasecki** [comment]
Again as @monyxcoin said it is not Monyx fault that the price is as it is. It would not be if people are not willing to sell for less than they bought during the ICO. As much as I would prefer to see the price as before as an investor, I am also understanding that artificially forcing the price up but not allowing people to sell under certain point is not good for market. We had 2 choices to look at the 1.80 price and not having any trades or let demand and supply do its job.
Again as an investor I personally think that it would be fantastic if they let us to lend at $8 but I know that it would only kill the platform as they would have to pay us daily interest at the market price so other words return us our coins in like 5 days, and then pay us with tokens out of their pocket for the next 1xx days.

**Comment by monyxcoin** [comment]
I got the information that an official statement will be released in 1-3 days on our site, I hope it will clarify all the answers.
