### ISSUE TITLE
I get a error withdrawing a small amount in test mode

### ISSUE THREAD

**Issue by 2themoonandback** [monyxcoin/monyx-coin#42]
this message is what I get for withdrawing 37 coins Error or the hot wallet is empty and soon will be funded

Not too sure how to cancel the order now also . It still hasn't credited me back 

Monyx account on the platform is Mm3DGerr6nJAnXi2uEeu2H958ZQeGkEL5m 

and wallet I'm withdrawing to is  MnmKKwuFfqAfciukt8BQ1orxsSMm7eYZRV

**Comment by monyxcoin** [comment]
@2themoonandback how much coins did you have before? I'm pretty sure if you reload the page, the coins will be credited back, since they won't be deducted from the account unless the transaction was successful.

**Comment by 2themoonandback** [comment]
You are correct sorry just checked they are back. Should I try again to withdraw or just wait for the official announcement ?

**Comment by 2themoonandback** [comment]
Sorry it worked now the withdrawal is incoming to my wallet . Thank you for being patient.
