### ISSUE TITLE
missing deposit

### ISSUE THREAD

**Issue by kalpanos1** [monyxcoin/monyx-coin#43]
Hi,

My deposit is missing since 15 hours or so since yesterday.Also need to notify that the address of your wallet yesterday was different that the one you have today for making deposits.Is this the cause that my deposit hasnt been credited still and hence my funds will be lost?
My TX id is 68c931bc0205d52c9f7d6dbe6a6bd688cb76cee0d87c564a989278561d902ca8.

Thanks

**Comment by kalpanos1** [comment]
for your evaluation the deposit address in monyx's website yesterday was this one 3P8tr1t2KeEyr5Sk16eT97zx28w1SJhM29,where i sent tmy btc.Hope this helps and finally my deposit got credited later today.

**Comment by monyxcoin** [comment]
@kalpanos1 don't worry, we keep all the addresses assigned to users, so no deposits will be lost.

The deposit should be credited soon, I'll get back to you once the next batch of missing deposits is processed.

**Comment by monyxcoin** [comment]
@kalpanos1 check your balance, new batch was processed.
