### ISSUE TITLE
Made a trade on the exchange and got wrong amount of BTC

### ISSUE THREAD

**Issue by amittt11** [monyxcoin/monyx-coin#44]
Hi, before few hours i trade throw the exchange. my order info is:
SELL | 525.51522468 | 0.00006600 | 0.03468400 | Completed
So i should get 0.03468400 BTC but only got 0.026126 BTC. I think there is a bug there.
Can u fix it please?

Thanks.

**Comment by loydz21** [comment]
The trade is not equal when i computed it @monyxcoin

**Comment by monyxcoin** [comment]
We'll investigate. If there is an error in processed orders, balances will be deducted/credited the missing amounts, so don't worry.

**Comment by manojaum** [comment]
Hi.

Even am facing wrong amount of btc credited back for all my sell orders. Almost 0.07btc is less. Note. I considered even 5% deduction fees. Kindly check my recent traded and credit back the correct btc balance. Thanks

**Comment by manojaum** [comment]
My monyx username is @manojaum

**Comment by monyxcoin** [comment]
@manojaum we'll investigate.

**Comment by manojaum** [comment]
My trades. I calculated at 5% fees deduction, i was supposed to get 0.34btc but i got 0.256. There are some more trades which i did yesterday. Looks like i have issues there too
SELL | 1533.33917433 | 0.00007349 | 0.11268509 | Completed
-- | -- | -- | -- | --
SELL | 400.00000000 | 0.00006500 | 0.02600000 | Completed
SELL | 500.00000000 | 0.00006600 | 0.03300000 | Completed
SELL | 1000.00000000 | 0.00008000 | 0.08000000 | Completed
SELL | 600.00000000 | 0.00007500 | 0.04500000 | Completed
SELL | 400.00000000 | 0.00007000 | 0.02800000 | Completed
SELL | 300.00000000 | 0.00006600 | 0.01980000 | Completed

**Comment by monyxcoin** [comment]
@manojaum ok, thanks. As I said, we will credit all missing funds if needed. Give us some time, I'll keep you updated in this thread.

**Comment by monyxcoin** [comment]
All missing amounts should be credited back.
