### ISSUE TITLE
TX id : 68c931bc0205d52c9f7d6dbe6a6bd688cb76cee0d87c564a989278561d902ca8 missing still

### ISSUE THREAD

**Issue by kalpanos1** [monyxcoin/monyx-coin#46]
Hi,

My deposit is still missing since 16 or more hours ago.You told me earlier that on the next processing transactions my issue should be solved but still my wallet is empty.Please take care this matter as i need to buy  more coins .

Thanks in advance!

**Comment by monyxcoin** [comment]
@kalpanos1 actually I just checked and see no addresses in the database that match the address you sent your deposit to.
From what address did you send the transaction?

**Comment by monyxcoin** [comment]
@kalpanos1 should be deposited, though not sure why that happened. Will investigate.

**Comment by kalpanos1** [comment]
from my bitpanda wallet i sent them yesterday.

**Comment by kalpanos1** [comment]
Also in the transactions history i see my it but still is in pending status so it is there.

**Comment by kalpanos1** [comment]
Ok now i see it in my wallet!Thank you!Time to buy more coins now ;)
