### ISSUE TITLE
Missing Deposit

### ISSUE THREAD

**Issue by cryptocumulate** [monyxcoin/monyx-coin#47]
Hi, I'm still waiting on a BTC are you still processing them? Could you offer an explanation as to what has caused these deposit delays? Thank you.

5dc2f6a43c4ee04c182d82f6026a21403c7815a7aeaf134036f55832fb5dab5a
<img width="972" alt="screen shot 2018-02-07 at 11 17 37" src="https://user-images.githubusercontent.com/36207428/35913718-9b689546-0bf8-11e8-846c-89c08dd53e37.png">

**Comment by monyxcoin** [comment]
@cryptocumulate there was an issue with the 3rd party service we use to process btc transactions, so now we have to process deposits manually in batches.

It should be deposited now.

**Comment by cryptocumulate** [comment]
I see. Well thank you for the response, however, the deposit it still not showing.
