### ISSUE TITLE
5% fees for selling monyx???

### ISSUE THREAD

**Issue by manojaum** [monyxcoin/monyx-coin#48]
Team
 Just now found out that there is 5% fees for selling and only 0.5% fees for buying in the trading exchange. Why there is a insane fees for selling ?? By trading people will loose lot of money here. Please fix it asap and credit back the high fees for my trading

**Comment by monyxcoin** [comment]
@manojaum the decision was made by the team, not me. If I understood correctly, it was done to prevent too active selling of tokens (and building the huge sell wall) for some time.

Anyway the fee is reflected in the form, so people are free to hold their tokens (especially considering the price).
