### ISSUE TITLE
Mac Wallet 3.0.0.1 Fails to start

### ISSUE THREAD

**Issue by doncrypto** [monyxcoin/monyx-coin#5]
https://i.imgur.com/K5o9Ji7.png

https://i.imgur.com/63evMjx.jpg

**Comment by monyxcoin** [comment]
@doncrypto what mac OS version do you use?
Can you please also attach the content of `~/Library/Application Support/Monyx/debug.log` file please?

**Comment by doncrypto** [comment]
Was able to fix my issue by deleting the ~/Library/Application Support/Monyx/ folder and install monyx again.

**Comment by BryerTuck** [comment]
What if I installed the wallet but can't find that folder. /Library/appliation Support/ "no monyx fold" Could is install somewhere else. When I search my hard drive the only Monyx files are the download installer and the app. Any ideas?
