### ISSUE TITLE
Two factor Authentication Problem

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#50]
@monyxcoin why i'm seeing two factor authentication? I didn't activate it..

**Comment by monyxcoin** [comment]
@loydz21 check again?

**Comment by loydz21** [comment]
@monyxcoin my myx and btc is gone

**Comment by monyxcoin** [comment]
@loydz21 will investigate. Can it be that your account compromised and password was stolen?

**Comment by loydz21** [comment]
@monyxcoin Its my accoutn..i lost 2k myx and 0.0407 btc.

**Comment by loydz21** [comment]
@monyxcoin my balance?can i get it back?

**Comment by loydz21** [comment]
@monyxcoin please fix my balances..please

**Comment by monyxcoin** [comment]
@loydz21 we need to investigate. Seems like your account was compromised (password is stolen). I suggest you to change the email password and monyx password.

Once we found out the reason and whether is the breach in our security, we'll decide what to do.

**Comment by loydz21** [comment]
I'll put screen shots for my reference that i have that amount is that ok sir @monyxcoin

**Comment by monyxcoin** [comment]
@loydz21 sure, any information is useful.

**Comment by loydz21** [comment]
Here's my account and balances
![received_1697845430238858](https://user-images.githubusercontent.com/36193728/35915383-a5ccecc8-0c41-11e8-9ed6-872ca054a17e.png)

**Comment by loydz21** [comment]
Please help me sir @monyxcoin

**Comment by loydz21** [comment]
My username is loydz21

**Comment by loydz21** [comment]
![screenshot_2018-02-07-20-03-15](https://user-images.githubusercontent.com/36193728/35916308-f29a7946-0c44-11e8-8eb8-2b0c73e4a541.jpeg)

**Comment by loydz21** [comment]
Please help me retrieve my balances sir @monyxcoin

**Comment by cryptocumulate** [comment]
I also noticed that my MYX balance had for some reason dropped from 500 into decimals of 499. So obviously not a hack but still, strange. Could it be part of the same problem? I mean why would I suddenly be deducted a fraction of a token?

**Comment by loydz21** [comment]
I think some reset my balances..

**Comment by loudiyi1** [comment]
![loid](https://user-images.githubusercontent.com/36209300/35916623-eba91b98-0c02-11e8-8e03-9d1814afe8f5.PNG)
also i have the some problem someone withdraw from my account all balance and sell my monyx 
mu user is : loudiyi
and this is the withdraw transaction 
https://chain.so/tx/BTC/886b181d8555962028d555786575469e0c5dda7b9ed29fceb6040bb4fe95c3cc

**Comment by loydz21** [comment]
Here's withdrawal the
 tx id: 86eb32602b1cf0eeb54ec673a772dad4d236d7d5a802e874a7e1948bbb5a4b5c

**Comment by loydz21** [comment]
Here's my screen shot of withdrawal

![screenshot_2018-02-07-20-34-07](https://user-images.githubusercontent.com/36193728/35916725-5af27628-0c46-11e8-9023-cb7783f9046e.jpeg)

**Comment by monyxcoin** [comment]
@cryptocumulate most likely that's another issue, will check it too.

**Comment by loudiyi1** [comment]
@loydz21  can please give me you whatsapp I may have begun to understand the reason for this farce

**Comment by loydz21** [comment]
@loudiyi1 i don't have whatsapp sir, do you have skype sir?

**Comment by loudiyi1** [comment]
@loydz21  yes ayoub.loudi

**Comment by monyxcoin** [comment]
Withdrawals are enabled, we're working on stolen funds cases and will provide more information as soon as possible.

**Comment by loydz21** [comment]
@loudiyi1 i can't search your detail given

**Comment by loudiyi1** [comment]
@monyxcoin  please fixed this problem in soon possible
Thanks

**Comment by loydz21** [comment]
@monyxcoin thank u so much i hope it goes will..i'll wait for my balances to retrieve.

**Comment by loudiyi1** [comment]
@loydz21 this is it
![skayp](https://user-images.githubusercontent.com/36209300/35917943-e7b72a2a-0c07-11e8-8baf-432882c8d849.PNG)

**Comment by loydz21** [comment]
Ok

**Comment by loydz21** [comment]
Send request

**Comment by loydz21** [comment]
@loudiyi1 i have watsapp now

**Comment by loudiyi1** [comment]
@loydz21  give me your num

**Comment by loydz21** [comment]
@loudiyi1 where can i see my number?

**Comment by loudiyi1** [comment]
+212666844191 add me

**Comment by loydz21** [comment]
@loudiyi1 i can't add i don't know why..i think heres my number +63 9068888456

**Comment by loydz21** [comment]
@monyxcoin whats the progress sir?

**Comment by monyxcoin** [comment]
@loydz21 give us some time please

**Comment by loydz21** [comment]
@monyxcoin ok sir..thank u hope it will fix as soon as posible

**Comment by monyxcoin** [comment]
@loudiyi1 @loydz21 should be fixed now, you are credited with the BTC that was withdrawn from your account. We are still investigating all the cases, the balance can be deducted in case if we found out the withdrawal was correct and your account wasn't compromised.

**Comment by loydz21** [comment]
Thank u so much..
