### ISSUE TITLE
exchange prices dropping too fast

### ISSUE THREAD

**Issue by animalmode** [monyxcoin/monyx-coin#51]
something isn't right with the exchange I believe its being manipulated somehow. Price has dropped from 60 cents to 33 cents very quickly. Please explain.

**Comment by loydz21** [comment]
Coz my 2k myx stolen...

**Comment by loydz21** [comment]
And maybe others 2..

**Comment by monyxcoin** [comment]
@animalmode we disabled withdrawals for some time while we're investigating how some users money were stolen.

**Comment by animalmode** [comment]
price has dropped down to 29 cents. do you believe people were hacked, sold coins, then sent the btc off to the hackers wallets??

**Comment by kalpanos1** [comment]
it is the damn davor anouncement mate which just now closed the lending and seems many guys here are dumping their coins..

**Comment by monyxcoin** [comment]
@animalmode no, we don't think many people were hacked, but I suppose the news about temporary disabled withdrawals made people panicking.

**Comment by animalmode** [comment]
No I dont think its that. something else weird is going on

**Comment by animalmode** [comment]
I believe monyx could do great with davor the scammers out of the way, very important interest is paid in btc for the first 30 days just like loopx is doing, to attract new investors otherwise if people can't cash out their interest like libracoin no new investors will loan their

**Comment by monyxcoin** [comment]
Withdrawals are enabled, we're working on stolen funds cases and will provide more information as soon as possible.
