### ISSUE TITLE
refund my money stolen 

### ISSUE THREAD

**Issue by loudiyi1** [monyxcoin/monyx-coin#52]
Hello
i don't want to go to the wrong place please refund  my myx or btc
my username : loudiyi
![loid](https://user-images.githubusercontent.com/36209300/35916740-5df43a20-0c03-11e8-81e9-1345b7cbd513.PNG)
my friend have Two factor Authentication Problem and the money stolen i'm not habppy to see this from you monyx recover my money
Thanks
![loid](https://user-images.githubusercontent.com/36209300/35916819-a0b1afe6-0c03-11e8-8c2e-e3b4ca135027.PNG)

**Comment by monyxcoin** [comment]
@loudiyi1 I keep opened the other issue for reference: https://github.com/monyxcoin/monyx-coin/issues/50
