### ISSUE TITLE
Funds Not Appearing After 30+ Hours

### ISSUE THREAD

**Issue by VM4ROI** [monyxcoin/monyx-coin#53]
Funds Not Appearing After 24 Hours? Please release my funds so I can purchase more MonyX asap, thanks.

https://cl.ly/pMDo

![image](https://user-images.githubusercontent.com/24924513/35918574-50236d8a-0be0-11e8-9570-ef1aadfcdf97.png)

**Comment by monyxcoin** [comment]
@VM4ROI can you please post here the tx id?

**Comment by monyxcoin** [comment]
@VM4ROI anyway we're still processing the backlog, it should be deposited soon.
