### ISSUE TITLE
withdraw btc

### ISSUE THREAD

**Issue by bheliisya** [monyxcoin/monyx-coin#54]
i withdraw btc and system says wait a confirmation link
i dont get email for confirmation link and my btc just processing
can u help me?

**Comment by monyxcoin** [comment]
@bheliisya is your email specified on the "Settings" page correct?
Check the spam folder?

**Comment by bheliisya** [comment]
nothing from monyx in spam
my email was right

**Comment by monyxcoin** [comment]
@bheliisya what is your username or email?

**Comment by bheliisya** [comment]
![aaa](https://user-images.githubusercontent.com/36233218/35919829-c94f8988-0c48-11e8-8d1e-4ceea7fc3084.png)

**Comment by bheliisya** [comment]
how?

**Comment by monyxcoin** [comment]
@bheliisya emails are sending again. If needed try to make another withdrawal request.

**Comment by bheliisya** [comment]
how to make another withdrawal request if my withdrawal still processing
system says Not enough funds if i make another withdrawal request

**Comment by monyxcoin** [comment]
@bheliisya the old withdrawal should be removed soon.
