### ISSUE TITLE
My monyx is gone

### ISSUE THREAD

**Issue by jaytan17** [monyxcoin/monyx-coin#55]
I have 2fa. When I open my account now my 134 monyx is gone and someone sell and withdrw it!

And my 2fa are disable 

Please help 

Email:Pinedabig10@gmail.com

**Comment by monyxcoin** [comment]
@jaytan17 investigating.

**Comment by jaytan17** [comment]
Thank you so much.even thought I have 2fa your system is not secured.hopefully you fix this. That's my only myx😞

**Comment by 2themoonandback** [comment]
Admin really verify if these people claiming they have been "hacked" are legit. How does a person hack 2fa?? Not saying this guy or woman is lying but really it doesn't make sense. If its 2 to 3 people I would really take a deep look before you start thinking these are real claims and not a few people working together to take advantage of your kindness or help.

**Comment by jaytan17** [comment]
I don't have plan to create this promote by my self.134 monyx is my only monyx in my account and my team know that.

**Comment by jaytan17** [comment]
And u don't have to leave message here.mind your own business.my problem is between me and dev.and we can solve this I believe..

**Comment by jaytan17** [comment]
Admin verify that u better shut your mouth and leave this problem between me and dev

**Comment by 2themoonandback** [comment]
My message was to the admin not to you. If you take it personal you need some help. If your innnocent it shouldnt matter anyhow. I'll say it again Admin DOUBLE CHECK every claim you get. Again we smart people know how hard it is to hack 2fa . Don't let people take advantage of your kindness.

**Comment by jaytan17** [comment]
Really??? U may message support directly
Not in my own problem message right?

**Comment by jaytan17** [comment]
Admin investigate that. For good sake please make your own message to support.

**Comment by jaytan17** [comment]
I'm sure this is hacked.my 2fa suddenly disable even if I enable it. And all of my my are gone

**Comment by jaytan17** [comment]
Myx*

**Comment by monyxcoin** [comment]
@2themoonandback @jaytan17 for now confirmation via email will protect you from any unauthorized withdrawals unless your email is compromised too, that is not our fault.

We will of course investigate this very closely.

**Comment by 2themoonandback** [comment]
Didn't say you weren't hacked again . My message was for the admin. If your taking it personal you need to relax take a few breaths.

**Comment by jaytan17** [comment]
So message them DIRECTLY.

Fyi. This thread is my message to support.

Understand?

**Comment by 2themoonandback** [comment]
Naw its everyones. See how I can type . It was never just yours.

**Comment by jaytan17** [comment]
I'm relax. All u gonna do is mind your own business. As per developer they will investigate it. And I'm sure they see it properly that the transaction being made is not my transaction. I only have 134 myx.oh my God. Please don't message here.

**Comment by 2themoonandback** [comment]
Yes and again All I said was the admin shouldn't believe everyone who CLAIMS they have been hacked if you are not lying you have nothing to be worried about right? So relax and stop whining

**Comment by jaytan17** [comment]
@monyxcoin thank you so much. The transaction is made yesterday. And the email verification is only enable today .

I'm sure you see it. Hopefully you fix this.more power and godbless.

**Comment by jaytan17** [comment]
@2themoonandback please leave this thread between me and the admin. Let them do their job.im sure they will fix that. and don't make comment here.this is my personal support to admin.do your own message to them if u want

**Comment by jaytan17** [comment]
Admin has full power and knowledge in this kind of problem. Let them do their job first. I was hacked yesterday when the email verification is not enable yet.

**Comment by monyxcoin** [comment]
@jaytan17 should be fixed now. We are still investigating all the cases, the balance can be deducted in case if we found out the withdrawal was correct.

**Comment by jaytan17** [comment]
@monyxcoin Ok thanks I only have 134 myx on that account

**Comment by monyxcoin** [comment]
@jaytan17 we credited you the account with the BTC. You can use it to buy more MYX.

**Comment by jaytan17** [comment]
That's ok @monyxcoin.thank you so much.godbless and more power.

**Comment by 24kdreams** [comment]
My 279 Monyx coins was stolen.  Please fix my account.
