### ISSUE TITLE
NO confirmation link 2 times,need a help)

### ISSUE THREAD

**Issue by aid0123** [monyxcoin/monyx-coin#56]
HEllO.HI.I'm really disappointed that you haven't tested enough your new confirmation by e-mail BECAUSE I HAVENT RECEIVED A LINK TO CONFIRM MY WITHDRAWAL ,first I tried to withdraw BTC,then, I've tried to withdraw myx.My username: aid00123 .  PLEASE THIS WORTH A LOT FOR ME,solve the problem please,resend a confirmation link to me,THANKS.

P.S please,for solving this, make a function "resend confirmation link",this will help and make everybody satisfied.THANKS A LOT, hope u won't scam..

**Comment by monyxcoin** [comment]
@aid0123 is your email on the "Settings" page correct?

**Comment by aid0123** [comment]
Glad to talk,MONEYX.I havent set it but had succesfully withdrawn before BTC 2 times

**Comment by aid0123** [comment]
![default](https://user-images.githubusercontent.com/32811954/35920298-b7fe8014-0c41-11e8-904a-ffa407ab109e.png)

**Comment by aid0123** [comment]
CHECK it

**Comment by monyxcoin** [comment]
@aid0123 thanks for the info, check the dashboard message.

**Comment by aid0123** [comment]
Thanks ,too.I Wasnt the only,gueess.HOPING FOR RESOLVING soon))

**Comment by monyxcoin** [comment]
@aid0123 should be resolved. If needed, make another withdrawal request.
