### ISSUE TITLE
Missing BTC deposit

### ISSUE THREAD

**Issue by russahorowitz** [monyxcoin/monyx-coin#57]
Hi i deposited btc to my wallet yesterday, 37zRM8bFkP5gS82m5baPnv7FPe9PT2iUzh  but it's not showing in my account.  

My email is russahorowitz@gmail.com.  Please let me know what the issue is.  Thx

Russ Horowitz
917-588-5553

**Comment by monyxcoin** [comment]
@russahorowitz thanks, we're still processing the backlog. It should be deposited soon.

**Comment by monyxcoin** [comment]
@russahorowitz should be deposited soon.
