### ISSUE TITLE
hack my monyx account 

### ISSUE THREAD

**Issue by rathorepritish** [monyxcoin/monyx-coin#59]
dear sir 

my monyx account hacked today and some sell my 1203 monyx coin  and withdrawal all my btc today i have seen in evening

i have checked and reset my password . kindly request from you please help for return my monyx 1203 coin

My user name is rathorepritish and email address is rathorepritish@gmail.com !

**Comment by 2themoonandback** [comment]
lol really???

**Comment by monyxcoin** [comment]
@rathorepritish investigating.

**Comment by rathorepritish** [comment]
kindly help me its very big amount for me 

i have investment 0.07478707 BTC for 1203 monyx coin

**Comment by monyxcoin** [comment]
@rathorepritish your btc balance should be credited with the missing amount.

**Comment by rathorepritish** [comment]
No sir my monyx account hacked and sold monyx 1203 coin and after that his withdrawal btc

**Comment by 24kdreams** [comment]
Did they resolve your issue?

**Comment by rathorepritish** [comment]
Yes thank you
