### ISSUE TITLE
Adding a share button while withdrawing for free marketing

### ISSUE THREAD

**Issue by emreboy** [monyxcoin/monyx-coin#6]
Hi,

I have an idea for you guys to carry your marketing to another level.

You can add a share button while withdrawing which allows you to share it on facebook or other social platforms showing how much profit you have made percentagewise and showing the btc value etc.

This will make people more willing to get into the platform to show off to their friends how much money they have made and give you a huge free marketing capability.

Please take this idea seriously this may change your platform`s future drastically.

Kind Regards

Emre

**Comment by xStarBlade** [comment]
I second this.

**Comment by monyxcoin** [comment]
Thanks, that's a good idea and we'll most likely implement it once other more important things are done.
