### ISSUE TITLE
MonyX Wallet v2.0.0.2 & v3.0.0.1

### ISSUE THREAD

**Issue by DreamMerchant** [monyxcoin/monyx-coin#60]
Dearest Devs @ MonyX,

I'm having issues firing-up the latest versions of the wallet on MacOs! I've had the first one, which now opens but doesn't sync anymore. The latest ones just crash!

Please do help.

kind regards,

DreamMerchant

**Comment by monyxcoin** [comment]
@DreamMerchant please try to delete `~/Library/Application Support/Monyx` folder (or the folder you specified as a custom).

**Comment by DreamMerchant** [comment]
😜😜😜

Thank you, it works!!
