### ISSUE TITLE
Staking in the monyx wallet OR on the website

### ISSUE THREAD

**Issue by Sirbearingson** [monyxcoin/monyx-coin#61]
Hello @monyxcoin 
i was hoping you could answer some questions in regards to the following..
-will staking take place on the monyx website or the computer wallets
-When will staking be available today
-how long are we expecting a staking period to last 
Yours truly 
Habibi

**Comment by Sirbearingson** [comment]
so i withdraw my tokens from the website and send them to my wallet it will start staking?
will there be a staking platform on the website?

**Comment by animalmode** [comment]
Do i have to keep computer on with wallet open for staking to be working?
