### ISSUE TITLE
made a btc deposit and my deposit hasn't been reflected on my web wallet yet.

### ISSUE THREAD

**Issue by franzb69** [monyxcoin/monyx-coin#62]
https://live.blockcypher.com/btc/tx/73e5ff26efc6fa198ccadbc44c8ee1c718904a60b01da187df6c5586b12c6735/

username franzb69 on monyx

made a deposit of 0.0065 btc

i wanna buy more myx on the exchange.

this is the wallet i deposited to

391CFjJsgfoUQdja57Gem5nPYFJQbt5T5s

thanks

**Comment by monyxcoin** [comment]
@franzb69 should be deposited soon.

**Comment by franzb69** [comment]
Ok thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by monyxcoin** [comment]
@franzb69 should be confirmed now.
