### ISSUE TITLE
Missing Deposit MYX

### ISSUE THREAD

**Issue by ganiom** [monyxcoin/monyx-coin#64]
I Have transfer MYX to another account, is not credited thanks, my Wallet Addres MjdpJ5P4ZzAvCbWE1hmAc5Mung8budqaZP

**Comment by monyxcoin** [comment]
@ganiom should be deposited soon.

**Comment by monyxcoin** [comment]
@ganiom investigating

**Comment by ganiom** [comment]
good, thanks bro

**Comment by monyxcoin** [comment]
@ganiom should be deposited now
