### ISSUE TITLE
withdraw error

### ISSUE THREAD

**Issue by loudiyi1** [monyxcoin/monyx-coin#65]
i get 

Error or the hot wallet is empty and soon will be funded
--

but i'm complet all etap i confirme it from email and thing but without sucess
![withdraw](https://user-images.githubusercontent.com/36209300/35927090-b6a5faa0-0c21-11e8-93bf-d8d5c477c076.PNG)

**Comment by bluppy90** [comment]
Same with me

**Comment by monyxcoin** [comment]
Our hot wallet was empty, we just deposited it, so now withdrawals should be successfull.

**Comment by loudiyi1** [comment]
still the same problem 
![050](https://user-images.githubusercontent.com/36209300/35931263-16d6182e-0c2c-11e8-95c8-66b620585ae3.PNG)
