### ISSUE TITLE
Missing DEPOSIT (MYX)

### ISSUE THREAD

**Issue by mindfocus11** [monyxcoin/monyx-coin#66]
transfer MYX but it's not credited
pls check .

MYX txid: 03293a411d70647551d93bacd06b7469271b154fb7fc00f457cb71799ecad2b2

deposit address not credited : Mte7Ktpi4vDFV4SjfajtVhgUmm9d34mKXV

**Comment by monyxcoin** [comment]
@mindfocus11 should be credited.
