### ISSUE TITLE
Missing BTC after selling MXY

### ISSUE THREAD

**Issue by cryptokiingg** [monyxcoin/monyx-coin#67]
Hello,

There is a bug in the exchange that resulted in me losing ~0.02 BTC. I had a total of 1115 MXY from the ICO which I traded and sold for a price of 0.00007500 - 0.00008000. Therefore my BTC balance should be 0.083625 - 0.0892. However, my current balance is only 0.0625 BTC. Please see screenshot below. I can provide my account details via private message.

Thanks,

![image](https://user-images.githubusercontent.com/36239171/35930235-4286e16a-0be6-11e8-95bf-22ebb978cfa3.png)

**Comment by monyxcoin** [comment]
@cryptokiingg what is your username?

**Comment by royalspin** [comment]
Same problem with me, wrote you on mail and in #68
Name - JohnRameez
Screen - https://i.gyazo.com/34bd81e9a3c7081a4fb9c0a618eea055.png

**Comment by monyxcoin** [comment]
@royalspin @cryptokiingg we identified the problem, your should be credited the missing amount soon.

**Comment by manojaum** [comment]
Same with me. There is other ticket opened for it. Is it fixed ?? My username is @manojaum

**Comment by monyxcoin** [comment]
@manojaum @royalspin @cryptokiingg check your balances please, missing amounts should be credited to you now.

**Comment by royalspin** [comment]
received. thanks

**Comment by monjil43** [comment]
Let's check it.Give us your Profile.

**Comment by manojaum** [comment]
You guys are best as always. Just imagine if some other platform without support team interative like this would hav created too much Fud by now

**Comment by cryptokiingg** [comment]
Thanks, it worked! Monyx to the moooon.
