### ISSUE TITLE
withdraw error

### ISSUE THREAD

**Issue by loudiyi1** [monyxcoin/monyx-coin#68]
still the same problem
![050](https://user-images.githubusercontent.com/36209300/35931316-3a348878-0c2c-11e8-9b80-8c45728ead5c.PNG)

**Comment by royalspin** [comment]
Hello!

I had sell 2500 monyx for 0.00004 = 0.1btc, but received only 0.05 and order closed.
Screen:
https://i.gyazo.com/34bd81e9a3c7081a4fb9c0a618eea055.png

Give me back my monyx or btc, please.

Nickname: JohnRameez
Mail: JohnRameez8@gmail.com

Regards
