### ISSUE TITLE
Withdraw problem

### ISSUE THREAD

**Issue by pawelkop** [monyxcoin/monyx-coin#69]
Hi 
I also have problem with withdraw my btc form exchange , Could you help me?

![bez tytulu](https://user-images.githubusercontent.com/36240297/35932075-fcb6fb92-0c36-11e8-9c0c-2be64d07d823.png)

**Comment by pawelkop** [comment]
My username is: pawel_ko

**Comment by monyxcoin** [comment]
@pawelkop our hot wallet was empty.
