### ISSUE TITLE
External and CMC

### ISSUE THREAD

**Issue by crypttto** [monyxcoin/monyx-coin#70]
@monyxcoin  the community really wants to know when we could expect you to go to an external exchange and when you will be listen on CMC. 

This would be a very smart move hence the "Big" platforms are down, a lot of investors are looking for a ''working'' platform to invest in. 

I remember when Davor only made an announcement that they where going to an external exchange, the price doubled in a week, and when they got external and listed on CMC the price went $150+ within a month. 

I hope Monyx dev's are focusing on going external asap.

really looking forward to your reply.

PS The community is with you and we are all  sta(c)king our coins

**Comment by monyxcoin** [comment]
@crypttto https://monyx.io/news
