### ISSUE TITLE
Monyx deposit missing.

### ISSUE THREAD

**Issue by vaidas1230** [monyxcoin/monyx-coin#71]
Hi i withraw all of my monyx to the windows wallet and everything was perfect received my Monyx within few seconds, yet I decided to try and withraw some of the monyx funds back to my web wallet. Tried twice both times failed. Could you please investigate why deposits to web wallet are not coming through.
1st transaction

Status: 24 confirmations
Date: 07/02/2018 17:51
To: MhzZrvZJoR9se9ECAF5q4WwzdjKSoWVMQc
Debit: -100.00 MYX
Net amount: -100.00 MYX
Transaction ID: 418c469955a74d4fd465bc2b8df978d6a8054fa40db258c0e421b493978469cd

2nd transaction
Status: 6 confirmations, broadcast through 4 nodes
Date: 07/02/2018 18:11
To: MhzZrvZJoR9se9ECAF5q4WwzdjKSoWVMQc
Debit: -80.00 MYX
Net amount: -80.00 MYX
Transaction ID: 0762c07da8f38bc369fa0b5fbe1c9212a625ebeeb7811463a5cda435fb5468de
Thank you Monyx. lets work together to fix all issues.

**Comment by monyxcoin** [comment]
@vaidas1230 sure, give us some time, will get back to you soon.

**Comment by monyxcoin** [comment]
@vaidas1230 thanks for this detailed information, check now please, all missing txs should be deposited.
