### ISSUE TITLE
Withdraw / Deposit missing

### ISSUE THREAD

**Issue by bakuleshkanakia** [monyxcoin/monyx-coin#74]
Dear MonyX team,

I was trying to withdraw 3 MonyX coins to another account. 3 coins got reduced from my account, whereas they did not get credited to the other account I was sending to.

I was sending MonyX tokens from my account bakulesh@gmail.com and depositing to Wallet id McyhdTdag8a2W1c7Z13y6rsLzRE76Za8p4

Can you please look into and please sort out the withdraw issue.

Thanks
Bakulesh

**Comment by monyxcoin** [comment]
@bakuleshkanakia we're working on missing MYX deposits, thanks for the information.

**Comment by monyxcoin** [comment]
@bakuleshkanakia should be deposited now
