### ISSUE TITLE
Haven't received my MYX coin

### ISSUE THREAD

**Issue by aid0123** [monyxcoin/monyx-coin#76]
HI.I have sent 3500 MYX coins to my mac-os wallet but still havent received it and 8 confirmations are already done,I'm starting to get a bit nervous about that, address was correct,i'm sure.
Transaction id :     eeedfb0eadd3b136aa3990cf0e916a03f640826915ae6c37f82f7593825019cb
Wallet has 0 balance still
![myx](https://user-images.githubusercontent.com/32811954/35939484-77448f8e-0c76-11e8-8555-2c0efc29ff66.png)

![myx2](https://user-images.githubusercontent.com/32811954/35939494-80ec2f88-0c76-11e8-932b-4c84260f64c3.png)

THANKS

HELP,PLS

**Comment by aid0123** [comment]
3500 ISNT A LARGE AMOUNT,why still no coins

**Comment by aid0123** [comment]
my username: aid00123    if needed

**Comment by monyxcoin** [comment]
@aid0123 it shows that your wallet is not synced. Did you download the latest wallet version?

Can you post here the content of `~/Library/Application Support/Monyx/debug.log` file?

**Comment by aid0123** [comment]
pls,explain how to do that

**Comment by aid0123** [comment]
I dont actually remember what version of wallet I have downloaded .Does it mean that ive lost funds?I just downloaded a first wallet I so maybe 7 days ago.Am I stupid or not

**Comment by aid0123** [comment]
https://docs.google.com/document/d/1kQf4rc-WYmAvKGfINmUVSNWPe0oI3X3qP7a1VfcURgM/edit?usp=sharing

**Comment by aid0123** [comment]
please solve my issue

**Comment by aid0123** [comment]
PLEASE

**Comment by monyxcoin** [comment]
@aid0123 try to delete everything **EXCEPT** the 'wallet.dat' file in `~/Library/Application Support/Monyx` folder, download the new wallet and run it again?

**Comment by aid0123** [comment]
Ok,i will try

**Comment by aid0123** [comment]
If this is going to be solved u gonna be named the best lending platform ,at least by me.I will spread how kind and reliable your support is,thnx)

**Comment by monyxcoin** [comment]
@aid0123 can't promise anything, but I suppose the private keys must be still in the wallet file, so theoretically you should have access to the address once new wallet is synced.

**Comment by aid0123** [comment]
Can I get a refund if goes wrong.Can't afford to lose this...I went all in believing in you..

**Comment by aid0123** [comment]
NEXT time i;m gonna be 10 times more accurate

**Comment by aid0123** [comment]
maan, I swear currently u are the best lending platform, at least because of perfect support.REALLY nice work, continue it, deserves attention of other people.Thnx,I will try to spread it

**Comment by aid0123** [comment]
Big respect,thumbs up
