### ISSUE TITLE
windows wallet 64

### ISSUE THREAD

**Issue by KMD89** [monyxcoin/monyx-coin#77]
@monyxcoin Hey guys i cant download the windows wallet, every time i do, my virus scanner says that they found a virus in that document and they block it..

What can i do? i wanna start start stacking

**Comment by aid0123** [comment]
ALLOW YOUR ANTIVIRUS DOWNLOADING PROGRAMMS FROM THE INTERNET.Change it in the settings

**Comment by KMD89** [comment]
i dont know what u guys did but it works now keep up the good work..
