### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by puttjattda** [monyxcoin/monyx-coin#79]
Hi,

Will staking be available on the platform? i see you got a Tab for it, similar to the way DavorCoin had their staking set up?

**Comment by aid0123** [comment]
Stacking is already set up ,check latest news on their website : ttps://monyx.io/news . .

**Comment by puttjattda** [comment]
@aid0123 yeh i know you can stake with your desktop wallet, but what I am asking can you still stake with an online wallet within the platform like DavorCoin does

**Comment by JamjamMcjammerson** [comment]
Mac wallet isn't working (crashes instantly while trying to startup) and I would like to stake so need an alternative as well.

**Comment by monyxcoin** [comment]
@puttjattda not right now, we're still dealing with the exchange launch
