### ISSUE TITLE
Website Missing Bitcoin Wallet Addresses for New Users

### ISSUE THREAD

**Issue by doncrypto** [monyxcoin/monyx-coin#8]
Hi Dev, we are having many issues where recent sign ups do not have access to a bitcoin wallet address to deposit and be ready for exchange. Just wanted to bring this up and let you know if you haven't heard. Feel free to close this issue. We are also sending emails but we know how much emails support receives.

**Comment by monyxcoin** [comment]
@doncrypto thanks for the information! I'll ask the dev who works on the website what's up with that.

**Comment by new2018man** [comment]
@monyxcoin what is about exchange?

**Comment by doncrypto** [comment]
Reports that btc addresses is still not working for newer sign ups.
