### ISSUE TITLE
Trading problem

### ISSUE THREAD

**Issue by loydz21** [monyxcoin/monyx-coin#80]
@monyxcoin sir i can't put the amount monyx in selling..what happen?

**Comment by loydz21** [comment]
@monyxcoin it warns empty amount when i click all button please help.

**Comment by loydz21** [comment]
Here's the screen shot
![screenshot_2018-02-08-05-19-46](https://user-images.githubusercontent.com/36193728/35942171-c3af77f8-0c8f-11e8-95de-bbad0e819157.jpeg)

**Comment by marcelvan** [comment]
i also have this problem

**Comment by chass3768** [comment]
I also have this problem

**Comment by ep0z85** [comment]
Looks like a sell limit. 23:37:50 UTC lets hope it will reset in 22min !

**Comment by monyxcoin** [comment]
The exchange team added the sell limit, if I understand correctly. 1000 tokens per trading to sell.

**Comment by marcelvan** [comment]
Awesome thank you so much

**Comment by loydz21** [comment]
Even 1000 myx..
![screenshot_2018-02-08-08-44-48](https://user-images.githubusercontent.com/36193728/35949438-6b6814e8-0cac-11e8-8257-9b6ce48a2bc5.jpeg)

**Comment by loydz21** [comment]
@monyxcoin ahhh..i see thank you sir.. :1st_place_medal:

**Comment by loydz21** [comment]
@monyxcoin last question how many minutes can i wait to trade again sir?

**Comment by marcelvan** [comment]
@monyxcoin Is it 1000 limit per day?  Or is there a time limit. Also I
really do like this idea of limited sell orders

**Comment by loydz21** [comment]
@monyxcoin I approve to the limit amount not limits of trading.

**Comment by loydz21** [comment]
@marcelvan Yes, I agree but I hope not limit of trading..

**Comment by marcelvan** [comment]
Any updates on how things are going with the Withdrawal problem  ?
