### ISSUE TITLE
Bug showing 0 available MYX balance

### ISSUE THREAD

**Issue by cryptokiingg** [monyxcoin/monyx-coin#81]
Hello,

There is a bug that's not allowing me to sell. My balance available to sell shows 0 even though I have over 1000 MYX coins. See below. 

Thanks in advance, I know you guys are doing everything you can to clear out all these early bugs.

![image](https://user-images.githubusercontent.com/36239171/35942101-72f254ce-0c09-11e8-92cd-ea884690a6a7.png)

**Comment by loydz21** [comment]
Mine too

**Comment by chass3768** [comment]
Having same issue, when I can get the exchange to load.

**Comment by monjil43** [comment]
It's nothing. Only bugs. You can whatever you want.

**Comment by manojaum** [comment]
it is not bug. They had enabled some sell limits now. enter some monyx manually, u will get the message that sell limit is reached

**Comment by loydz21** [comment]
@manojaum even with the minimum amount which is 20myx it appears it exceed to the limits

**Comment by monyxcoin** [comment]
Right, that's the sell limit that resets every day at 00:00:00 UTC.
