### ISSUE TITLE
windows wallet netwoek connection

### ISSUE THREAD

**Issue by OgRastaman** [monyxcoin/monyx-coin#83]
![screenshot 17](https://user-images.githubusercontent.com/36246120/35952497-19d63eb0-0c35-11e8-8ac1-3a0b0cf4680c.png)
i downloaded the windows wallet it is saying not syncing i have had the wallet open for 2 hours now and not connecting to the network
 here is the debug log i was able to get connected to the network and was able to successfully send some monyx tokens to the wallet i restarted my pc  mow restarted the walet and it is coming up i get this error message when i go to retry it shuts down when i hit ignore it loads the wallet but will not connect to the network  i add a screen shot of the error msg im reciving

[debug.log](https://github.com/monyxcoin/monyx-coin/files/1705471/debug.log)
[debug.log](https://github.com/monyxcoin/monyx-coin/files/1705477/debug.log)

**Comment by monyxcoin** [comment]
@OgRastaman post your `debug.log` file from the wallet folder please.

**Comment by anj2208** [comment]
I have same issue...looks like connection error..attached is my debug.log
[debug.log](https://github.com/monyxcoin/monyx-coin/files/1705321/debug.log)

**Comment by monyxcoin** [comment]
Thanks for the info, I'll investigate.

**Comment by monyxcoin** [comment]
@anj2208 try to delete everything in the wallet folder **EXCEPT** `wallet.dat` file and start the wallet again.
