### ISSUE TITLE
My coins we're stolen

### ISSUE THREAD

**Issue by 24kdreams** [monyxcoin/monyx-coin#84]
My coins we're stolen..... please fix this! I never received an email confirmation for ant withdrawal so why was this transaction approved.   Please rectify this matter.
Thank you.

**Comment by monjil43** [comment]
Please check your smap mail.

**Comment by 24kdreams** [comment]
@monjil43 check what?

**Comment by monjil43** [comment]
Go to your mail id and check in smap mail. You will have confirmation mail

**Comment by 24kdreams** [comment]
Admin please fix my account.  My account was hacked...my 279 MYX coins are gone!
I never requested a withdrawal!
My username: 24kdreams
Email: 24kdreamsmedia@gmail.com
