### ISSUE TITLE
To the github dev..

### ISSUE THREAD

**Issue by xStarBlade** [monyxcoin/monyx-coin#85]
We trust you guys know what you are doing, I won't question your choices, however, I would like to know more about those choices and so would others. Are you turning into a staking platform 100%? What will the payout and stuff be? If you had something else in mind, could you explain it in a sufficient amount of detail please? Can you tell me why people will want to buy this coin over any other coin going forward? What kind of  growth should we as investors expect from Monyx now?

**Comment by monyxcoin** [comment]
@xStarBlade we need few days to deal with all the things, the official statement about future plans will be ready soon.
