### ISSUE TITLE
Exchange is not loading! Can't initiate trade!

### ISSUE THREAD

**Issue by chass3768** [monyxcoin/monyx-coin#88]
The exchange is not loading on laptop or phone! If I do get it to laod, can't initiate a trade, clicking all says zero balance, even though I have 466 coins. 
Please fix these issues as soon as possible.

Thank you

**Comment by manojaum** [comment]
Looks like they enabled some sell limit for a day. enter your monyx coin manually, u will get the message

**Comment by chass3768** [comment]
Says I have 0.0000 myx available to sell right now even though I have 466.

**Comment by manojaum** [comment]
yeah, same with me. I think after they announce no more lending, to avoid big dump, they disabled selling

**Comment by chass3768** [comment]
Exchange is active and others are selling and buying. Monyx is costing me money right now. Monyx please fix my MYX balance, I should have 466 coins to trade with! Username chass3768!!!

**Comment by monyxcoin** [comment]
The exchange team added the sell limit, if I understand correctly. 1000 tokens per trading day to sell.
