### ISSUE TITLE
Commissions for referrals

### ISSUE THREAD

**Issue by CANADAMONYX** [monyxcoin/monyx-coin#90]
Username: CanadaMonyx

Email: financialprotectionsystem@gmail.com

**Not receiving any referral tokens for affiliate referrals**. Does this come later??.....see below:

Date | Username | Email | Level | Commission
-- | -- | -- | -- | --
07/02/2018, 23:01:31 | branvold | ronbranvold@protonmail.com | 1 (8%) | -
07/02/2018, 22:47:55 | KOSTIDAS | NICKKOSTIDAS@PROTONMAIL.COM | 1 (8%) | -
07/02/2018, 22:23:00 | cotton7586 | cotton7586@hotmail.com | 1 (8%) | -
07/02/2018, 16:19:26 | Bryan13 | biffrudiak@hotmail.com | 1 (8%) | -
07/02/2018, 00:43:41 | jncap | drjohncaplinger@gmail.com | 1 (8%) | -
06/02/2018, 23:18:20 | Maianadw2018 | maianadw20022@aol.com | 1 (8%) | -
06/02/2018, 22:54:17 | viper311 | mscubado@yahoo.com | 1 (8%) | -
06/02/2018, 20:23:54 | stevehyjek | stevehyjek@gmail.com | 1 (8%) | -
06/02/2018, 15:02:02 | catanzarite | JEFFCATANZARITE@PROTONMAIL.COM | 1 (8%) | -
31/01/2018, 21:26:03 | drdougdc | desalvo@protonmail.com | 1 (8%) | -

Please review and advise

**Comment by doncrypto** [comment]
Hi Canadamonyx. You get commissions from the ICO only if your referrals bought monyx coins(the ICO is over). The next place to earn commissions is from your referrals making loans to the lending platform which hasn’t even been released and might not be released. Hope this clears any confusion.

**Comment by monyxcoin** [comment]
@doncrypto is right, referrals were active only for ICO-presale stage, sorry for confusion.

We're working on stabilizing the exchange, after that we'll clean up the site to avoid more confusion.
