### ISSUE TITLE
error msg when openin up windows wallet 

### ISSUE THREAD

**Issue by OgRastaman** [monyxcoin/monyx-coin#93]
my wallet was working and connected to the network i did test sends of monyx to my wallet they went through fine now i restarted my pc and i get this error message, when i bypass and push ignore the wallet will open i see my tokens but the wallet does not connect to the network please help 
![screenshot 18](https://user-images.githubusercontent.com/36246120/35954629-98b8d6fc-0c3f-11e8-94a8-557aa7eecb87.png)
 
[debug1.txt](https://github.com/monyxcoin/monyx-coin/files/1705670/debug1.txt)

**Comment by monyxcoin** [comment]
@OgRastaman as one of possible solutions you can try to delete everything in the wallet folder **EXCEPT** `wallet.dat` file and start the wallet again.

**Comment by OgRastaman** [comment]
thank you very much i deleted the files except for the wallet.dat file and i was able to restart my wallet and connection was established in 5 min thank you for the quick response
