### ISSUE TITLE
MYX Deposit missing

### ISSUE THREAD

**Issue by pnguyen32** [monyxcoin/monyx-coin#94]
I deposit from my web wallet to the address that is provided on the website and the coin is missing. The transaction is confirmed within the network but not reflect on my "Deposit History" or "Balance"

**Comment by animalmode** [comment]
Mine took 24 hours to arrive. If it doesn't arrive by then, I would contact monyx again.

**Comment by monyxcoin** [comment]
@pnguyen32 it should be deposited already, create a new issue if it's still missing.
