### ISSUE TITLE
Withdrawals question

### ISSUE THREAD

**Issue by aid0123** [monyxcoin/monyx-coin#96]
Hello.I have a question : when are you going to allow people to withdraw again,pls give an approximte time if can,thank you.

**Comment by aid0123** [comment]
Please, announce lending date asap , price mught go down more if u wont do this within next days

**Comment by chass3768** [comment]
At this point there may not be any lending? Go read the announcement in the news section on the dashboard.

**Comment by aid0123** [comment]
Yes I 've read it

**Comment by monyxcoin** [comment]
Withdrawals will be enabled in the coming days, we're analyzing all the orders were made in few past days to be sure nobody is credited/funded incorrect amounts. Your BTC is safe and it's done to prevent any losses that can damage the project.
