### ISSUE TITLE
online staking

### ISSUE THREAD

**Issue by kalpanos1** [monyxcoin/monyx-coin#97]
Hi,

When you think monyx will provide online staking as well, as i want to avoid the technical issues for making staking on a windows wallet?

Thanks

**Comment by monyxcoin** [comment]
@kalpanos1 we're still working on stabilizing the exchange and all related stuff, so no information about online staking yet, sorry.

There shouldn't be any technical issues with a wallet, especially if it's not an older macOS version, that is not currently compatible.
