### ISSUE TITLE
MYX Deposit missed

### ISSUE THREAD

**Issue by bnoizem** [monyxcoin/monyx-coin#98]
Hello, I have sent from OSX Wallet MYX to my account at monyx.io and it still didn't come.

I have sent it 07.02.2018 at 12:30, it passed one day (but written needed just 3 confirmation).

What happened?

Thank you.

**Comment by monyxcoin** [comment]
@bnoizem what is your username? Tx id?

**Comment by bnoizem** [comment]
@monyxcoin - bnoize

**Comment by bnoizem** [comment]
@monyxcoin ID: 5e56600b6780b55394373daececf132b3da84359234d8ee02d21c7b51a11b23b

**Comment by monyxcoin** [comment]
@bnoizem there is no such TX id: http://explorer.monyx.io/tx/5e56600b6780b55394373daececf132b3da84359234d8ee02d21c7b51a11b23b

**Comment by bnoizem** [comment]
@monyxcoin how come this could be?

here is screenshot.

<img width="732" alt="skrinshot2_4823538_29309304" src="https://user-images.githubusercontent.com/36266582/36018733-e1e8ee6c-0d8d-11e8-9e97-02e7dce42d43.png">

**Comment by bnoizem** [comment]
@monyxcoin here is my wallet information.
<img width="752" alt="skrinshot2_6180893_29309370" src="https://user-images.githubusercontent.com/36266582/36018930-8e9900c0-0d8e-11e8-8f3b-7cb15f69bd2b.png">

Maybe this depend on resetting blockchain before internal exchange?

**Comment by bnoizem** [comment]
@monyxcoin ?

**Comment by monyxcoin** [comment]
@bnoizem yes, you are using the old wallet. As it was stated before, we had to make a hard-fork (basically reset) of the blockchain. You need to delete everything from the monyx folder **EXCEPT** `wallet.dat` file and download the new wallet.

**Comment by bnoizem** [comment]
I installed new wallet and moved my wallet.dat into it.

My windows wallet had been synchronized. But now i can't see my balance. 

And all of my old transactions with question sign (?).

The earliest transactions is dated 01.02.2018 08:33, the oldest trascation dated 11.02.2018 20:10.

What I did wrong?

**Comment by bnoizem** [comment]
But balances and latest transactions written (not synchronized).

Do I need to wait?

**Comment by bnoizem** [comment]
So, its fully synchronized and I steel can't see my balance from old wallet.

**Comment by monyxcoin** [comment]
@bnoizem you were doing transactions in the old blockchain network. Now you are synced with the new one - after hardfork. There is nothing we can do, since basically you was doing all operations in a different blockchain.

**Comment by bnoizem** [comment]
@monyxcoin ok, but my last transactions before hardfork were  04.02.2018 16:34, right before its.

Why I can't see my balance which I had BEFORE this hardfork?

**Comment by monyxcoin** [comment]
@bnoizem because now you use the new wallet. If you want to see transactions before the hardfork,  you can use the old wallet.

**Comment by mmgva** [comment]
good afternoon monyx team! Here there must be an error I have never withdrawn coins nor will I like your platform and I trust that it will be great! before its keeping I had in my wallet 1256 coins now I only have 400 monedes please I ask for my coins back thanks !! Nombre de usuario Mjrg02

**Comment by bnoizem** [comment]
@monyxcoin is there any way I can move coins from old wallet to the new wallet?

**Comment by mmgva** [comment]
I do not understand why I would have to do that? I only use the internal
portfolio of monyx! since yesterday I am waiting for the complete
replacement of my 1356 monyx coins that I decided to leave on the platform
relying on your project

**Comment by mmgva** [comment]
Quisiera saber que ha pasado con mi reclamo aun no llegan el resto de las monedas aun faltan 856

**Comment by revbukola** [comment]
Hello please I have have my monyx coin in the wallet I used to buy it during the ICO.
So where do I move my coins to to be able to stake them?

**Comment by monyxcoin** [comment]
@revbukola download the wallet from https://github.com/monyxcoin/monyx-coin/releases page.
