### ISSUE TITLE
EXCHANGE IS NOT LOADING! 

### ISSUE THREAD

**Issue by chass3768** [monyxcoin/monyx-coin#99]
I get the white page with a flashing Monyx logo. It is happening on both phone and laptop! Please fix this!

**Comment by monyxcoin** [comment]
@chass3768 what browser do you use? Doesn't it load at all or just sometimes?

Regarding the limit - can't provide any response, that's not my decision, but the team who runs the exchange.

**Comment by chass3768** [comment]
I use the chrome browser. It is sticking on the white page with the flashing monyx logo.

**Comment by manojaum** [comment]
Manipulation killed many platforms. For organic growth, free trading needs to be provided in the initial days where weak hands will move out and strong hands accumulate. Trading volume will keep on reducing by doing this limitations. Its not good for monyx

**Comment by chass3768** [comment]
It is doing the same thing with internet explorer browser also.

**Comment by monyxcoin** [comment]
@chass3768 yes, that's the valid point, I'll bring up that to the team.

**Comment by monyxcoin** [comment]
@chass3768 ok, we'll try to fix it.
